/* Login */
setLanguage=function(lang){const next=typeof normalizeOleiroLanguage==='function'?(normalizeOleiroLanguage(lang)||'pt'):lang;localStorage.setItem('oleiro-language',next);if(typeof closeLanguageModal==='function')closeLanguageModal();location.reload();};

let loginTransitionTimer=null;
function isDevMode(){return new URLSearchParams(location.search).get('dev')==='1'}
function destinationFor(role){const suffix=isDevMode()?'?dev=1':'';if(role==='manager')return `admin/${suffix}`;if(role==='volunteer')return `portal/${suffix}`;return `inactive.html${suffix}`}
function startLoginTransition(role,mode=null){if(loginTransitionTimer)return;if(role)sessionStorage.setItem('oleiro-role',role);if(mode)sessionStorage.setItem('oleiro-volunteer-mode',mode);const overlay=document.getElementById('loginLoading');const button=document.getElementById('loginButton');if(button)button.disabled=true;if(overlay)overlay.hidden=false;loginTransitionTimer=setTimeout(()=>{location.href=destinationFor(role)},850)}
async function handleLogin(){const email=document.getElementById('email')?.value.trim()||'',password=document.getElementById('password')?.value||'';if(window.OleiroAuth&&typeof window.OleiroAuth.signIn==='function'){try{const session=await window.OleiroAuth.signIn({email,password});if(!session?.role)throw new Error('Sessão inválida.');return startLoginTransition(session.role,session.mode||null)}catch(error){return showLoginMessage(error?.message||'Não foi possível entrar.')}}if(isDevMode()){const role=sessionStorage.getItem('oleiro-role')||'manager';const mode=role==='volunteer'?(sessionStorage.getItem('oleiro-volunteer-mode')||'candidate'):null;return startLoginTransition(role,mode)}showLoginMessage('Autenticação em configuração. O acesso será liberado quando o backend estiver conectado.')}
function chooseDevRole(role,mode){sessionStorage.setItem('oleiro-role',role);if(mode)sessionStorage.setItem('oleiro-volunteer-mode',mode);startLoginTransition(role,mode)}
function showLoginMessage(text){const el=document.getElementById('loginMessage');if(!el)return;el.textContent=typeof translateText==='function'?translateText(text):text;el.hidden=false}
document.addEventListener('DOMContentLoaded',()=>{const devPanel=document.getElementById('devPanel');if(devPanel&&isDevMode())devPanel.hidden=false});
