/* Comportamentos do Portal conectados à sessão real. */
const _oleiroVolunteerHomeBase=volunteerHome;
volunteerHome=function(){let html=_oleiroVolunteerHomeBase();html=html.replace(/onclick="state\.volunteerPage='info';render\(\)"/g,`onclick="navigateVolunteer('info')"`);if(state.volunteerMode==='approved'){const marker='<section class="section"><div class="section-head"><div><h2>Informações importantes</h2>';const idx=html.indexOf(marker);if(idx>=0)html=html.slice(0,idx)}return html;};
volunteerMenu=function(){return `<section class="section"><div class="section-head"><div><span class="eyebrow">Portal</span><h2>Menu</h2><p>Conta e preferências</p></div></div><div class="menu-list">${menuLink('fa-language','Idioma','Português, English ou Español',"openLanguageModal()")}${menuLink('fa-user','Perfil do voluntário','Dados pessoais e do acesso',"openVolunteerProfile()")}${menuLink('fa-right-from-bracket','Sair','Encerrar sessão','logout()')}</div></section>`;};

const _v3VolunteerHomeBase=volunteerHome;
volunteerHome=function(){let html=_v3VolunteerHomeBase();html=html.replace(/onclick="state\.volunteerPage='([^']+)';render\(\)"/g,(_m,page)=>`onclick="navigateVolunteer('${page}')"`);return html;};
function portalIsoDate(value){if(!value)return null;if(typeof value==='string')return value.slice(0,10);if(typeof value.toDate==='function')return value.toDate().toISOString().slice(0,10);return null}
function portalDateRange(start,end){if(!start||!end||end<start)return [];const rows=[];let current=start;for(let i=0;i<370&&current<=end;i++){rows.push(current);current=addDays(current,1)}return rows}
volunteerStayDates=function(){const application=state.currentApplication||{};return portalDateRange(portalIsoDate(application.stayStart),portalIsoDate(application.stayEnd));};
volunteerHomeActivityCard=function(s){return `<button class="list-item clickable volunteer-home-activity" onclick="navigateVolunteer('agenda')"><div class="time-box single"><strong>${s.activity.time||'—'}</strong></div><div class="item-main"><h3>${escapeHtml(s.activity.name||'Atividade')}</h3><p>${fmtDate(s.date)} • ${escapeHtml(s.group||'A definir')}</p><div class="item-meta">${badge('Confirmada','success')}</div></div><i class="fa-solid fa-chevron-right" style="color:var(--muted);align-self:center"></i></button>`;};
openActivityModal=function(date=null,id=null){
  if(state.volunteerMode==='approved')return showToast('Após a aprovação, mudanças devem ser solicitadas pela agenda.');
  if(!['draft','adjustments'].includes(state.volunteerPlanStatus||'draft'))return showToast('O planejamento já foi enviado. Aguarde a análise da Casa.');
  const a=id?state.activities.find(x=>String(x.id)===String(id)):null,availableDates=volunteerStayDates(),defaultDate=date||availableDates[0]||'';
  const body=`<div class="form-grid activity-modal-form"><div class="field"><label for="actName">Nome da atividade</label><input id="actName" class="input" value="${escapeHtml(a?.name||'')}" placeholder="Ex.: Conversação em inglês"></div><div class="field"><label for="actDesc">Descrição</label><textarea id="actDesc" class="textarea" placeholder="Como a atividade funciona?">${escapeHtml(a?.description||'')}</textarea></div><div class="field-row"><div class="field"><label for="actDuration">Duração</label><select id="actDuration" class="select">${[30,60,90,120].map(v=>`<option value="${v}" ${a&&Number(a.duration)===v?'selected':''}>${v===90?'1h30':v===120?'2h':v+' min'}</option>`).join('')}</select></div><div class="field"><label for="actParticipation">Participação</label><select id="actParticipation" class="select">${['Até 5','Até 10','Livre','Outro'].map(v=>`<option ${a&&a.participation===v?'selected':''}>${v}</option>`).join('')}</select></div></div><div class="field"><label for="actMaterials">Materiais necessários</label><input id="actMaterials" class="input" value="${escapeHtml(a?.materials||'')}" placeholder="Nenhum, quadro, bola..."></div><div class="field"><label for="actNotes">Observações</label><textarea id="actNotes" class="textarea" placeholder="Opcional">${escapeHtml(a?.notes||'')}</textarea></div><div class="field-row"><div class="field"><label for="actPeriod">Período preferido</label><select id="actPeriod" class="select">${['Manhã','Tarde','Noite','Sem preferência'].map(v=>`<option ${a&&a.period===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label for="actTime">Horário sugerido</label><input id="actTime" class="input" type="time" value="${a?.time||'15:15'}"><small>Opcional.</small></div></div><div class="field"><label>Datas em que deseja realizar</label><div class="check-grid activity-date-grid">${availableDates.length?availableDates.map(d=>`<label class="check-card"><input type="checkbox" name="actDate" value="${d}" ${(a&&Array.isArray(a.dates)&&a.dates.includes(d))||(!a&&d===defaultDate)?'checked':''}><span>${dayName(d)} ${fmtDate(d,true)}</span></label>`).join(''):'<div class="empty">Período de estadia ainda não definido.</div>'}</div></div></div>`;
  const footer=`<button class="btn btn-primary btn-block" type="button" onclick='saveActivity(${a?JSON.stringify(a.id):'null'})'>${a?'Salvar alterações':'Adicionar atividade'}</button>`;
  openModal(a?'Editar atividade':'Nova atividade',a?'A descrição é compartilhada entre todas as sessões.':'Cadastre uma vez e selecione quantas datas precisar.',body,footer);modalRoot.querySelector('.modal')?.classList.add('activity-modal');
};
window.volunteerHome=volunteerHome;window.volunteerPlan=volunteerPlan;

function renderVolunteer(){const pages={home:typeof volunteerHome==='function'?volunteerHome:null,plan:typeof volunteerPlan==='function'?volunteerPlan:null,agenda:typeof volunteerAgenda==='function'?volunteerAgenda:null,stay:typeof volunteerStay==='function'?volunteerStay:null,info:typeof volunteerInfo==='function'?volunteerInfo:null,menu:typeof volunteerMenu==='function'?volunteerMenu:null};const pageFn=pages[state.volunteerPage]||pages.home;let content='';try{if(typeof pageFn!=='function')throw new Error('Módulo do portal indisponível.');content=pageFn()}catch(error){console.error('Erro ao renderizar portal:',error);content=`<section class="section"><div class="notice danger"><i class="fa-solid fa-triangle-exclamation"></i><div><strong>Não foi possível abrir esta tela.</strong><br>Atualize a página. Se o problema continuar, volte ao início.</div></div><button class="btn btn-primary btn-block" style="margin-top:12px" onclick="navigateVolunteer('home')">Voltar ao início</button></section>`}app.innerHTML=header('',true)+`<main class="page">${content}</main>`;navRoot.innerHTML=volunteerNav();if(typeof applyI18n==='function'){applyI18n(app);applyI18n(navRoot)}}
function render(){renderVolunteer()}
function planStatusFromApplication(status){return status==='adjustments'?'adjustments':status==='analysis'?'submitted':status==='approved'?'approved':status==='rejected'?'rejected':'draft'}
async function hydrateVolunteerPlanning(application){
  if(!application?.id||!window.OleiroServices?.planning)return;
  const from=portalIsoDate(application.stayStart),to=portalIsoDate(application.stayEnd);
  const [activities,sessions]=await Promise.all([window.OleiroServices.planning.listActivities(application.id),window.OleiroServices.planning.listSessions({applicationId:application.id,from,to})]);
  state.sessions=sessions||[];
  const byActivity=new Map((activities||[]).map(activity=>[String(activity.id),{...activity,dates:[],time:activity.time||''}]));state.sessionStatus={};state.sessionGroups={};
  state.sessions.forEach(session=>{const activity=byActivity.get(String(session.activityId||''));if(activity){if(session.date&&!activity.dates.includes(session.date))activity.dates.push(session.date);if(!activity.time&&session.time)activity.time=session.time}if(session.activityId&&session.date){state.sessionStatus[`${session.activityId}-${session.date}`]=session.status||'proposed';state.sessionGroups[`${session.activityId}-${session.date}`]=session.groupId||'A definir'}});
  state.activities=[...byActivity.values()];
}
async function bootVolunteer(){
  const session=await window.OleiroAuthGuard?.requireRole('volunteer');if(!session)return;
  state.role='volunteer';state.currentSession=session;state.currentApplication=session.application||null;state.volunteerMode=session.mode||'candidate';state.volunteerPlanStatus=planStatusFromApplication(session.application?.status);state.volunteerPage='home';
  try{await hydrateVolunteerPlanning(session.application)}catch(error){console.error('Falha ao carregar planejamento:',error)}render();
}
bootVolunteer();
