/* Comportamentos do Portal conectados à sessão real. */
const _oleiroVolunteerHomeBase=volunteerHome;
volunteerHome=function(){let html=_oleiroVolunteerHomeBase();html=html.replace(/onclick="state\.volunteerPage='info';render\(\)"/g,`onclick="navigateVolunteer('info')"`);if(state.volunteerMode==='approved'){const marker='<section class="section"><div class="section-head"><div><h2>Informações importantes</h2>';const idx=html.indexOf(marker);if(idx>=0)html=html.slice(0,idx)}return html;};
const _v3VolunteerHomeBase=volunteerHome;
volunteerHome=function(){let html=_v3VolunteerHomeBase();html=html.replace(/onclick="state\.volunteerPage='([^']+)';render\(\)"/g,(_m,page)=>`onclick="navigateVolunteer('${page}')"`);return html;};
function portalIsoDate(value){if(!value)return null;if(typeof value==='string')return value.slice(0,10);if(typeof value.toDate==='function')return value.toDate().toISOString().slice(0,10);return null}
function portalDateRange(start,end){if(!start||!end||end<start)return [];const rows=[];let current=start;for(let i=0;i<370&&current<=end;i++){rows.push(current);current=addDays(current,1)}return rows}
volunteerStayDates=function(){const application=state.currentApplication||{};return portalDateRange(portalIsoDate(application.stayStart),portalIsoDate(application.stayEnd));};
function portalStoredOption(value,current){return `<option value="${escapeHtml(value)}" ${current===value?'selected':''}>${escapeHtml(typeof tValue==='function'?tValue(value):value)}</option>`}
openActivityModal=function(date=null,id=null){
  const approved=state.volunteerMode==='approved',a=id?state.activities.find(x=>String(x.id)===String(id)):null,postApprovalEdit=approved&&a?.postApprovalProposal===true&&a?.reviewStatus==='adjustments';
  if(approved&&id&&!postApprovalEdit)return showToast(t('portal.activity.adjustLocked'));
  if(!approved&&!['draft','submitted','adjustments'].includes(state.volunteerPlanStatus||'draft'))return showToast(t('portal.activity.locked'));
  const availableDates=volunteerStayDates(),defaultDate=date||availableDates[0]||'',participation=a?.participation||'',period=a?.period||'';
  const body=`<div class="form-grid activity-modal-form">${postApprovalEdit&&a?.reviewNote?`<div class="notice warning"><i class="fa-solid fa-rotate"></i><div><strong>${escapeHtml(t('portal.activity.adjustRequested'))}</strong><br><span data-no-i18n>${escapeHtml(a.reviewNote)}</span></div></div>`:''}<div class="field"><label for="actName">${escapeHtml(t('portal.activity.name'))}</label><input id="actName" class="input" value="${escapeHtml(a?.name||'')}" placeholder="${escapeHtml(t('portal.activity.namePlaceholder'))}"></div><div class="field"><label for="actDesc">${escapeHtml(t('portal.activity.description'))}</label><textarea id="actDesc" class="textarea" placeholder="${escapeHtml(t('portal.activity.descriptionPlaceholder'))}">${escapeHtml(a?.description||'')}</textarea></div><div class="field-row"><div class="field"><label for="actDuration">${escapeHtml(t('portal.activity.duration'))}</label><select id="actDuration" class="select">${[30,60,90,120].map(v=>`<option value="${v}" ${a&&Number(a.duration)===v?'selected':''}>${v===90?'1h30':v===120?'2h':v+' min'}</option>`).join('')}</select></div><div class="field"><label for="actParticipation">${escapeHtml(t('portal.activity.participation'))}</label><select id="actParticipation" class="select">${['Até 5','Até 10','Livre','Outro'].map(v=>portalStoredOption(v,participation)).join('')}</select></div></div><div class="field"><label for="actMaterials">${escapeHtml(t('portal.activity.materials'))}</label><input id="actMaterials" class="input" value="${escapeHtml(a?.materials||'')}" placeholder="${escapeHtml(t('portal.activity.materialsPlaceholder'))}"></div><div class="field"><label for="actNotes">${escapeHtml(t('portal.activity.notes'))}</label><textarea id="actNotes" class="textarea" placeholder="${escapeHtml(t('portal.activity.notesPlaceholder'))}">${escapeHtml(a?.notes||'')}</textarea></div><div class="field-row"><div class="field"><label for="actPeriod">${escapeHtml(t('portal.activity.period'))}</label><select id="actPeriod" class="select">${['Manhã','Tarde','Noite','Sem preferência'].map(v=>portalStoredOption(v,period)).join('')}</select></div><div class="field"><label for="actTime">${escapeHtml(t('portal.activity.time'))}</label><input id="actTime" class="input" type="time" value="${a?.time||'15:15'}"><small>${escapeHtml(t('common.optional'))}</small></div></div><div class="field"><label>${escapeHtml(t('portal.activity.dates'))}</label><div class="check-grid activity-date-grid">${availableDates.length?availableDates.map(d=>`<label class="check-card"><input type="checkbox" name="actDate" value="${d}" ${(a&&Array.isArray(a.dates)&&a.dates.includes(d))||(!a&&d===defaultDate)?'checked':''}><span>${dayName(d)} ${fmtDate(d,true)}</span></label>`).join(''):`<div class="empty">${escapeHtml(t('portal.activity.noStayPeriod'))}</div>`}</div></div></div>`;
  const label=approved?(a?t('action.resendReview'):t('action.sendReview')):(a?t('action.saveChanges'):t('action.addActivity'));
  const title=approved?(a?t('portal.activity.adjustTitle'):t('portal.activity.newProposal')):(a?t('portal.activity.editTitle'):t('portal.activity.newTitle'));
  const subtitle=approved?t('portal.activity.proposalSubtitle'):a?t('portal.activity.editSubtitle'):t('portal.activity.baseSubtitle');
  const footer=`<button class="btn btn-primary btn-block" type="button" onclick='saveActivity(${a?JSON.stringify(a.id):'null'})'>${escapeHtml(label)}</button>`;openModal(escapeHtml(title),escapeHtml(subtitle),body,footer);modalRoot.querySelector('.modal')?.classList.add('activity-modal');
};
window.volunteerHome=volunteerHome;window.volunteerPlan=volunteerPlan;
function renderVolunteer(){const pages={home:typeof volunteerHome==='function'?volunteerHome:null,plan:typeof volunteerPlan==='function'?volunteerPlan:null,agenda:typeof volunteerAgenda==='function'?volunteerAgenda:null,stay:typeof volunteerStay==='function'?volunteerStay:null,info:typeof volunteerInfo==='function'?volunteerInfo:null,profile:typeof volunteerProfile==='function'?volunteerProfile:null};const pageFn=pages[state.volunteerPage]||pages.home;let content='';try{if(typeof pageFn!=='function')throw new Error('Módulo do portal indisponível.');content=pageFn()}catch(error){console.error('Erro ao renderizar portal:',error);content=`<section class="section"><div class="notice danger"><i class="fa-solid fa-triangle-exclamation"></i><div><strong>${escapeHtml(t('common.errorOpenTitle'))}</strong><br>${escapeHtml(t('common.errorOpenBody'))}</div></div><button class="btn btn-primary btn-block" style="margin-top:12px" onclick="navigateVolunteer('home')">${escapeHtml(t('common.backHome'))}</button></section>`}app.innerHTML=header('',true)+`<main class="page">${content}</main>`;navRoot.innerHTML=volunteerNav();if(typeof applyI18n==='function'){applyI18n(app);applyI18n(navRoot)}}
function render(){renderVolunteer()}
function planStatusFromApplication(status){return status==='adjustments'?'adjustments':status==='analysis'?'submitted':status==='approved'?'approved':status==='rejected'?'rejected':'draft'}
function portalPlanActivities(application,sessions){
  const byActivity=new Map();
  (sessions||[]).forEach(session=>{const id=String(session.activityId||'');if(!id)return;let activity=byActivity.get(id);if(!activity){activity={id,applicationId:String(application?.id||''),name:session.activityName||'Atividade',description:session.activityDescription||'',duration:Number(session.duration)||60,participation:session.participation||'Livre',materials:session.materials||'',notes:session.notes||'',period:session.period||'Sem preferência',time:session.time||'',ownerName:session.ownerName||'',createdByUid:session.createdByUid||'',managerCreated:session.managerCreated===true,postApprovalProposal:session.postApprovalProposal===true,reviewStatus:session.reviewStatus||'',reviewNote:session.reviewNote||'',dates:[]};byActivity.set(id,activity)}if(session.date&&!activity.dates.includes(session.date))activity.dates.push(session.date);if(!activity.time&&session.time)activity.time=session.time;if(session.managerCreated===true)activity.managerCreated=true;if(session.postApprovalProposal===true){activity.postApprovalProposal=true;activity.reviewStatus=session.reviewStatus||activity.reviewStatus;activity.reviewNote=session.reviewNote||activity.reviewNote}});
  byActivity.forEach(activity=>activity.dates.sort());return [...byActivity.values()];
}
function applyVolunteerPlanningRows(application,sessions){
  state.sessions=sessions||[];state.activities=portalPlanActivities(application,state.sessions);state.sessionStatus={};state.sessionGroups={};
  state.sessions.forEach(session=>{if(session.activityId&&session.date){state.sessionStatus[`${session.activityId}-${session.date}`]=session.status||'proposed';state.sessionGroups[`${session.activityId}-${session.date}`]=session.groupId||'A definir'}});state.volunteerPlanningLoadedFor=String(application.id);state.volunteerPlanningFailedFor=null;
}
async function resetEmptyAdjustmentState(application){
  if(!application?.id||application.status!=='adjustments'||!window.OleiroServices?.applications?.update)return;
  try{await window.OleiroServices.applications.update(application.id,{status:'pending',planningSubmittedAt:null,dayAdjustments:{}});application.status='pending';application.planningSubmittedAt=null;application.dayAdjustments={};state.volunteerPlanStatus='draft'}catch(error){console.warn('Não foi possível normalizar o planejamento vazio:',error)}
}
async function hydrateVolunteerPlanning(application,{force=false}={}){
  if(!application?.id||!window.OleiroServices?.planning)return;const applicationId=String(application.id);if(!force&&state.volunteerPlanningLoadedFor===applicationId)return;
  const candidate=state.volunteerMode!=='approved',declaredEmpty=candidate&&Number(application.sessionCount||0)===0&&Number(application.activityCount||0)===0;
  try{
    if(!force&&declaredEmpty&&window.OleiroServices.planning.hasSessions){
      applyVolunteerPlanningRows(application,[]);
      const hasAny=await window.OleiroServices.planning.hasSessions({applicationId});
      if(!hasAny){await resetEmptyAdjustmentState(application);return []}
    }
    const sessions=await window.OleiroServices.planning.listSessions({applicationId});applyVolunteerPlanningRows(application,sessions||[]);
    if(candidate&&state.sessions.length===0)await resetEmptyAdjustmentState(application);return state.sessions;
  }catch(error){state.volunteerPlanningFailedFor=applicationId;throw error}
}
async function bootVolunteer(){
  const session=await window.OleiroAuthGuard?.requireRole('volunteer');if(!session)return;state.role='volunteer';state.currentSession=session;state.currentApplication=session.application||null;state.volunteerMode=session.mode||'candidate';state.volunteerPlanStatus=planStatusFromApplication(session.application?.status);state.volunteerPage='home';state.activities=[];state.sessions=[];state.volunteerPlanningLoadedFor=null;state.volunteerPlanningFailedFor=null;render();hydrateVolunteerPlanning(session.application).then(()=>render()).catch(error=>console.error('Falha ao carregar planejamento:',error));
}
bootVolunteer();