function volunteerHome(){
  const application=state.currentApplication||{};const approved=state.volunteerMode==='approved';const planStatus=state.volunteerPlanStatus||'draft';const showPlanStatus=!approved&&planStatus!=='draft';
  const from=typeof portalIsoDate==='function'?portalIsoDate(application.stayStart):null;const to=typeof portalIsoDate==='function'?portalIsoDate(application.stayEnd):null;const unit=application.unitName||((application.unitId||'').replace(/^./,c=>c.toUpperCase()))||t('portal.support.unit');const period=from&&to?`${fmtDate(from)}–${fmtDate(to)}`:t('portal.home.periodConfirm');
  const planMeta={submitted:[t('portal.home.planSubmitted'),'success',t('portal.home.submittedBody')],adjustments:[t('portal.home.adjustments'),'warning',t('portal.home.adjustmentsBody')],approved:[t('portal.home.planApproved'),'success',t('portal.home.approvedBody')]}[planStatus]||[t('portal.home.planPending'),'warning',t('portal.home.pendingBody')];
  const heroAction=approved?`<button class="btn btn-light" onclick="navigateVolunteer('agenda')"><i class="fa-regular fa-calendar-check"></i>${escapeHtml(t('portal.home.myAgenda'))}</button>`:`<button class="btn btn-light" onclick="navigateVolunteer('plan')"><i class="fa-solid ${planStatus==='adjustments'?'fa-pen-to-square':planStatus==='submitted'?'fa-eye':'fa-calendar-plus'}"></i>${escapeHtml(planStatus==='adjustments'?t('portal.home.adjustPlan'):planStatus==='submitted'?t('portal.home.viewPlan'):t('portal.home.buildPlan'))}</button>`;
  const nextDay=approved?getNextVolunteerDay():null;
  return `<section class="hero"><div class="eyebrow" style="color:#d9eadf">${escapeHtml(approved?t('portal.home.stayConfirmed'):t('portal.home.proposedPeriod'))}</div><h1>${escapeHtml(approved?t('portal.home.welcome'):t('portal.home.prepare'))}</h1><p class="muted">${escapeHtml(unit)} • ${period}</p><div class="hero-actions">${heroAction}</div></section>
  ${approved?`<section class="section"><div class="section-head"><div><h2>${escapeHtml(nextDay?.date===portalToday()?t('portal.home.todayActivities'):t('portal.home.nextActivities'))}</h2><p>${nextDay?`${dayName(nextDay.date)} • ${fmtDate(nextDay.date)}`:escapeHtml(t('portal.home.whatsNext'))}</p></div><button class="btn btn-soft" onclick="navigateVolunteer('agenda')">${escapeHtml(t('portal.nav.agenda'))}</button></div>${nextDay?`<div class="list">${nextDay.sessions.map(volunteerHomeActivityCard).join('')}</div>`:`<div class="empty"><i class="fa-regular fa-calendar-check"></i>${escapeHtml(t('portal.home.noUpcoming'))}</div>`}</section>`:''}
  ${showPlanStatus?`<section class="section"><div class="section-head"><div><h2>${escapeHtml(t('portal.home.yourPlan'))}</h2><p>${escapeHtml(t('portal.home.planStatus'))}</p></div><button class="btn btn-soft" onclick="navigateVolunteer('plan')">${escapeHtml(t('action.view'))}</button></div><div class="card"><div class="status-line"><span class="dot ${planMeta[1]==='success'?'success':'warning'}"></span><strong style="font-size:.76rem">${escapeHtml(planMeta[0])}</strong></div><p style="font-size:.66rem;color:var(--muted);margin-top:7px">${escapeHtml(planMeta[2])}</p><div class="stat-row"><span class="stat-pill">${escapeHtml(t('portal.home.activitiesCount',{count:volunteerActivities().length}))}</span><span class="stat-pill">${escapeHtml(t('portal.home.sessionsCount',{count:volunteerActivities().reduce((s,a)=>s+(a.dates||[]).length,0)}))}</span></div></div></section>`:''}
  <section class="section"><div class="section-head"><div><h2>${escapeHtml(t('portal.home.myStay'))}</h2><p>${escapeHtml(t('portal.home.mainInfo'))}</p></div></div><div class="grid-2"><div class="card"><span class="eyebrow">${escapeHtml(t('portal.home.arrival'))}</span><strong style="display:block;margin-top:8px;font-size:.85rem">${from?fmtDate(from,true):'—'}</strong><span style="font-size:.62rem;color:var(--muted)">${escapeHtml(unit)}</span></div><div class="card"><span class="eyebrow">${escapeHtml(t('portal.home.departure'))}</span><strong style="display:block;margin-top:8px;font-size:.85rem">${to?fmtDate(to,true):'—'}</strong><span style="font-size:.62rem;color:var(--muted)">${escapeHtml(t('portal.home.noActivityDay'))}</span></div></div></section>
  <section class="section"><div class="section-head"><div><h2>${escapeHtml(t('portal.home.importantInfo'))}</h2><p>${escapeHtml(t('portal.home.arrivalHelp'))}</p></div></div><div class="list"><button class="menu-link" onclick="navigateVolunteer('info')"><i class="fa-solid fa-route"></i><span>${escapeHtml(t('portal.home.howGet'))}<small>${escapeHtml(t('portal.home.transportAddress'))}</small></span><i class="fa-solid fa-chevron-right"></i></button><button class="menu-link" onclick="navigateVolunteer('info')"><i class="fa-solid fa-house"></i><span>${escapeHtml(t('portal.home.accommodationMeals'))}<small>${escapeHtml(t('portal.home.included'))}</small></span><i class="fa-solid fa-chevron-right"></i></button></div></section>`;
}
function portalToday(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function getNextVolunteerDay(){
  const today=portalToday();const sessions=getAllVolunteerSessions().filter(s=>s.status==='confirmed'&&s.date>=today).sort((a,b)=>(a.date+String(a.activity.time||'')).localeCompare(b.date+String(b.activity.time||'')));if(!sessions.length)return null;const date=sessions[0].date;return {date,sessions:sessions.filter(s=>s.date===date)};
}
function getAllVolunteerSessions(){
  const rows=(state.sessions||[]).map(session=>{const activity=(state.activities||[]).find(a=>String(a.id)===String(session.activityId))||{id:session.activityId,name:session.activityName||'Atividade',time:session.time||'',duration:session.duration||60};return {sessionId:session.id,activity:{...activity,time:session.time||activity.time||''},date:session.date,status:session.status||'proposed',group:session.groupId||'A definir'};});
  if(rows.length)return rows;const fallback=[];volunteerActivities().forEach(a=>(a.dates||[]).forEach(date=>fallback.push({activity:a,date,status:state.sessionStatus?.[`${a.id}-${date}`]||'proposed',group:state.sessionGroups?.[`${a.id}-${date}`]||'A definir'})));return fallback;
}
function volunteerHomeActivityCard(s){return `<button class="list-item clickable volunteer-home-activity" onclick="navigateVolunteer('agenda')"><div class="time-box single"><strong>${escapeHtml(s.activity.time||'—')}</strong></div><div class="item-main"><h3 data-no-i18n>${escapeHtml(s.activity.name||'Atividade')}</h3><p>${Number(s.activity.duration)||0} min${s.group&&s.group!=='A definir'?` • ${escapeHtml(t('portal.session.group',{group:s.group}))}`:''}</p></div><i class="fa-solid fa-chevron-right" style="color:var(--muted);align-self:center"></i></button>`;}
function volunteerActivities(){return state.activities||[]}
function volunteerStayDates(){return []}
