function volunteerHome(){
  const application=state.currentApplication||{},approved=state.volunteerMode==='approved',status=state.volunteerPlanStatus||'draft';const from=typeof portalIsoDate==='function'?portalIsoDate(application.stayStart):null,to=typeof portalIsoDate==='function'?portalIsoDate(application.stayEnd):null,unit=application.unitName||((application.unitId||'').replace(/^./,c=>c.toUpperCase()))||t('portal.support.unit');const progress=approved?100:{draft:24,submitted:56,adjustments:68,approved:100}[status]||24;const nextDay=approved?getNextVolunteerDay():null;const sideTitle=approved?'Estadia confirmada':status==='submitted'?'Planejamento enviado':status==='adjustments'?'Ajustes solicitados':'Planejamento a preparar';const sideBody=approved?'Sua agenda e as informações da estadia já estão disponíveis.':status==='submitted'?'A equipe já pode analisar. Você ainda pode editar enquanto aguarda a aprovação.':status==='adjustments'?'Existem orientações da equipe para revisar antes do reenvio.':'Organize as atividades que você pretende oferecer durante a estadia.';const primary=approved?`<button class="btn btn-primary" onclick="navigateVolunteer('agenda')"><i class="fa-regular fa-calendar-check"></i>Ver minha agenda</button>`:`<button class="btn btn-primary" onclick="navigateVolunteer('plan')"><i class="fa-solid ${status==='adjustments'?'fa-pen-to-square':status==='submitted'?'fa-eye':'fa-calendar-plus'}"></i>${status==='adjustments'?'Fazer ajustes':status==='submitted'?'Ver planejamento':'Montar planejamento'}</button>`;
  return `<div class="r61-page r61-portal-home"><section class="r61-portal-hero"><div><span class="r61-kicker">${approved?'Bem-vindo à Casa':'Sua jornada de voluntariado'}</span><h1>${approved?'Tudo o que você precisa para a sua estadia.':'Prepare sua participação com clareza.'}</h1><p>${escapeHtml(unit)}${from&&to?` • ${fmtDate(from)}–${fmtDate(to)}`:''}. Consulte seu próximo passo, planejamento e informações importantes em um só lugar.</p><div class="r61-portal-actions">${primary}<button class="btn btn-outline" onclick="navigateVolunteer('info')"><i class="fa-solid fa-circle-info"></i>Informações da Casa</button></div></div><aside class="r61-journey"><div><span class="r61-kicker">${approved?'Status':'Próximo passo'}</span><strong>${escapeHtml(sideTitle)}</strong><p>${escapeHtml(sideBody)}</p></div><div><div class="r61-progress"><span style="width:${progress}%"></span></div><p>${progress}% da jornada atual</p></div></aside></section><div class="r61-portal-grid"><section class="r61-portal-panel"><h2>${approved?'Próximas atividades':'Sua estadia'}</h2><p>${approved?(nextDay?`${dayName(nextDay.date)} • ${fmtDate(nextDay.date)}`:'Agenda atualizada'):'Datas e unidade informadas no processo.'}</p>${approved?r61NextActivityRows(nextDay):`<div class="r61-stay-grid"><div class="r61-stay-card"><span>Chegada</span><strong>${from?fmtDate(from,true):'A confirmar'}</strong><small>${escapeHtml(unit)}</small></div><div class="r61-stay-card"><span>Saída</span><strong>${to?fmtDate(to,true):'A confirmar'}</strong><small>Dia sem atividade</small></div></div>`}</section><section class="r61-portal-panel"><h2>Atalhos úteis</h2><p>Informações que você pode precisar rapidamente.</p>${r61QuickLink('fa-location-dot','Estadia','Datas, unidade e orientações',"navigateVolunteer('stay')")}${r61QuickLink('fa-route','Como chegar e rotina','Transporte, endereço e informações práticas',"navigateVolunteer('info')")}${r61QuickLink('fa-user','Meu perfil','Dados pessoais e contato',"navigateVolunteer('profile')")}</section></div></div>`;
}
function r61QuickLink(icon,title,desc,action){return `<button class="r61-quick-link" onclick="${action}"><span><i class="fa-solid ${icon}"></i></span><span><strong>${escapeHtml(title)}</strong><small>${escapeHtml(desc)}</small></span><i class="fa-solid fa-chevron-right"></i></button>`}
function r61NextActivityRows(nextDay){if(!nextDay)return `<div class="empty">Nenhuma atividade futura confirmada.</div>`;return nextDay.sessions.slice(0,4).map(s=>`<button class="r61-quick-link" onclick="navigateVolunteer('agenda')"><span><i class="fa-regular fa-calendar-check"></i></span><span><strong>${escapeHtml(s.activity.name||'Atividade')}</strong><small>${Number(s.activity.duration)||0} min • ${escapeHtml(activityPeriodValue(s,s.activity))}</small></span><i class="fa-solid fa-chevron-right"></i></button>`).join('')}
function portalToday(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function getNextVolunteerDay(){const today=portalToday();const sessions=getAllVolunteerSessions().filter(s=>s.status==='confirmed'&&s.date>=today).sort(activityScheduleCompare);if(!sessions.length)return null;const date=sessions[0].date;return {date,sessions:sessions.filter(s=>s.date===date).sort(activityScheduleCompare)}}
function getAllVolunteerSessions(){const rows=(state.sessions||[]).map(session=>{const activity=(state.activities||[]).find(a=>String(a.id)===String(session.activityId))||{id:session.activityId,name:session.activityName||'Atividade',duration:session.duration||60};return {sessionId:session.id,activity:{...activity,period:activityPeriodValue(session,activity)},date:session.date,status:session.status||'proposed',group:session.groupId||'A definir'}});if(rows.length)return rows;const fallback=[];volunteerActivities().forEach(a=>(a.dates||[]).forEach(date=>fallback.push({activity:a,date,status:state.sessionStatus?.[`${a.id}-${date}`]||'proposed',group:state.sessionGroups?.[`${a.id}-${date}`]||'A definir'})));return fallback}
function volunteerHomeActivityCard(s){return `<button class="list-item clickable volunteer-home-activity" onclick="navigateVolunteer('agenda')"><div class="item-main"><h3 data-no-i18n>${escapeHtml(s.activity.name||'Atividade')}</h3><p>${Number(s.activity.duration)||0} min • ${escapeHtml(tValue(activityPeriodValue(s,s.activity)))}${s.group&&s.group!=='A definir'?` • ${escapeHtml(t('portal.session.group',{group:s.group}))}`:''}</p></div><i class="fa-solid fa-chevron-right" style="color:var(--muted);align-self:center"></i></button>`}
function volunteerActivities(){return state.activities||[]}
function volunteerStayDates(){return []}
