function volunteerInfo(){return `<section class="section"><div class="section-head"><div><span class="eyebrow">Portal</span><h2>Informações da Casa</h2><p>Consulte antes e durante sua experiência</p></div></div>${infoAccordion()}</section>`}

function volunteerMenu(){return `<section class="section"><div class="section-head"><div><span class="eyebrow">Portal</span><h2>Menu</h2><p>Conta e informações</p></div></div><div class="menu-list">${menuLink('fa-circle-info','Informações da Casa','Orientações da experiência',"state.volunteerPage='info';render()")}${menuLink('fa-user','Perfil do voluntário','Dados pessoais e do acesso',"openVolunteerProfile()")}${menuLink('fa-arrows-rotate','Trocar modo do protótipo','Alternar em processo / aprovado',"state.volunteerMode=state.volunteerMode==='candidate'?'approved':'candidate';localStorage.setItem('oleiro-volunteer-mode',state.volunteerMode);render()")}${menuLink('fa-right-from-bracket','Sair','Encerrar sessão','logout()')}</div></section>`}

function openVolunteerProfile(){
  const p=state.candidates.find(x=>x.name==='Thomas Miller')||{};
  const status=state.volunteerMode==='approved'?'Aprovado':state.volunteerPlanStatus==='submitted'?'Planejamento em análise':state.volunteerPlanStatus==='adjustments'?'Ajustes solicitados':'Em preparação';
  openModal('Perfil do voluntário','Seus dados de acesso e da experiência',`<div class="profile-card"><div class="profile-avatar">TM</div><div><strong>${p.name||'Thomas Miller'}</strong><p>${p.country||'Alemanha'} • ${p.unit||'Rodeio'}</p></div></div><div class="card profile-details"><div><span>E-mail</span><strong>${p.email||'thomas@email.com'}</strong></div><div><span>WhatsApp</span><strong>${p.phone||'+49 151 000000'}</strong></div><div><span>Período</span><strong>${fmtDate(p.from||'2026-09-03',true)}–${fmtDate(p.to||'2026-09-18',true)}</strong></div><div><span>Status</span><strong>${status}</strong></div></div>`);modalRoot.querySelector('.modal')?.classList.add('profile-modal')
}
