function volunteerPlan(){
  const acts=volunteerActivities();
  return `<section class="section"><div class="section-head"><div><span class="eyebrow">03–18 SET</span><h2>Meu planejamento</h2><p>Datas e horários são sugestões até a confirmação da Casa</p></div><button class="btn btn-primary" onclick="openActivityModal()"><i class="fa-solid fa-plus"></i>Atividade</button></div>
  <div class="segment"><button class="${state.planView==='agenda'?'active':''}" onclick="state.planView='agenda';render()">Agenda</button><button class="${state.planView==='activities'?'active':''}" onclick="state.planView='activities';render()">Atividades</button></div>
  <div class="notice"><i class="fa-solid fa-circle-info"></i><div>Você pode editar o planejamento. Depois que uma sessão for confirmada, alterações feitas por você voltam para análise da Casa.</div></div>
  <div style="margin-top:14px">${state.planView==='agenda'?volunteerAgendaContent(true):activityList()}</div>
  <div class="card" style="margin-top:14px"><span class="eyebrow">Resumo</span><div class="stat-row"><span class="stat-pill">${acts.length} atividades</span><span class="stat-pill">${acts.reduce((s,a)=>s+a.dates.length,0)} sessões</span><span class="stat-pill">${(acts.reduce((s,a)=>s+a.duration*a.dates.length,0)/60).toFixed(1).replace('.',',')}h planejadas</span></div><button class="btn btn-primary btn-block" style="margin-top:12px" onclick="submitPlan()">Enviar planejamento</button></div></section>`;
}

function volunteerAgendaContent(editable=false){
  const dates=volunteerStayDates();
  return `<div class="calendar-strip">${dates.map(d=>`<button class="date-chip" onclick="document.getElementById('vday-${d}').scrollIntoView({behavior:'smooth',block:'start'})"><span>${dayName(d)}</span><strong>${new Date(d+'T12:00:00').getDate()}</strong><span>SET</span></button>`).join('')}</div><div style="margin-top:14px">${dates.map(d=>{const ss=getSessions(d,true);return `<div class="day-block" id="vday-${d}"><div class="day-title"><h3>${dayName(d)}, ${fmtDate(d)}</h3><span>${ss.length?((ss.reduce((x,s)=>x+s.activity.duration,0)/60)+'h'):''}</span></div>${ss.map(s=>sessionCardVolunteer(s,editable)).join('')||'<div class="empty">Nenhuma atividade planejada.</div>'}${editable?`<button class="btn btn-soft btn-block" style="margin-top:6px" onclick="openActivityModal('${d}')"><i class="fa-solid fa-plus"></i>Adicionar atividade</button>`:''}</div>`}).join('')}</div>`;
}

function sessionCardVolunteer(s,editable){const [l,t]=statusMeta(s.status);return `<div class="activity-card"><div class="activity-row"><div><h4>${s.activity.time} • ${s.activity.name}</h4><p>${s.activity.duration} min • ${s.activity.period}</p></div>${badge(l,t)}</div>${editable?`<div class="activity-actions"><button class="btn btn-outline" onclick="openActivityModal('${s.date}',${s.activity.id})">Editar</button><button class="btn btn-outline" onclick="moveSession(${s.activity.id},'${s.date}',true)">Mover</button></div>`:''}</div>`}

function activityList(){const acts=volunteerActivities();return `<div class="list">${acts.map(a=>`<div class="card"><div class="activity-row"><div><h3 style="font-size:.8rem">${a.name}</h3><p style="font-size:.65rem;color:var(--muted)">${a.description}</p></div>${badge(a.dates.length+' sessões','primary')}</div><div class="stat-row"><span class="stat-pill">${a.duration} min</span><span class="stat-pill">${a.participation}</span><span class="stat-pill">${a.period}</span></div><div style="font-size:.63rem;color:var(--muted);margin-top:10px">${a.dates.map(d=>fmtDate(d,true)).join(' • ')}</div><div class="activity-actions"><button class="btn btn-outline" onclick="openActivityModal(null,${a.id})">Editar atividade</button><button class="btn btn-soft" onclick="openReuseActivity(${a.id})">+ Sessão</button></div></div>`).join('')}</div>`}

function openActivityModal(date=null,id=null){const a=id?state.activities.find(x=>x.id===id):null;const defaultDate=date||'2026-09-08';const availableDates=volunteerStayDates();openModal(a?'Editar atividade':'Nova atividade',a?'A descrição é compartilhada entre todas as sessões.':'Cadastre uma vez e selecione quantas datas precisar.',`<div class="form-grid"><div class="field"><label>Nome da atividade</label><input id="actName" class="input" value="${a?a.name:''}" placeholder="Ex.: Conversação em inglês"></div><div class="field"><label>Descrição</label><textarea id="actDesc" class="textarea" placeholder="Como a atividade funciona?">${a?a.description:''}</textarea></div><div class="field-row"><div class="field"><label>Duração</label><select id="actDuration" class="select">${[30,60,90,120].map(v=>`<option value="${v}" ${a&&a.duration===v?'selected':''}>${v===90?'1h30':v===120?'2h':v+' min'}</option>`).join('')}</select></div><div class="field"><label>Participação</label><select id="actParticipation" class="select">${['Até 5','Até 10','Livre','Outro'].map(v=>`<option ${a&&a.participation===v?'selected':''}>${v}</option>`).join('')}</select></div></div><div class="field"><label>Materiais necessários</label><input id="actMaterials" class="input" value="${a?a.materials:''}" placeholder="Nenhum, quadro, bola..."></div><div class="field"><label>Observações</label><textarea id="actNotes" class="textarea" placeholder="Opcional">${a?a.notes:''}</textarea></div><div class="field-row"><div class="field"><label>Período preferido</label><select id="actPeriod" class="select">${['Manhã','Tarde','Noite','Sem preferência'].map(v=>`<option ${a&&a.period===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Horário sugerido</label><input id="actTime" class="input" type="time" value="${a?a.time:'15:15'}"><small>Opcional na versão final.</small></div></div><div class="field"><label>Datas em que deseja realizar</label><div class="check-grid">${availableDates.map(d=>`<label class="check-card"><input type="checkbox" name="actDate" value="${d}" ${(a&&a.dates.includes(d))||(!a&&d===defaultDate)?'checked':''}>${dayName(d)} ${fmtDate(d,true)}</label>`).join('')}</div></div><button class="btn btn-primary btn-block" onclick="saveActivity(${a?a.id:'null'})">${a?'Salvar alterações':'Adicionar atividade'}</button></div>`)}

function saveActivity(id){const dates=[...document.querySelectorAll('input[name="actDate"]:checked')].map(x=>x.value);const data={name:document.getElementById('actName').value.trim(),description:document.getElementById('actDesc').value.trim(),duration:+document.getElementById('actDuration').value,participation:document.getElementById('actParticipation').value,materials:document.getElementById('actMaterials').value.trim()||'Nenhum',notes:document.getElementById('actNotes').value.trim(),period:document.getElementById('actPeriod').value,time:document.getElementById('actTime').value||'15:15',dates};if(!data.name)return showToast('Informe o nome da atividade.');if(id){Object.assign(state.activities.find(x=>x.id===id),data)}else{state.activities.push({id:Date.now(),owner:'Thomas Miller',...data})}closeModal();render();showToast(id?'Atividade atualizada.':'Atividade adicionada ao planejamento.')}

function openReuseActivity(id){const a=state.activities.find(x=>x.id===id);openModal('Adicionar sessão',a.name,`<div class="field"><label>Selecione uma nova data</label><select id="reuseDate" class="select">${volunteerStayDates().filter(d=>!a.dates.includes(d)).map(d=>`<option value="${d}">${dayName(d)} • ${fmtDate(d)}</option>`).join('')}</select></div><button class="btn btn-primary btn-block" style="margin-top:12px" onclick="addReuseDate(${id})">Adicionar sessão</button>`)}

function addReuseDate(id){const a=state.activities.find(x=>x.id===id);const d=document.getElementById('reuseDate').value;a.dates.push(d);state.sessionStatus[`${id}-${d}`]='proposed';closeModal();render();showToast('Nova sessão adicionada.')}

function submitPlan(){showToast('Planejamento enviado para análise.');if(state.volunteerMode==='candidate')state.notifications.unshift({id:Date.now(),title:'Planejamento enviado',text:'A equipe da Casa recebeu seu planejamento.',unread:true})}

function openQuickSession(date='2026-09-08'){openActivityModal(date)}
