function volunteerPlan(){
  const acts=volunteerActivities();const status=state.volunteerPlanStatus||'draft';const approved=state.volunteerMode==='approved';const editable=!approved&&(status==='draft'||status==='adjustments');const dates=volunteerStayDates();const periodLabel=dates.length?`${fmtDate(dates[0],true)}–${fmtDate(dates[dates.length-1],true)}`:'Período a confirmar';
  const notice=approved?'Seu planejamento aprovado está disponível para consulta. Mudanças precisam de nova confirmação da Casa.':status==='submitted'?'Planejamento enviado. Enquanto a equipe estiver analisando, a edição fica bloqueada.':status==='adjustments'?'Revise os dias marcados como “Reajustar” e reenvie o planejamento.':'Monte o planejamento pelos dias da sua estadia. Você pode editar, mover ou excluir até enviar.';
  const submitButton=approved?`<button class="btn btn-soft btn-block" style="margin-top:12px" disabled><i class="fa-solid fa-circle-check"></i>Planejamento aprovado</button>`:status==='submitted'?`<button class="btn btn-soft btn-block" style="margin-top:12px" disabled><i class="fa-solid fa-paper-plane"></i>Enviado</button>`:`<button class="btn btn-primary btn-block" style="margin-top:12px" onclick="submitPlan()"><i class="fa-solid fa-paper-plane"></i>${status==='adjustments'?'Reenviar planejamento':'Enviar planejamento'}</button>`;
  return `<section class="section volunteer-plan-page"><div class="plan-title-row"><div><h2>Meu planejamento</h2><p>Datas e horários são sugestões até a confirmação da Casa</p></div><strong>${periodLabel}</strong></div><div class="notice ${status==='adjustments'?'warning':''}"><i class="fa-solid fa-circle-info"></i><div>${notice}</div></div><div style="margin-top:14px">${volunteerAgendaContent(editable)}</div><div class="card plan-summary" style="margin-top:14px"><span class="eyebrow">Resumo</span><div class="stat-row"><span class="stat-pill">${acts.length} atividades</span><span class="stat-pill">${(state.sessions||[]).length} sessões</span><span class="stat-pill">${((state.sessions||[]).reduce((s,row)=>s+(Number(row.duration)||60),0)/60).toFixed(1).replace('.',',')}h planejadas</span></div>${submitButton}</div></section>`;
}
function calendarMonthLabel(date){const locale=typeof currentLocale==='function'?currentLocale():'pt-BR';return new Intl.DateTimeFormat(locale,{month:'short'}).format(new Date(date+'T12:00:00')).replace('.','').toUpperCase()}
function volunteerDayAdjustment(date){const rows=state.currentApplication?.dayAdjustments;return rows&&typeof rows==='object'?rows[date]||null:null}
function openVolunteerDayAdjustment(date){const item=volunteerDayAdjustment(date);if(!item)return;openModal(`Ajuste em ${fmtDate(date,true)}`,'Orientação da equipe da Casa.',`<div class="notice warning"><i class="fa-solid fa-circle-info"></i><div>${escapeHtml(item.note||'Revise o planejamento deste dia.')}</div></div>`)}
function scrollToVolunteerDay(date){const target=document.getElementById(`vday-${date}`);if(!target)return;const header=document.querySelector('.app-header');const offset=(header?.getBoundingClientRect().height||70)+14;const top=window.scrollY+target.getBoundingClientRect().top-offset;window.scrollTo({top:Math.max(0,top),behavior:'smooth'})}
function volunteerAgendaContent(editable=false){
  const dates=volunteerStayDates();if(!dates.length)return '<div class="empty"><i class="fa-regular fa-calendar-xmark"></i>O período da estadia ainda não foi definido.</div>';
  return `<div class="calendar-strip">${dates.map(d=>`<button class="date-chip" onclick="scrollToVolunteerDay('${d}')"><span>${dayName(d)}</span><strong>${new Date(d+'T12:00:00').getDate()}</strong><span>${calendarMonthLabel(d)}</span></button>`).join('')}</div><div class="volunteer-plan-days">${dates.map(d=>{const ss=getSessions(d,true),adjustment=volunteerDayAdjustment(d);return `<div class="day-block" id="vday-${d}"><div class="day-title volunteer-day-title"><div><h3>${dayName(d)}, ${fmtDate(d)}</h3>${adjustment?'<span class="badge warning">Reajustar</span>':''}</div><div class="day-title-actions">${adjustment?`<button class="day-info-button" type="button" onclick="openVolunteerDayAdjustment('${d}')" aria-label="Ver orientação"><i class="fa-solid fa-circle-info"></i></button>`:''}<span>${ss.length?`${(ss.reduce((x,s)=>x+(Number(s.activity.duration)||0),0)/60).toFixed(1).replace('.0','')}h`:''}</span></div></div>${ss.map(s=>sessionCardVolunteer(s,editable)).join('')||'<div class="empty">Nenhuma atividade planejada.</div>'}${editable&&state.volunteerMode!=='approved'?`<button class="btn btn-soft btn-block" style="margin-top:6px" onclick="openActivityModal('${d}')"><i class="fa-solid fa-plus"></i>Adicionar atividade</button>`:''}</div>`}).join('')}</div>`;
}
function sessionCardVolunteer(s,editable){
  const [l,t]=statusMeta(s.status);const candidateEdit=editable&&state.volunteerMode!=='approved';const approvedMove=editable&&state.volunteerMode==='approved';
  const actions=candidateEdit?`<div class="activity-actions candidate-session-actions"><button class="btn btn-outline" onclick='openActivityModal(${JSON.stringify(s.date)},${JSON.stringify(s.activity.id)})'>Editar</button><button class="btn btn-outline" onclick='moveSession(${JSON.stringify(s.activity.id)},${JSON.stringify(s.date)},true)'>Mover</button><button class="btn btn-danger-soft" onclick='requestDeletePlanningSession(${JSON.stringify(s.activity.id)},${JSON.stringify(s.date)})'>Excluir</button></div>`:approvedMove?`<div class="activity-actions"><button class="btn btn-outline" onclick='moveSession(${JSON.stringify(s.activity.id)},${JSON.stringify(s.date)},true)'>Solicitar mudança</button></div>`:'';
  const statusBadge=s.status==='proposed'&&state.volunteerMode!=='approved'?'':badge(l,t);
  return `<div class="activity-card"><div class="activity-row"><div><h4>${escapeHtml(s.activity.time||'—')} • ${escapeHtml(s.activity.name||'Atividade')}</h4><p>${Number(s.activity.duration)||0} min • ${escapeHtml(s.activity.period||'Sem preferência')}</p></div>${statusBadge}</div>${actions}</div>`;
}
function syncVolunteerApplicationCounts(){if(!state.currentApplication)return;state.currentApplication.sessionCount=(state.sessions||[]).length;state.currentApplication.activityCount=(state.activities||[]).length}
function applySavedActivityResult(result,dates){
  if(!result)return;const activityId=String(result.activityId);state.sessions=(state.sessions||[]).filter(s=>String(s.activityId)!==activityId).concat(result.sessions||[]).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.time||'').localeCompare(String(b.time||'')));
  const activity={...(result.activity||{}),id:activityId,dates:[...dates]};const index=(state.activities||[]).findIndex(a=>String(a.id)===activityId);if(index>=0)state.activities[index]=activity;else state.activities.push(activity);syncVolunteerApplicationCounts();
}
function planningOwnerName(application,session){
  const names=Array.isArray(application?.participantNames)?application.participantNames.filter(Boolean):[];
  if((application?.type==='couple'||Number(application?.participantCount)===2)&&names.length)return names.join(' + ');
  return typeof volunteerProfileName==='function'?volunteerProfileName():(session?.profile?.name||session?.email||'Voluntário');
}
async function saveActivity(id){
  if(state.volunteerMode==='approved')return showToast('Após a aprovação, mudanças devem ser solicitadas pela agenda.');if(!['draft','adjustments'].includes(state.volunteerPlanStatus||'draft'))return showToast('O planejamento está bloqueado para edição.');
  const dates=[...document.querySelectorAll('input[name="actDate"]:checked')].map(x=>x.value);const data={name:document.getElementById('actName')?.value.trim()||'',description:document.getElementById('actDesc')?.value.trim()||'',duration:+document.getElementById('actDuration')?.value||60,participation:document.getElementById('actParticipation')?.value||'Livre',materials:document.getElementById('actMaterials')?.value.trim()||'Nenhum',notes:document.getElementById('actNotes')?.value.trim()||'',period:document.getElementById('actPeriod')?.value||'Sem preferência',time:document.getElementById('actTime')?.value||'15:15'};
  if(!data.name)return showToast('Informe o nome da atividade.');if(!dates.length)return showToast('Selecione pelo menos uma data.');const application=state.currentApplication,session=state.currentSession;if(!application?.id||!session?.uid)return showToast('Sessão de voluntariado inválida.');const ownerName=planningOwnerName(application,session);
  try{const result=await window.OleiroServices.planning.saveActivity({activityId:id,applicationId:application.id,unitId:application.unitId,createdByUid:session.uid,ownerName,data,dates,existingSessions:state.sessions||[]});applySavedActivityResult(result,dates);closeModal();render();showToast(id?'Atividade atualizada.':'Atividade adicionada ao planejamento.')}catch(error){console.error(error);showToast(error?.message||'Não foi possível salvar a atividade.')}
}
function requestDeletePlanningSession(activityId,date){const session=realSessionFor(activityId,date);const activity=(state.activities||[]).find(a=>String(a.id)===String(activityId));if(!session)return showToast('Sessão não encontrada.');openModal('Excluir esta sessão?',`${activity?.name||'Atividade'} • ${fmtDate(date,true)}`,`<div class="notice warning"><i class="fa-solid fa-trash"></i><div>A sessão será removida do seu planejamento. Se for a única data dessa atividade, a atividade também será excluída.</div></div>`,`<div class="confirm-delete-actions"><button class="btn btn-outline" onclick="closeModal()">Cancelar</button><button class="btn btn-danger" onclick='deletePlanningSession(${JSON.stringify(activityId)},${JSON.stringify(date)})'>Excluir</button></div>`)}
async function deletePlanningSession(activityId,date){const session=realSessionFor(activityId,date),application=state.currentApplication;if(!session||!application?.id)return showToast('Sessão não encontrada.');try{const result=await window.OleiroServices.planning.deleteSession(session.id,{applicationId:application.id,activityId});state.sessions=(state.sessions||[]).filter(s=>String(s.id)!==String(session.id));if(result.deletedActivity)state.activities=(state.activities||[]).filter(a=>String(a.id)!==String(activityId));else{const activity=(state.activities||[]).find(a=>String(a.id)===String(activityId));if(activity)activity.dates=(activity.dates||[]).filter(d=>d!==date)}syncVolunteerApplicationCounts();closeModal();render();showToast('Sessão excluída.')}catch(error){console.error(error);showToast(error?.message||'Não foi possível excluir a sessão.')}}
async function submitPlan(){
  const acts=volunteerActivities();if(!acts.length||(state.sessions||[]).length===0)return showToast('Adicione pelo menos uma atividade antes de enviar.');const application=state.currentApplication;if(!application?.id)return showToast('Candidatura não encontrada.');const wasAdjustment=state.volunteerPlanStatus==='adjustments';
  try{await window.OleiroServices.applications.submitPlanning(application.id,{wasAdjustment});application.status='analysis';application.planningSubmittedAt=new Date().toISOString();if(state.currentSession)state.currentSession.application=application;state.volunteerPlanStatus='submitted';render();showToast(wasAdjustment?'Planejamento reenviado para análise.':'Planejamento enviado para análise.')}catch(error){console.error(error);showToast(error?.message||'Não foi possível enviar o planejamento.')}
}
function openQuickSession(date=null){openActivityModal(date||volunteerStayDates()[0]||null)}
