/* Estado atual do Portal: dias sem atividade, navegação enxuta e agenda coerente. */
(function productCurrentPortal(){
  const APPLICATION_REFRESH_TTL=2*60*1000;
  let applicationRefreshAt=Date.now();
  let applicationRefreshPromise=null;

  function safe(value){return encodeURIComponent(String(value??''))}
  function iso(value){if(!value)return '';if(typeof value==='string')return value.slice(0,10);if(typeof value.toDate==='function')return value.toDate().toISOString().slice(0,10);return ''}
  function blockedDayReason(date){
    const dates=volunteerStayDates(),first=dates[0],last=dates[dates.length-1];
    if(date===first)return 'Chegada — dia sem atividade';
    if(date===last)return 'Saída — dia sem atividade';
    const day=new Date(`${date}T12:00:00`).getDay();
    if(day===0||day===6)return 'Fim de semana — dia sem atividade';
    return '';
  }
  function deadlineDays(){const value=state.currentApplication?.planningDeadlineAt;if(!value)return null;let date=null;if(typeof value?.toDate==='function')date=value.toDate();else date=new Date(value);if(!date||Number.isNaN(date.getTime()))return null;return Math.max(0,Math.ceil((date.getTime()-Date.now())/86400000))}
  function profileStatus(){const application=state.currentApplication||{};if(state.volunteerMode==='approved')return 'Aprovado';if(state.volunteerPlanStatus==='submitted')return 'Em análise';if(state.volunteerPlanStatus==='adjustments')return 'Ajustes';if(application.status==='rejected')return 'Recusado';const days=deadlineDays();return days===null?'Em preparação':`Em preparação · ${days} ${days===1?'dia restante':'dias restantes'}`}

  volunteerNav=function(){
    const approved=state.volunteerMode==='approved';if(state.volunteerPage==='stay')state.volunteerPage='home';
    const items=approved?[['home','fa-house','Início'],['agenda','fa-calendar-check','Agenda'],['info','fa-circle-info','Informações'],['profile','fa-user','Perfil']]:[['home','fa-house','Início'],['plan','fa-calendar-plus','Planejamento'],['info','fa-circle-info','Informações'],['profile','fa-user','Perfil']];
    return `<nav class="bottom-nav volunteer-nav-current">${items.map(([id,ic,tx])=>`<button class="nav-btn ${state.volunteerPage===id?'active':''}" onclick="navigateVolunteer('${id}')"><i class="fa-solid ${ic}"></i><span>${tx}</span></button>`).join('')}<button class="nav-btn nav-logout" type="button" onclick="logout()"><i class="fa-solid fa-right-from-bracket"></i><span>Sair</span></button></nav>`;
  };

  /* Perfil em um único card, sem repetir bloco de identidade e sem Sair duplicado. */
  volunteerProfile=function(){
    const session=state.currentSession||{},profile=session.profile||{},application=state.currentApplication||{},name=volunteerProfileName();
    const country=profile.country||profile.nationality||(Array.isArray(application.participantCountries)?application.participantCountries[0]:null)||'—';
    const unit=application.unitName||String(application.unitId||'—').replace(/^./,c=>c.toUpperCase()),email=profile.email||session.email||'—',phone=profile.phone||profile.whatsapp||'—';
    return `<section class="section volunteer-profile-page"><div class="section-head"><div><span class="eyebrow">Conta</span><h2>Meu perfil</h2><p>Dados pessoais e da experiência</p></div></div><div class="card volunteer-profile-unified"><div class="volunteer-profile-identity"><div class="profile-avatar">${volunteerProfileInitials(name)}</div><div><strong>${escapeHtml(name)}</strong><span>${escapeHtml(country)} • ${escapeHtml(unit)}</span></div></div><div class="profile-details volunteer-profile-details"><div><span>Email</span><strong>${escapeHtml(email)}</strong></div><div><span>WhatsApp</span><strong>${escapeHtml(phone)}</strong></div><div><span>Período</span><strong>${volunteerApplicationDate(application.stayStart)}–${volunteerApplicationDate(application.stayEnd)}</strong></div><div><span>Status</span><strong>${escapeHtml(profileStatus())}</strong></div></div></div></section>`;
  };

  /* Unidade e suporte passam para a Home, logo abaixo de Minha estadia. */
  const baseVolunteerHome=volunteerHome;
  volunteerHome=function(){
    let html=baseVolunteerHome(),application=state.currentApplication||{},unit=application.unitName||String(application.unitId||'Rodeio').replace(/^./,c=>c.toUpperCase());
    const support=`<div class="card home-unit-support"><div class="home-unit-copy"><span class="home-unit-icon"><i class="fa-solid fa-location-dot"></i></span><div><small>Unidade</small><strong>${escapeHtml(unit)}</strong><span>Suporte: +55 47 99950-4753</span></div></div><a href="https://wa.me/5547999504753" target="_blank" rel="noopener noreferrer" aria-label="Abrir suporte no WhatsApp"><i class="fa-brands fa-whatsapp"></i></a></div>`;
    const unitInArrival=`<span style="font-size:.62rem;color:var(--muted)">${escapeHtml(unit)}</span>`;
    html=html.replace(unitInArrival,'<span style="font-size:.62rem;color:var(--muted)">Dia sem atividade</span>');
    const marker='<section class="section"><div class="section-head"><div><h2>Informações importantes</h2>',idx=html.indexOf(marker);if(idx>=0)html=html.slice(0,idx)+support+html.slice(idx);
    if(state.volunteerMode!=='approved'&&(state.volunteerPlanStatus||'draft')==='draft'){const days=deadlineDays();if(days!==null)html=html.replace('Período proposto',`Em preparação · ${days} ${days===1?'dia restante':'dias restantes'}`)}
    return html;
  };

  window.openVolunteerActivityInfo=function(name,description,notes,materials){const n=decodeURIComponent(name||''),d=decodeURIComponent(description||''),o=decodeURIComponent(notes||''),m=decodeURIComponent(materials||''),sections=[];if(d)sections.push(`<div class="activity-info-block"><strong>Descrição</strong><p>${escapeHtml(d)}</p></div>`);if(o)sections.push(`<div class="activity-info-block"><strong>Observações</strong><p>${escapeHtml(o)}</p></div>`);if(m&&m!=='Nenhum')sections.push(`<div class="activity-info-block"><strong>Materiais</strong><p>${escapeHtml(m)}</p></div>`);openModal(n||'Informações da atividade','',`<div class="activity-info-compact">${sections.join('')||'<div class="empty">Sem informações adicionais.</div>'}</div>`);modalRoot.querySelector('.modal')?.classList.add('activity-info-modal-compact')};

  sessionCardVolunteer=function(s,editable){const a=s.activity||{},raw=s.raw||{},description=raw.activityDescription||a.description||'',notes=raw.notes||a.notes||'',materials=raw.materials||a.materials||'',hasInfo=!!(description||notes||(materials&&materials!=='Nenhum')),candidateEdit=editable&&state.volunteerMode!=='approved',approved=state.volunteerMode==='approved',change=s.status==='change_requested',group=s.group&&s.group!=='A definir'?`Grupo ${escapeHtml(s.group)}`:'Grupo a definir',statusBadge=change?badge('Mudança solicitada','warning'):(s.status==='proposed'&&!approved?'':s.status==='confirmed'?'':badge(statusMeta(s.status)[0],statusMeta(s.status)[1])),sessionId=s.sessionId||raw.id||'';const actions=candidateEdit?`<div class="activity-actions candidate-session-actions"><button class="btn btn-outline" onclick='openActivityModal(${JSON.stringify(s.date)},${JSON.stringify(a.id)})'>Editar</button><button class="btn btn-outline" onclick="moveSessionById('${safe(sessionId)}',true)">Mover</button><button class="btn btn-danger-soft" onclick='requestDeletePlanningSession(${JSON.stringify(a.id)},${JSON.stringify(s.date)})'>Excluir</button></div>`:approved?(change?`<div class="activity-actions"><button class="btn btn-soft" type="button" disabled><i class="fa-solid fa-clock"></i>Mudança solicitada</button></div>`:`<div class="activity-actions"><button class="btn btn-outline" type="button" onclick="moveSessionById('${safe(sessionId)}',true)">Solicitar mudança</button></div>`):'';return `<div class="activity-card volunteer-session-card"><div class="activity-row"><div class="volunteer-session-main"><div class="volunteer-session-title"><h4>${escapeHtml(a.time||raw.time||'—')} • ${escapeHtml(a.name||raw.activityName||'Atividade')}</h4>${hasInfo?`<button class="planning-note-button volunteer-info-button" type="button" aria-label="Ver informações" onclick="openVolunteerActivityInfo('${safe(a.name||raw.activityName||'Atividade')}','${safe(description)}','${safe(notes)}','${safe(materials)}')"><i class="fa-solid fa-circle-info"></i></button>`:''}</div><p>${Number(a.duration||raw.duration)||0} min • ${escapeHtml(a.period||raw.period||'Sem preferência')}</p><span class="volunteer-group-label"><i class="fa-solid fa-people-group"></i>${group}</span></div>${statusBadge}</div>${actions}</div>`};

  /* Chegada, saída, sábado e domingo são bloqueados para novas atividades. */
  volunteerAgendaContent=function(editable=false){const dates=volunteerStayDates();if(!dates.length)return '<div class="empty"><i class="fa-regular fa-calendar-xmark"></i>O período da estadia ainda não foi definido.</div>';return `<div class="calendar-strip">${dates.map(d=>`<button class="date-chip" onclick="scrollToVolunteerDay('${d}')"><span>${dayName(d)}</span><strong>${new Date(d+'T12:00:00').getDate()}</strong><span>${calendarMonthLabel(d)}</span></button>`).join('')}</div><div class="volunteer-plan-days">${dates.map(d=>{const ss=getSessions(d,true),adjustment=volunteerDayAdjustment(d),blocked=blockedDayReason(d);return `<div class="day-block" id="vday-${d}"><div class="day-title volunteer-day-title"><div><h3>${dayName(d)}, ${fmtDate(d)}</h3>${adjustment?'<span class="badge warning">Reajustar</span>':''}</div><div class="day-title-actions">${adjustment?`<button class="day-info-button" type="button" onclick="openVolunteerDayAdjustment('${d}')" aria-label="Ver orientação"><i class="fa-solid fa-circle-info"></i></button>`:''}<span>${ss.length?`${(ss.reduce((x,s)=>x+(Number(s.activity.duration)||0),0)/60).toFixed(1).replace('.0','')}h`:''}</span></div></div>${ss.map(s=>sessionCardVolunteer(s,editable)).join('')}${blocked?`<div class="no-activity-day"><i class="fa-regular fa-calendar-xmark"></i><span>${blocked}</span></div>`:(!ss.length?'<div class="empty">Nenhuma atividade planejada.</div>':'')}${editable&&state.volunteerMode!=='approved'&&!blocked?`<button class="btn btn-soft btn-block" style="margin-top:6px" onclick="openActivityModal('${d}')"><i class="fa-solid fa-plus"></i>Adicionar atividade</button>`:''}</div>`}).join('')}</div>`};

  const baseOpenActivityModal=openActivityModal;
  openActivityModal=function(date=null,id=null){if(!id&&date&&blockedDayReason(date))return showToast(blockedDayReason(date));const result=baseOpenActivityModal(date,id);const checks=[...modalRoot.querySelectorAll('input[name="actDate"]')];checks.forEach(input=>{const reason=blockedDayReason(input.value);if(!reason)return;input.disabled=true;input.closest('.check-card')?.classList.add('is-disabled');input.closest('.check-card')?.setAttribute('title',reason)});return result};

  /* Atualiza apenas o documento da candidatura, no máximo a cada 2 minutos. Não há polling. */
  async function refreshVolunteerApplication({hard=false}={}){const application=state.currentApplication;if(!application?.id||!window.OleiroServices?.applications?.getById)return application;if(applicationRefreshPromise)return applicationRefreshPromise;if(!hard&&Date.now()-applicationRefreshAt<APPLICATION_REFRESH_TTL)return application;applicationRefreshPromise=window.OleiroServices.applications.getById(application.id,{enrichProfiles:false}).then(fresh=>{if(!fresh)return application;const oldStart=iso(application.stayStart),oldEnd=iso(application.stayEnd);state.currentApplication={...application,...fresh};if(state.currentSession)state.currentSession.application=state.currentApplication;state.volunteerMode=fresh.status==='approved'?'approved':'candidate';state.volunteerPlanStatus=planStatusFromApplication(fresh.status);applicationRefreshAt=Date.now();const changedDates=oldStart!==iso(fresh.stayStart)||oldEnd!==iso(fresh.stayEnd);if(changedDates){state.volunteerPlanningLoadedFor=null;hydrateVolunteerPlanning(state.currentApplication,{force:true}).then(()=>render()).catch(console.error)}else render();return state.currentApplication}).catch(error=>{console.error('Não foi possível atualizar a candidatura:',error);return application}).finally(()=>{applicationRefreshPromise=null});return applicationRefreshPromise}
  const baseNavigateVolunteer=navigateVolunteer;
  navigateVolunteer=function(page){const result=baseNavigateVolunteer(page);if(['home','agenda','plan'].includes(page))refreshVolunteerApplication().catch(console.error);return result};
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.role==='volunteer')refreshVolunteerApplication().catch(console.error)});

  if(state.role==='volunteer'&&typeof render==='function')render();
})();
