/* Estado atual do Portal: dias sem atividade, navegação enxuta e agenda coerente. */
(function productCurrentPortal(){
  const APPLICATION_REFRESH_TTL=2*60*1000;
  let applicationRefreshAt=Date.now();
  let applicationRefreshPromise=null;

  function safe(value){return encodeURIComponent(String(value??''))}
  const safeHtml=typeof window.escapeHtml==='function'?window.escapeHtml:(value=>String(value??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]||c)));
  const safeStatusMeta=status=>typeof window.statusMeta==='function'?window.statusMeta(status):[String(status||''),''];
  function iso(value){if(!value)return '';if(typeof value==='string')return value.slice(0,10);if(typeof value.toDate==='function')return value.toDate().toISOString().slice(0,10);return ''}
  function blockedDayReason(date){
    const dates=volunteerStayDates(),first=dates[0],last=dates[dates.length-1];
    if(date===first)return t('portal.blocked.arrival');
    if(date===last)return t('portal.blocked.departure');
    const day=new Date(`${date}T12:00:00`).getDay();
    if(day===0||day===6)return t('portal.blocked.weekend');
    return '';
  }
  function deadlineDays(){const value=state.currentApplication?.planningDeadlineAt;if(!value)return null;let date=null;if(typeof value?.toDate==='function')date=value.toDate();else date=new Date(value);if(!date||Number.isNaN(date.getTime()))return null;return Math.max(0,Math.ceil((date.getTime()-Date.now())/86400000))}
  function profileStatus(){const application=state.currentApplication||{};if(state.volunteerMode==='approved')return [t('portal.profile.approved'),'success'];if(state.volunteerPlanStatus==='submitted')return [t('portal.profile.analysis'),'info'];if(state.volunteerPlanStatus==='adjustments')return [t('portal.profile.adjustments'),'warning'];if(application.status==='rejected')return [t('portal.profile.rejected'),'danger'];const days=deadlineDays(),label=days===null?t('portal.profile.preparing'):`${t('portal.profile.preparing')} · ${days===1?t('portal.profile.remainingOne'):t('portal.profile.remainingMany',{days})}`;return [label,'warning']}
  function supportCard(unit){return `<div class="card home-unit-support"><div class="home-unit-copy"><span class="home-unit-icon"><i class="fa-solid fa-location-dot"></i></span><div><small>${safeHtml(t('portal.support.unit'))}</small><strong>${safeHtml(unit)}</strong><span>${safeHtml(t('portal.support.support'))}: +55 47 99950-4753</span></div></div><a href="https://wa.me/5547999504753" target="_blank" rel="noopener noreferrer" aria-label="${safeHtml(t('portal.support.whatsappAria'))}"><i class="fa-brands fa-whatsapp"></i></a></div>`}

  window.confirmVolunteerLogout=function(){openModal(t('portal.logout.title'),t('portal.logout.question'),`<div class="notice"><i class="fa-solid fa-right-from-bracket"></i><div>${safeHtml(t('portal.logout.body'))}</div></div>`,`<div class="confirm-delete-actions"><button class="btn btn-outline" type="button" onclick="closeModal()">${safeHtml(t('common.cancel'))}</button><button class="btn btn-danger" type="button" onclick="logout()"><i class="fa-solid fa-right-from-bracket"></i>${safeHtml(t('action.signOut'))}</button></div>`)};

  volunteerNav=function(){
    const approved=state.volunteerMode==='approved';if(state.volunteerPage==='stay')state.volunteerPage='home';
    const items=approved?[['home','fa-house',t('portal.nav.home')],['agenda','fa-calendar-check',t('portal.nav.agenda')],['info','fa-circle-info',t('portal.nav.info')],['profile','fa-user',t('portal.nav.profile')]]:[['home','fa-house',t('portal.nav.home')],['plan','fa-calendar-plus',t('portal.nav.planning')],['info','fa-circle-info',t('portal.nav.info')],['profile','fa-user',t('portal.nav.profile')]];
    return `<nav class="bottom-nav volunteer-nav-current">${items.map(([id,ic,tx])=>`<button class="nav-btn ${state.volunteerPage===id?'active':''}" onclick="navigateVolunteer('${id}')"><i class="fa-solid ${ic}"></i><span>${safeHtml(tx)}</span></button>`).join('')}<button class="nav-btn nav-logout" type="button" onclick="confirmVolunteerLogout()"><i class="fa-solid fa-right-from-bracket"></i><span>${safeHtml(t('portal.nav.signout'))}</span></button></nav>`;
  };

  /* Perfil em um único card, compacto e com status visual. */
  volunteerProfile=function(){
    const session=state.currentSession||{},profile=session.profile||{},application=state.currentApplication||{},name=volunteerProfileName();
    const country=profile.country||profile.nationality||(Array.isArray(application.participantCountries)?application.participantCountries[0]:null)||'—';
    const unit=application.unitName||String(application.unitId||'—').replace(/^./,c=>c.toUpperCase()),email=profile.email||session.email||'—',phone=profile.phone||profile.whatsapp||'—',status=profileStatus();
    return `<section class="section volunteer-profile-page"><div class="section-head"><div><span class="eyebrow">${safeHtml(t('portal.profile.eyebrow'))}</span><h2>${safeHtml(t('portal.profile.title'))}</h2><p>${safeHtml(t('portal.profile.subtitle'))}</p></div></div><div class="card volunteer-profile-unified"><div class="volunteer-profile-identity"><div class="profile-avatar">${volunteerProfileInitials(name)}</div><div><strong>${safeHtml(name)}</strong><span>${safeHtml(country)} • ${safeHtml(unit)}</span></div></div><div class="profile-details volunteer-profile-details"><div><span>${safeHtml(t('portal.profile.email'))}</span><strong>${safeHtml(email)}</strong></div><div><span>WhatsApp</span><strong>${safeHtml(phone)}</strong></div><div><span>${safeHtml(t('portal.profile.period'))}</span><strong>${volunteerApplicationDate(application.stayStart)}–${volunteerApplicationDate(application.stayEnd)}</strong></div><div><span>${safeHtml(t('portal.profile.status'))}</span><strong class="profile-status ${status[1]}">${safeHtml(status[0])}</strong></div></div></div></section>`;
  };

  /* Suporte: voluntário aprovado logo abaixo da estadia; candidato após as informações de chegada. */
  const baseVolunteerHome=volunteerHome;
  volunteerHome=function(){
    let html=baseVolunteerHome(),application=state.currentApplication||{},unit=application.unitName||String(application.unitId||'Rodeio').replace(/^./,c=>c.toUpperCase()),support=supportCard(unit),approved=state.volunteerMode==='approved';
    const unitInArrival=`<span style="font-size:.62rem;color:var(--muted)">${safeHtml(unit)}</span>`;
    html=html.replace(unitInArrival,`<span style="font-size:.62rem;color:var(--muted)">${safeHtml(t('portal.home.noActivityDay'))}</span>`);
    if(!html.includes('home-unit-support'))html+=support;
    if(!approved&&(state.volunteerPlanStatus||'draft')==='draft'){const days=deadlineDays();if(days!==null)html=html.replace(t('portal.home.proposedPeriod'),`${t('portal.profile.preparing')} · ${days===1?t('portal.profile.remainingOne'):t('portal.profile.remainingMany',{days})}`)}
    return html;
  };

  window.openVolunteerActivityInfo=function(name,notes,materials){const n=decodeURIComponent(name||''),o=decodeURIComponent(notes||''),m=decodeURIComponent(materials||''),sections=[];if(o)sections.push(`<div class="activity-info-block"><strong>${safeHtml(t('portal.activity.infoNotes'))}</strong><p data-no-i18n>${safeHtml(o)}</p></div>`);if(m&&m!=='Nenhum')sections.push(`<div class="activity-info-block"><strong>${safeHtml(t('portal.activity.infoMaterials'))}</strong><p data-no-i18n>${safeHtml(m)}</p></div>`);openModal(n||t('portal.activity.infoTitle'),'',`<div class="activity-info-compact">${sections.join('')||`<div class="empty">${safeHtml(t('common.noAdditionalInfo'))}</div>`}</div>`);modalRoot.querySelector('.modal')?.classList.add('activity-info-modal-compact')};

  sessionCardVolunteer=function(s,editable){const a=s.activity||{},raw=s.raw||{},description=raw.activityDescription||a.description||'',notes=raw.notes||a.notes||'',materials=raw.materials||a.materials||'',hasInfo=!!(notes||(materials&&materials!=='Nenhum')),candidateEdit=editable&&state.volunteerMode!=='approved',approved=state.volunteerMode==='approved',change=s.status==='change_requested',group=s.group&&s.group!=='A definir'?t('portal.session.group',{group:s.group}):t('portal.session.groupPending'),statusBadge=!approved&&state.volunteerPlanStatus==='submitted'?badge(t('portal.plan.sentButton'),'info'):change?badge(t('portal.session.changeRequested'),'warning'):(s.status==='proposed'&&!approved?'':s.status==='confirmed'?'':badge(safeStatusMeta(s.status)[0],safeStatusMeta(s.status)[1])),sessionId=s.sessionId||raw.id||'';const actions=candidateEdit?`<div class="activity-actions candidate-session-actions"><button class="btn btn-outline" onclick='openActivityModal(${JSON.stringify(s.date)},${JSON.stringify(a.id)})'>${safeHtml(t('action.edit'))}</button><button class="btn btn-outline" onclick="moveSessionById('${safe(sessionId)}',true)">${safeHtml(t('action.move'))}</button><button class="btn btn-danger-soft" onclick='requestDeletePlanningSession(${JSON.stringify(a.id)},${JSON.stringify(s.date)})'>${safeHtml(t('action.delete'))}</button></div>`:approved?(change?`<div class="activity-actions"><button class="btn btn-soft" type="button" disabled><i class="fa-solid fa-clock"></i>${safeHtml(t('portal.session.changeRequested'))}</button></div>`:`<div class="activity-actions"><button class="btn btn-outline" type="button" onclick="moveSessionById('${safe(sessionId)}',true)">${safeHtml(t('action.requestChange'))}</button></div>`):'';return `<div class="activity-card volunteer-session-card"><div class="activity-row"><div class="volunteer-session-main"><div class="volunteer-session-title"><h4 data-no-i18n>${safeHtml(a.name||raw.activityName||t('role.volunteer'))}</h4>${hasInfo?`<button class="planning-note-button volunteer-info-button" type="button" aria-label="${safeHtml(t('portal.activity.infoAria'))}" onclick="openVolunteerActivityInfo('${safe(a.name||raw.activityName||'Atividade')}','${safe(notes)}','${safe(materials)}')"><i class="fa-solid fa-circle-info"></i></button>`:''}</div><p>${Number(a.duration||raw.duration)||0} min • ${safeHtml(tValue(activityPeriodValue(raw,a)))}</p><span class="volunteer-group-label"><i class="fa-solid fa-people-group"></i>${safeHtml(group)}</span>${description?`<p class="volunteer-session-description"><strong>${safeHtml(t('portal.activity.descriptionLabel'))}</strong> <span data-no-i18n>${safeHtml(description)}</span></p>`:''}</div>${statusBadge}</div>${actions}</div>`};

  /* Chegada, saída, sábado e domingo são bloqueados para novas atividades. */
  volunteerAgendaContent=function(editable=false){const dates=volunteerStayDates();if(!dates.length)return `<div class="empty"><i class="fa-regular fa-calendar-xmark"></i>${safeHtml(t('portal.plan.noPeriod'))}</div>`;return `<div class="calendar-strip">${dates.map(d=>`<button class="date-chip" onclick="scrollToVolunteerDay('${d}')"><span>${dayName(d)}</span><strong>${new Date(d+'T12:00:00').getDate()}</strong><span>${calendarMonthLabel(d)}</span></button>`).join('')}</div><div class="volunteer-plan-days">${dates.map(d=>{const ss=getSessions(d,true),adjustment=volunteerDayAdjustment(d),blocked=blockedDayReason(d);return `<div class="day-block" id="vday-${d}"><div class="day-title volunteer-day-title"><div><h3>${dayName(d)}, ${fmtDate(d)}</h3>${adjustment?`<span class="badge warning">${safeHtml(t('portal.plan.adjust'))}</span>`:''}</div><div class="day-title-actions">${adjustment?`<button class="day-info-button" type="button" onclick="openVolunteerDayAdjustment('${d}')" aria-label="${safeHtml(t('portal.plan.viewGuidance'))}"><i class="fa-solid fa-circle-info"></i></button>`:''}<span>${ss.length?`${(ss.reduce((x,s)=>x+(Number(s.activity.duration)||0),0)/60).toFixed(1).replace('.0','')}h`:''}</span></div></div>${ss.map(s=>sessionCardVolunteer(s,editable)).join('')}${blocked?`<div class="no-activity-day"><i class="fa-regular fa-calendar-xmark"></i><span>${safeHtml(blocked)}</span></div>`:(!ss.length?`<div class="empty">${safeHtml(t('portal.plan.noActivity'))}</div>`:'')}${editable&&state.volunteerMode!=='approved'&&!blocked?`<button class="btn btn-soft btn-block" style="margin-top:6px" onclick="openActivityModal('${d}')"><i class="fa-solid fa-plus"></i>${safeHtml(t('action.addActivity'))}</button>`:''}</div>`}).join('')}</div>`};

  const baseOpenActivityModal=openActivityModal;
  openActivityModal=function(date=null,id=null){if(!id&&date&&blockedDayReason(date))return showToast(blockedDayReason(date));const result=baseOpenActivityModal(date,id);const checks=[...modalRoot.querySelectorAll('input[name="actDate"]')];checks.forEach(input=>{const reason=blockedDayReason(input.value);if(!reason)return;input.disabled=true;input.closest('.check-card')?.classList.add('is-disabled');input.closest('.check-card')?.setAttribute('title',reason)});return result};

  /* Atualiza apenas o documento da candidatura, no máximo a cada 2 minutos. Não há polling. */
  async function refreshVolunteerApplication({hard=false}={}){const application=state.currentApplication;if(!application?.id||!window.OleiroServices?.applications?.getById)return application;if(applicationRefreshPromise)return applicationRefreshPromise;if(!hard&&Date.now()-applicationRefreshAt<APPLICATION_REFRESH_TTL)return application;applicationRefreshPromise=window.OleiroServices.applications.getById(application.id,{enrichProfiles:false}).then(fresh=>{if(!fresh)return application;const oldStart=iso(application.stayStart),oldEnd=iso(application.stayEnd);state.currentApplication={...application,...fresh};if(state.currentSession)state.currentSession.application=state.currentApplication;state.volunteerMode=fresh.status==='approved'?'approved':'candidate';state.volunteerPlanStatus=planStatusFromApplication(fresh.status);applicationRefreshAt=Date.now();const changedDates=oldStart!==iso(fresh.stayStart)||oldEnd!==iso(fresh.stayEnd);if(changedDates){state.volunteerPlanningLoadedFor=null;hydrateVolunteerPlanning(state.currentApplication,{force:true}).then(()=>render()).catch(console.error)}else render();return state.currentApplication}).catch(error=>{if(error?.code==='unavailable'||/offline|failed to get/i.test(String(error?.message||'')))console.warn('Sem conexão para atualizar a candidatura; mantendo os dados já carregados.');else console.error('Não foi possível atualizar a candidatura:',error);return application}).finally(()=>{applicationRefreshPromise=null});return applicationRefreshPromise}
  const baseNavigateVolunteer=navigateVolunteer;
  navigateVolunteer=function(page){const result=baseNavigateVolunteer(page);if(['home','agenda','plan'].includes(page))refreshVolunteerApplication().catch(console.error);return result};
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.role==='volunteer')refreshVolunteerApplication().catch(console.error)});

  if(state.role==='volunteer'&&typeof render==='function')render();
})();
