/* Round 5 — Portal: reenvio encerra ajuste, estadia mais limpa e próxima atividade sem botão redundante. */
(function round5Portal(){
  submitPlan=async function(){
    const acts=volunteerActivities();if(!acts.length||(state.sessions||[]).length===0)return showToast('Adicione pelo menos uma atividade antes de enviar.');
    const application=state.currentApplication;if(!application?.id)return showToast('Candidatura não encontrada.');
    const wasAdjustment=state.volunteerPlanStatus==='adjustments';
    try{
      await window.OleiroServices.applications.submitPlanning(application.id,{wasAdjustment});
      application.status='analysis';application.planningSubmittedAt=new Date().toISOString();
      if(wasAdjustment)application.dayAdjustments={};
      if(state.currentSession)state.currentSession.application=application;
      state.volunteerPlanStatus='submitted';render();showToast(wasAdjustment?'Planejamento reenviado para análise.':'Planejamento enviado para análise.');
    }catch(error){console.error(error);showToast(error?.message||'Não foi possível enviar o planejamento.')}
  };

  volunteerStay=function(){
    const application=state.currentApplication||{},unit=application.unitName||String(application.unitId||'—').replace(/^./,c=>c.toUpperCase());
    return `<section class="section"><div class="section-head"><div><span class="eyebrow">${escapeHtml(unit)}</span><h2>Minha estadia</h2><p>Informações do período</p></div></div><div class="grid-2"><div class="card"><span class="eyebrow">Chegada</span><strong style="display:block;margin-top:8px">${stayFullDate(application.stayStart)}</strong></div><div class="card"><span class="eyebrow">Saída</span><strong style="display:block;margin-top:8px">${stayFullDate(application.stayEnd)}</strong></div></div><div class="card stay-unit-card" style="margin-top:10px"><h3>Unidade ${escapeHtml(unit)}</h3><p>A equipe local acompanha a experiência e pode ajustar datas e atividades conforme a rotina da comunidade.</p><a class="stay-support-link" href="https://wa.me/5547999504753" target="_blank" rel="noopener noreferrer"><span class="stay-support-icon"><i class="fa-brands fa-whatsapp"></i></span><span class="stay-support-copy"><small>Suporte pelo WhatsApp</small><strong>+55 47 99950-4753</strong></span><i class="fa-solid fa-chevron-right"></i></a></div></section>`;
  };

  volunteerHome=function(){
    const application=state.currentApplication||{},approved=state.volunteerMode==='approved',planStatus=state.volunteerPlanStatus||'draft',showPlanStatus=!approved&&planStatus!=='draft';
    const from=typeof portalIsoDate==='function'?portalIsoDate(application.stayStart):null,to=typeof portalIsoDate==='function'?portalIsoDate(application.stayEnd):null,unit=application.unitName||((application.unitId||'').replace(/^./,c=>c.toUpperCase()))||'Unidade',period=from&&to?`${fmtDate(from)} a ${fmtDate(to)}`:'Período a confirmar';
    const planMeta={submitted:['Enviado para análise','success','A equipe da Casa recebeu seu planejamento. Enquanto ele estiver em análise, a edição fica bloqueada.'],adjustments:['Ajustes solicitados','warning','A equipe pediu alterações. Revise somente os dias sinalizados e reenvie quando estiver pronto.'],approved:['Planejamento aprovado','success','Seu planejamento foi aprovado pela equipe da Casa.']}[planStatus]||['Planejamento pendente','warning','Monte seu planejamento e envie para análise.'];
    const heroAction=approved?`<button class="btn btn-light" onclick="navigateVolunteer('agenda')"><i class="fa-regular fa-calendar-check"></i>Minha agenda</button>`:`<button class="btn btn-light" onclick="navigateVolunteer('plan')"><i class="fa-solid ${planStatus==='adjustments'?'fa-pen-to-square':planStatus==='submitted'?'fa-eye':'fa-calendar-plus'}"></i>${planStatus==='adjustments'?'Ajustar planejamento':planStatus==='submitted'?'Ver planejamento':'Montar planejamento'}</button>`;
    const nextDay=approved?getNextVolunteerDay():null;
    return `<section class="hero"><div class="eyebrow" style="color:#d9eadf">${approved?'Estadia confirmada':'Período proposto'}</div><h1>${approved?'Bem-vindo à sua experiência':'Prepare sua experiência'}</h1><p class="muted">${escapeHtml(unit)} • ${period}</p><div class="hero-actions">${heroAction}</div></section>
    ${approved?`<section class="section"><div class="section-head"><div><h2>${nextDay?.date===portalToday()?'Atividades de hoje':'Próximas atividades'}</h2><p>${nextDay?`${dayName(nextDay.date)} • ${fmtDate(nextDay.date)}`:'O que vem a seguir'}</p></div></div>${nextDay?`<div class="list">${nextDay.sessions.map(volunteerHomeActivityCard).join('')}</div>`:'<div class="empty"><i class="fa-regular fa-calendar-check"></i>Nenhuma próxima atividade programada.</div>'}</section>`:''}
    ${showPlanStatus?`<section class="section"><div class="section-head"><div><h2>Seu planejamento</h2><p>Status do planejamento</p></div><button class="btn btn-soft" onclick="navigateVolunteer('plan')">Ver</button></div><div class="card"><div class="status-line"><span class="dot ${planMeta[1]==='success'?'success':'warning'}"></span><strong style="font-size:.76rem">${planMeta[0]}</strong></div><p style="font-size:.66rem;color:var(--muted);margin-top:7px">${planMeta[2]}</p><div class="stat-row"><span class="stat-pill">${volunteerActivities().length} atividades</span><span class="stat-pill">${volunteerActivities().reduce((s,a)=>s+(a.dates||[]).length,0)} sessões</span></div></div></section>`:''}
    <section class="section"><div class="section-head"><div><h2>Minha estadia</h2><p>Informações principais</p></div></div><div class="grid-2"><div class="card"><span class="eyebrow">Chegada</span><strong style="display:block;margin-top:8px;font-size:.85rem">${from?fmtDate(from,true):'—'}</strong><span style="font-size:.62rem;color:var(--muted)">${escapeHtml(unit)}</span></div><div class="card"><span class="eyebrow">Saída</span><strong style="display:block;margin-top:8px;font-size:.85rem">${to?fmtDate(to,true):'—'}</strong><span style="font-size:.62rem;color:var(--muted)">Dia sem atividade</span></div></div></section>
    <section class="section"><div class="section-head"><div><h2>Informações importantes</h2><p>Tudo para sua chegada</p></div></div><div class="list"><button class="menu-link" onclick="window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('R. São Pedro Novo, 1999, Rodeio - SC, 89136-000'),'_blank')"><i class="fa-solid fa-route"></i><span>Como chegar<small>Transporte, endereço e horários</small></span><i class="fa-solid fa-chevron-right"></i></button><button class="menu-link" onclick="navigateVolunteer('info')"><i class="fa-solid fa-house"></i><span>Acomodação e refeições<small>O que está incluído na experiência</small></span><i class="fa-solid fa-chevron-right"></i></button></div></section>`;
  };
})();
