function openNewCandidate(){openModal('Novo candidato','Cadastre somente quem já está no processo real de avaliação.',`<div class="form-grid"><div class="field"><label>Nome</label><input id="ncName" class="input" placeholder="Nome completo"></div><div class="field"><label>E-mail</label><input id="ncEmail" class="input" type="email" placeholder="email@exemplo.com"></div><div class="field-row"><div class="field"><label>WhatsApp</label><input id="ncPhone" class="input" placeholder="+55 ..."></div><div class="field"><label>Nacionalidade</label><input id="ncCountry" class="input" placeholder="País"></div></div><div class="field"><label>Unidade</label><select id="ncUnit" class="select"><option>Rodeio</option><option>Indaial</option></select></div><div class="field-row"><div class="field"><label>Chegada proposta</label><input id="ncFrom" class="input" type="date"></div><div class="field"><label>Saída proposta</label><input id="ncTo" class="input" type="date"></div></div><div class="field"><label>Observação interna</label><textarea id="ncNote" class="textarea" placeholder="Opcional"></textarea></div><button class="btn btn-primary btn-block" onclick="saveCandidate()">Cadastrar e liberar acesso</button></div>`)}

function saveCandidate(){const name=document.getElementById('ncName').value.trim();const email=document.getElementById('ncEmail').value.trim();if(!name||!email)return showToast('Informe nome e e-mail.');state.candidates.unshift({id:Date.now(),name,country:document.getElementById('ncCountry').value||'—',email,phone:document.getElementById('ncPhone').value,unit:document.getElementById('ncUnit').value,from:document.getElementById('ncFrom').value||'2026-09-01',to:document.getElementById('ncTo').value||'2026-09-15',status:'pending',sessions:0,activities:0,submitted:'—'});closeModal();state.managerPage='volunteer';state.candidateTab='candidates';state.candidateFilter='pending';render();showToast('Candidato cadastrado no protótipo.')}

function openPerson(id,tab='overview'){
  const p=state.candidates.find(x=>x.id===id);if(!p)return;state.personModalTab=tab;
  const tabs=[['overview','Visão geral'],['plan','Planejamento'],['stay','Estadia'],['history','Histórico']];
  openModal(p.name,`${p.country} • ${p.unit}`,`<div class="tabs person-tabs">${tabs.map(([k,l])=>`<button class="tab ${tab===k?'active':''}" onclick="openPerson(${p.id},'${k}')">${l}</button>`).join('')}</div>${personTabContent(p,tab)}`)
}

function personTabContent(p,tab){
  const [l,t]=statusMeta(p.status);
  if(tab==='plan'){
    const acts=state.activities.filter(a=>a.owner===p.name);
    return acts.length?`<div class="list">${acts.map(a=>`<div class="card"><div class="activity-row"><div><h3 style="font-size:.8rem">${a.name}</h3><p style="font-size:.64rem;color:var(--muted);margin-top:3px">${a.description}</p></div>${badge(a.dates.length+' sessões','primary')}</div><div style="margin-top:10px">${a.dates.map(d=>{const st=state.sessionStatus[`${a.id}-${d}`]||'proposed';const [sl,stt]=statusMeta(st);return `<button class="menu-link" style="margin-bottom:6px" onclick="closeModal();openSessionDetail(${a.id},'${d}')"><i class="fa-regular fa-calendar"></i><span>${dayName(d)} • ${fmtDate(d)} • ${a.time}<small>${sl} • ${state.sessionGroups[`${a.id}-${d}`]||'Grupo a definir'}</small></span><i class="fa-solid fa-chevron-right" style="color:var(--muted)"></i></button>`}).join('')}</div></div>`).join('')}</div>`:`<div class="empty"><i class="fa-regular fa-calendar-xmark"></i>Nenhuma atividade cadastrada ainda.</div>`;
  }
  if(tab==='stay') return `<div class="card"><span class="eyebrow">${p.status==='approved'?'Estadia confirmada':'Período proposto'}</span><div class="grid-2" style="margin-top:10px"><div><strong style="font-size:.8rem">Chegada</strong><p class="compact-hint">${fmtDate(p.from)}</p></div><div><strong style="font-size:.8rem">Saída</strong><p class="compact-hint">${fmtDate(p.to)}</p></div></div><div style="margin-top:12px"><strong style="font-size:.72rem">Unidade</strong><p class="compact-hint">${p.unit}</p></div></div>`;
  if(tab==='history') return `<div class="list"><div class="list-item"><div class="metric-icon"><i class="fa-solid fa-user-plus"></i></div><div class="item-main"><h3>Perfil criado</h3><p>Acesso liberado para o processo de planejamento.</p></div></div>${p.submitted!=='—'?`<div class="list-item"><div class="metric-icon"><i class="fa-solid fa-paper-plane"></i></div><div class="item-main"><h3>Planejamento enviado</h3><p>${p.submitted}</p></div></div>`:''}<div class="list-item"><div class="metric-icon"><i class="fa-solid fa-circle-info"></i></div><div class="item-main"><h3>Status atual</h3><p>${l}</p></div>${badge(l,t)}</div></div>`;
  return `<div class="card"><div class="activity-row"><div><span class="eyebrow">Status</span><h3 style="font-size:.88rem;margin-top:5px">${l}</h3></div>${badge(l,t)}</div><div class="stat-row"><span class="stat-pill">${fmtDate(p.from,true)}–${fmtDate(p.to,true)}</span><span class="stat-pill">${p.activities} atividades</span><span class="stat-pill">${p.sessions} sessões</span></div></div><div class="card" style="margin-top:10px"><h3 style="font-size:.78rem">Contato</h3><p style="font-size:.66rem;color:var(--muted);margin-top:6px">${p.email}<br>${p.phone}</p></div>${p.status==='analysis'||p.status==='adjustments'?`<div class="activity-actions" style="margin-top:12px"><button class="btn btn-primary" onclick="approveCandidate(${p.id})">Aprovar</button><button class="btn btn-outline" onclick="requestAdjust(${p.id})">Pedir ajuste</button><button class="btn btn-danger" onclick="rejectCandidate(${p.id})">Recusar</button></div>`:''}${p.status==='rejected'?`<button class="btn btn-soft btn-block" style="margin-top:12px" onclick="reactivateCandidate(${p.id})">Reativar perfil</button>`:''}`;
}

function approveCandidate(id){const p=state.candidates.find(x=>x.id===id);p.status='approved';closeModal();render();showToast('Candidato aprovado. Estadia confirmada.')}

function requestAdjust(id){const p=state.candidates.find(x=>x.id===id);p.status='adjustments';closeModal();render();showToast('Planejamento devolvido para ajustes.')}

function rejectCandidate(id){const p=state.candidates.find(x=>x.id===id);p.status='rejected';closeModal();state.candidateTab='rejected';render();showToast('Perfil movido para Rejeitados e inativado.')}

function reactivateCandidate(id){const p=state.candidates.find(x=>x.id===id);p.status='pending';closeModal();state.candidateTab='candidates';state.candidateFilter='pending';render();showToast('Perfil reativado.')}

function confirmSession(id,date){state.sessionStatus[`${id}-${date}`]='confirmed';render();showToast('Sessão confirmada.')}

function assignGroup(id,date){openModal('Definir grupo','Somente a equipe da Casa define quem participa.',`<div class="check-grid">${['A','B','C','D','A+B','C+D','Livre'].map(g=>`<button class="check-card" onclick="saveGroup(${id},'${date}','${g}')">${g==='Livre'?'Participação livre':'Grupo '+g}</button>`).join('')}</div>`)}

function saveGroup(id,date,g){state.sessionGroups[`${id}-${date}`]=g;closeModal();render();showToast('Grupo atualizado.')}
