/* Admin activity flow: multi-groups, same-day repetitions, portal-like planning cards and aligned emergency profile. */
(function adminActivityFlow(){
  const baseOpenCreate=window.openAdminPlanningActivity;
  const baseOpenEdit=window.openAdminEditPlanningSession;
  const baseRenderPersonModal=window.renderPersonModal||renderPersonModal;
  const baseAdminPlanningDayCard=window.adminPlanningDayCard||adminPlanningDayCard;
  const text=key=>typeof t==='function'?t(key):key;
  let repeatIndex=0;

  function safe(value){return encodeURIComponent(String(value??''))}
  function parseGroups(value){const parts=String(value||'').split('+').map(item=>item.trim()).filter(Boolean);if(parts.includes('Livre'))return ['Livre'];return [...new Set(parts.filter(item=>['A','B','C','D'].includes(item)))]}
  function availableGroups(){const loaded=(state.groups||[]).map(group=>String(group.code||group.id||'').trim()).filter(code=>['A','B','C','D'].includes(code));return [...new Set([...loaded,'A','B','C','D'])]}
  function groupValue(values){const clean=[...new Set((values||[]).filter(Boolean))];if(clean.includes('Livre'))return 'Livre';return clean.join(' + ')}
  function participationForGroups(values){const clean=parseGroups(groupValue(values));if(clean.includes('Livre'))return 'Livre';return clean.length>1?`Grupos ${clean.join(' + ')}`:clean.length?`Grupo ${clean[0]}`:'Livre'}
  function pickerHtml(prefix,selected){const current=parseGroups(selected),options=[...availableGroups(),'Livre'];return `<div class="activity-group-picker" data-group-picker="${escapeHtml(prefix)}"><div class="activity-group-grid">${options.map(group=>`<label class="check-card"><input type="checkbox" data-group-choice="${escapeHtml(prefix)}" value="${group}" ${current.includes(group)?'checked':''}><span>${group==='Livre'?'Livre':`Grupo ${escapeHtml(group)}`}</span></label>`).join('')}</div><small>${escapeHtml(text('activity.groupsHelp'))}</small></div>`}
  function selectedGroups(prefix){return [...document.querySelectorAll(`input[data-group-choice="${CSS.escape(prefix)}"]:checked`)].map(input=>input.value)}
  function syncPrimaryGroup(){const select=document.getElementById('managerActGroup');if(!select)return;const value=groupValue(selectedGroups('manager-primary'));select.innerHTML=`<option value="${escapeHtml(value)}" selected>${escapeHtml(value)}</option>`}
  function bindGroupPicker(root,prefix,{syncPrimary=false}={}){root.querySelectorAll(`input[data-group-choice="${CSS.escape(prefix)}"]`).forEach(input=>input.addEventListener('change',()=>{const boxes=[...root.querySelectorAll(`input[data-group-choice="${CSS.escape(prefix)}"]`)];if(input.checked&&input.value==='Livre')boxes.forEach(box=>{if(box!==input)box.checked=false});else if(input.checked)boxes.filter(box=>box.value==='Livre').forEach(box=>box.checked=false);if(syncPrimary)syncPrimaryGroup()}));if(syncPrimary)syncPrimaryGroup()}
  function enhancePrimaryGroups(selected='Livre'){
    const select=document.getElementById('managerActGroup');if(!select)return;const field=select.closest('.field');if(!field||field.querySelector('[data-group-picker="manager-primary"]'))return;field.querySelector('label')?.replaceChildren(document.createTextNode(text('activity.groups')));select.classList.add('activity-group-source');select.insertAdjacentHTML('beforebegin',pickerHtml('manager-primary',selected));bindGroupPicker(field,'manager-primary',{syncPrimary:true});
  }
  function findAdminSession(applicationId,sessionId){
    const direct=(state.sessions||[]).find(row=>String(row.id)===String(sessionId)&&String(row.applicationId||applicationId)===String(applicationId));if(direct)return direct;
    for(const [key,cache] of Object.entries(state.adminPlanPageCache||{})){if(!key.startsWith(`${applicationId}|`))continue;const row=(cache?.sessions||[]).find(item=>String(item.id)===String(sessionId));if(row)return row}return null;
  }

  function repeatBlock(){return `<div class="activity-repeat-block" id="adminRepeatBlock"><div class="activity-repeat-head"><div class="activity-repeat-copy"><strong>${escapeHtml(text('activity.repeat.title'))}</strong><small>${escapeHtml(text('activity.repeat.help'))}</small></div><button class="btn btn-outline activity-repeat-add" type="button" onclick="addAdminRepeatSession()"><i class="fa-solid fa-plus"></i>${escapeHtml(text('activity.repeat.add'))}</button></div><div class="activity-repeat-list" id="adminRepeatList"></div></div>`}
  window.addAdminRepeatSession=function(){
    const list=document.getElementById('adminRepeatList');if(!list)return;const index=++repeatIndex,prefix=`manager-repeat-${index}`,periodId=`managerRepeatPeriod${index}`,row=document.createElement('div');row.className='activity-repeat-row';const primary=groupValue(selectedGroups('manager-primary'))||'Livre';row.dataset.repeatGroupPrefix=prefix;row.innerHTML=`<div class="activity-repeat-row-head"><div class="field"><label for="${periodId}">${escapeHtml(text('activity.repeat.period'))}</label><select id="${periodId}" class="select" data-repeat-period>${['Sem preferência','Manhã','Tarde','Noite'].map(period=>`<option value="${escapeHtml(period)}">${escapeHtml(tValue(period))}</option>`).join('')}</select></div><button class="icon-btn" type="button" aria-label="${escapeHtml(text('activity.repeat.remove'))}" title="${escapeHtml(text('activity.repeat.remove'))}" onclick="this.closest('.activity-repeat-row').remove()"><i class="fa-solid fa-trash"></i></button></div><div class="field"><label>${escapeHtml(text('activity.groups'))}</label>${pickerHtml(prefix,primary)}</div>`;list.appendChild(row);bindGroupPicker(row,prefix);
  };
  window.addAdminRepeatTime=window.addAdminRepeatSession;

  function enhanceCreateModal(){enhancePrimaryGroups('Livre');const period=document.getElementById('managerActPeriod'),row=period?.closest('.field');if(row&&!document.getElementById('adminRepeatBlock'))row.insertAdjacentHTML('afterend',repeatBlock())}
  openAdminPlanningActivity=function(encodedId,encodedDate){const result=baseOpenCreate(encodedId,encodedDate);enhanceCreateModal();return result};
  openAdminEditPlanningSession=function(encodedId,encodedSessionId,encodedDate){const id=decodeURIComponent(encodedId),sessionId=decodeURIComponent(encodedSessionId),session=findAdminSession(id,sessionId),result=baseOpenEdit(encodedId,encodedSessionId,encodedDate);enhancePrimaryGroups(session?.groupId||'Livre');return result};

  function readPrimaryData(){const groups=selectedGroups('manager-primary');return {name:document.getElementById('managerActName')?.value.trim()||'',description:document.getElementById('managerActDesc')?.value.trim()||'',duration:Number(document.getElementById('managerActDuration')?.value)||60,groups,groupId:groupValue(groups),participation:participationForGroups(groups),materials:document.getElementById('managerActMaterials')?.value.trim()||'Nenhum',notes:document.getElementById('managerActNotes')?.value.trim()||'',period:document.getElementById('managerActPeriod')?.value||'Sem preferência'}}
  function updateAdminCacheAfterSeries(p,date,result){
    const activities=(result?.activities||[]).map(activity=>({...activity,id:String(activity.id),dates:[date]})),byId=new Map(activities.map(activity=>[String(activity.id),activity])),rows=(result?.sessions||[]).map(row=>({...row,activity:byId.get(String(row.activityId))||row.activity}));
    Object.entries(state.adminPlanPageCache||{}).forEach(([key,cache])=>{if(!key.startsWith(`${p.id}|`)||!Array.isArray(cache?.dates)||!cache.dates.includes(date))return;cache.activities=(cache.activities||[]).concat(activities);cache.sessions=(cache.sessions||[]).concat(rows).sort(activityScheduleCompare);cache.at=Date.now()});
    p.activities=(Number(p.activities)||0)+activities.length;p.sessions=(Number(p.sessions)||0)+rows.length;p.planningCountVersion=1;
  }
  saveAdminPlanningActivity=async function(encodedId,encodedDate){
    const id=decodeURIComponent(encodedId),date=decodeURIComponent(encodedDate),p=candidateById(id),button=document.getElementById('managerActSave');if(!p)return showToast('Cadastro não encontrado.');const data=readPrimaryData();if(!data.name)return showToast('Informe o nome da atividade.');if(data.duration<15||data.duration>240)return showToast('Informe uma duração entre 15 e 240 minutos.');if(!data.groupId)return showToast(text('activity.groupRequired'));const uid=state.currentSession?.uid;if(!uid)return showToast('Sessão administrativa inválida.');
    const occurrences=[{period:data.period,groupId:data.groupId,participation:data.participation}];for(const row of document.querySelectorAll('#adminRepeatList .activity-repeat-row')){const prefix=row.dataset.repeatGroupPrefix,period=row.querySelector('select[data-repeat-period]')?.value||'Sem preferência',groups=selectedGroups(prefix),groupId=groupValue(groups);if(!groupId)return showToast(text('activity.groupRequired'));occurrences.push({period,groupId,participation:participationForGroups(groups)})}const signatures=occurrences.map(item=>`${item.period}|${item.groupId}`);if(new Set(signatures).size!==signatures.length)return showToast(text('activity.repeat.duplicatePeriodGroup'));
    if(button){button.disabled=true;button.innerHTML='<i class="fa-solid fa-circle-notch fa-spin"></i> Salvando...'}
    try{const result=await window.OleiroServices.planning.createActivitySeries({applicationId:p.id,unitId:p.unitId||String(p.unit||'').toLowerCase(),createdByUid:uid,ownerName:p.name||'Voluntário',data,date,occurrences,postApprovalProposal:false,sessionStatus:'confirmed',managerCreated:true,updateApplicationCounts:true});updateAdminCacheAfterSeries(p,date,result);renderPersonModal(p,'plan');const target=modalRoot.querySelector(`details[data-plan-date="${CSS.escape(date)}"]`);if(target)target.open=true;showToast(occurrences.length>1?'Atividades criadas e confirmadas.':'Atividade criada e confirmada.')}catch(error){console.error(error);showToast(error?.message||'Não foi possível criar a atividade.');if(button?.isConnected){button.disabled=false;button.innerHTML='<i class="fa-solid fa-check"></i>Adicionar ao planejamento'}}
  };

  function meaningfulMaterials(value){const normalized=String(value||'').trim();return normalized&&!['Nenhum','None','Ninguno','Ningún'].includes(normalized)}
  function normalizedPeriod(value){
    const raw=String(value||'Sem preferência').trim()||'Sem preferência',key=raw.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
    if(['manha','morning','manana'].includes(key))return {key:'Manhã',label:'Manhã',rank:0,icon:'fa-sun'};
    if(['tarde','afternoon'].includes(key))return {key:'Tarde',label:'Tarde',rank:1,icon:'fa-cloud-sun'};
    if(['noite','night','evening','noche'].includes(key))return {key:'Noite',label:'Noite',rank:2,icon:'fa-moon'};
    return {key:'Sem preferência',label:'Sem preferência',rank:3,icon:'fa-clock'};
  }
  function adminGroupLabel(value){
    const raw=String(value||'').trim();if(!raw||raw==='A definir')return 'Grupo a definir';if(raw==='Livre')return 'Grupo Livre';const groups=raw.split('+').map(item=>item.trim()).filter(Boolean);return groups.length>1?`Grupos ${groups.join(' + ')}`:`Grupo ${groups[0]||raw}`;
  }
  function decorateAdminActivityRow(row,session){
    if(!row||!session)return;const activity=session.activity||{},description=session.activityDescription||activity.description||'',notes=session.notes||activity.notes||'',materials=session.materials||activity.materials||'',period=normalizedPeriod(activityPeriodValue(session,activity)),duration=Number(session.duration||activity.duration)||0,name=activity.name||session.activityName||'Atividade',group=adminGroupLabel(session.groupId||activity.groupId||session.participation||activity.participation),body=row.firstElementChild||row;
    const badges=[...row.querySelectorAll('.planning-session-title .badge')].map(node=>node.outerHTML).join('');const actions=[...body.querySelectorAll(':scope > .approve-change-button,:scope > .admin-session-manage-actions')].map(node=>node.outerHTML).join('');
    const secondary=[];if(notes)secondary.push(`<p class="admin-portal-detail"><strong>${escapeHtml(text('activity.details.notes'))}:</strong> <span data-no-i18n>${escapeHtml(notes)}</span></p>`);if(meaningfulMaterials(materials))secondary.push(`<p class="admin-portal-detail"><strong>${escapeHtml(text('activity.details.materials'))}:</strong> <span data-no-i18n>${escapeHtml(materials)}</span></p>`);
    row.classList.add('admin-portal-activity-card');row.dataset.period=period.key;row.innerHTML=`<div class="admin-portal-activity-main"><div class="admin-portal-activity-head"><div class="admin-portal-activity-title"><h4 data-no-i18n>${escapeHtml(name)}</h4><p>${duration} min • ${escapeHtml(period.label)}</p></div>${badges?`<div class="admin-portal-status">${badges}</div>`:''}</div><div class="admin-portal-group"><i class="fa-solid fa-people-group" aria-hidden="true"></i><strong>${escapeHtml(group)}</strong></div>${description?`<div class="admin-portal-description"><strong>${escapeHtml(text('portal.activity.infoDescription'))}:</strong> <span data-no-i18n>${escapeHtml(description)}</span></div>`:''}${secondary.length?`<div class="admin-portal-detail-divider" aria-hidden="true"></div><div class="admin-portal-secondary">${secondary.join('')}</div>`:''}${actions?`<div class="admin-portal-actions">${actions}</div>`:''}</div>`;
  }
  function groupAdminRowsByPeriod(container,sessions){
    if(!container)return;const rows=[...container.children].filter(node=>node.classList?.contains('planning-session-row')),buckets=new Map();rows.forEach((row,index)=>{const session=sessions[index],period=normalizedPeriod(activityPeriodValue(session||{},session?.activity||{}));decorateAdminActivityRow(row,session);if(!buckets.has(period.key))buckets.set(period.key,{period,rows:[]});buckets.get(period.key).rows.push(row)});container.replaceChildren();[...buckets.values()].sort((a,b)=>a.period.rank-b.period.rank).forEach(bucket=>{const section=document.createElement('section');section.className='admin-period-section';section.dataset.period=bucket.period.key;const heading=document.createElement('div');heading.className='admin-period-heading';heading.innerHTML=`<i class="fa-solid ${bucket.period.icon}" aria-hidden="true"></i><span>${escapeHtml(bucket.period.label)}</span>`;const list=document.createElement('div');list.className='admin-period-activities';bucket.rows.sort((a,b)=>String(a.querySelector('h4')?.textContent||'').localeCompare(String(b.querySelector('h4')?.textContent||''),'pt-BR',{sensitivity:'base'})).forEach(row=>list.appendChild(row));section.append(heading,list);container.appendChild(section)})
  }
  adminPlanningDayCard=function(p,day){
    const html=baseAdminPlanningDayCard(p,day),template=document.createElement('template');template.innerHTML=html;template.content.querySelectorAll('.planning-note-button').forEach(button=>button.remove());const container=template.content.querySelector('.planning-day-sessions');groupAdminRowsByPeriod(container,day?.sessions||[]);return template.innerHTML;
  };

  function normalizeContact(value){return window.OleiroServices?.profiles?.normalizeEmergencyContact?.(value)||{name:String(value?.name||'').trim(),relationship:String(value?.relationship||'').trim(),phone:String(value?.phone||'').trim()}}
  function participantName(p,index){return (Array.isArray(p?.participantNames)?p.participantNames[index]:null)||p?.participantProfiles?.[index]?.name||p?.name||`Participante ${index+1}`}
  function initials(name){return String(name||'V').split(/\s+/).filter(Boolean).map(part=>part[0]).slice(0,2).join('').toUpperCase()}
  function enhanceEmergencyCard(p){
    const card=modalRoot.querySelector('.account-emergency-card');if(!card||!p?.emergencyProfilesLoaded)return;const count=Math.max(Number(p.participantCount)||1,(p.participantUids||[]).length,(p.participantNames||[]).length),rows=Array.from({length:count},(_,index)=>{const profile=p.participantProfiles?.[index]||{},contact=normalizeContact(profile.emergencyContact),name=participantName(p,index),has=!!(contact.name||contact.relationship||contact.phone),label=has?text('emergency.edit'):text('emergency.add');return `<div class="emergency-admin-person"><div class="avatar emergency-admin-avatar">${escapeHtml(initials(name))}</div><div class="emergency-admin-main"><strong class="emergency-admin-owner">${escapeHtml(name)}</strong><div class="emergency-admin-details"><div><span>${escapeHtml(text('emergency.name'))}</span><strong>${escapeHtml(contact.name||text('emergency.none'))}</strong></div><div><span>${escapeHtml(text('emergency.relationship'))}</span><strong>${escapeHtml(contact.relationship||text('emergency.none'))}</strong></div><div><span>${escapeHtml(text('emergency.phone'))}</span><strong>${escapeHtml(contact.phone||text('emergency.none'))}</strong></div></div></div><button class="icon-btn emergency-admin-edit" type="button" onclick="openVolunteerEmergencyEditor('${safe(p.id)}',${index})" aria-label="${escapeHtml(label)}" title="${escapeHtml(label)}"><i class="fa-solid fa-pen"></i></button></div>`}).join('');card.innerHTML=`<div class="account-card-head"><div><span class="eyebrow">${escapeHtml(text('emergency.title'))}</span></div></div><div class="emergency-admin-list">${rows}</div>`;
  }
  renderPersonModal=function(p,tab='plan'){const result=baseRenderPersonModal(p,tab);if((tab==='account'||modalRoot.dataset.personTab==='account')&&p)enhanceEmergencyCard(p);return result};

  window.openAdminPlanningActivity=openAdminPlanningActivity;window.openAdminEditPlanningSession=openAdminEditPlanningSession;window.saveAdminPlanningActivity=saveAdminPlanningActivity;window.adminPlanningDayCard=adminPlanningDayCard;window.renderPersonModal=renderPersonModal;
})();
