function managerGreeting(){
  const hour=new Date().getHours();const lang=typeof currentLanguage==='function'?currentLanguage():'pt';
  if(hour<12)return lang==='en'?'Good morning':lang==='es'?'Buenos días':'Bom dia';
  if(hour<18)return lang==='en'?'Good afternoon':lang==='es'?'Buenas tardes':'Boa tarde';
  return lang==='en'?'Good evening':lang==='es'?'Buenas noches':'Boa noite';
}
function openTodayAgenda(){state.agendaAnchor=_oleiroToday;state.selectedDate=_oleiroToday;state.agendaFrom=_oleiroToday;state.agendaTo=_oleiroToday;navigateManager('agenda')}
function dashboardCount(status){return (state.candidates||[]).filter(p=>p.status===status).length}
function movementDaysLabel(iso){if(!iso)return '';const diff=Math.ceil((new Date(iso+'T12:00:00')-new Date(_oleiroToday+'T12:00:00'))/86400000);return diff===0?'hoje':diff===1?'amanhã':diff>1?`em ${diff} dias`:diff===-1?'ontem':`${Math.abs(diff)} dias atrás`}
function nextMovements(field,limit=3){return (state.candidates||[]).filter(p=>p.status==='approved'&&!p.inactive&&p[field]&&p[field]>=_oleiroToday).sort((a,b)=>a[field].localeCompare(b[field])).slice(0,limit)}
function movementList(rows,field){return rows.length?rows.map(p=>miniMove(p.name,fmtDate(p[field],true),movementDaysLabel(p[field]))).join(''):'<div class="empty">Nenhuma movimentação prevista.</div>'}
function managerHome(){
  const todaySessions=getSessions(_oleiroToday),arrivals=nextMovements('from'),departures=nextMovements('to'),attention=(state.notifications||[]).length;
  return `<section class="hero"><div class="eyebrow" style="color:#d9eadf">Gestão</div><h1>${managerGreeting()}</h1><p class="muted">Veja o que precisa da sua atenção e o que acontece hoje na Casa.</p><div class="hero-actions"><button class="btn btn-light" onclick="navigateManager('volunteer')"><i class="fa-solid fa-users"></i>Voluntariado</button><button class="btn btn-outline" style="border-color:rgba(255,255,255,.28);color:white" onclick="openTodayAgenda()"><i class="fa-regular fa-calendar"></i>Ver agenda</button></div></section>
  <section class="section"><div class="section-head"><div><h2>Pendências</h2><p>Ações que merecem atenção</p></div></div><div class="grid-2 grid-md-4 pending-grid">${metric(dashboardCount('analysis'),'fa-clipboard-check','Em análise',"state.candidateFilter='analysis';navigateManager('volunteer')")}${metric(dashboardCount('adjustments'),'fa-rotate','Ajustes',"state.candidateFilter='adjustments';navigateManager('volunteer')")}${metric(arrivals.length,'fa-plane-arrival','Chegadas',"openOccupancyCalendar()")}${metric(attention,'fa-triangle-exclamation','Atenção','openNotifications()')}</div></section>
  <section class="section"><div class="section-head"><div><h2>Hoje na Casa</h2><p>${longDate(_oleiroToday)}</p></div><button class="btn btn-soft" onclick="openTodayAgenda()">Agenda</button></div><div class="list">${todaySessions.length?todaySessions.map(s=>agendaItem(s.activity.time,s.activity.name,s.activity.owner,s.group,s.status)).join(''):'<div class="empty">Nenhuma atividade prevista para hoje.</div>'}</div></section>
  <section class="section"><div class="section-head"><div><h2>Próximas movimentações</h2><p>Chegadas e saídas confirmadas</p></div></div><div class="grid-2"><div class="card"><span class="eyebrow">Chegadas</span><div style="margin-top:10px" class="list">${movementList(arrivals,'from')}</div></div><div class="card"><span class="eyebrow">Saídas</span><div style="margin-top:10px" class="list">${movementList(departures,'to')}</div></div></div></section>`;
}
function metric(n,icon,label,action){return `<button class="card metric" style="border:1px solid var(--border);color:var(--text)" onclick="${action}"><div class="metric-icon"><i class="fa-solid ${icon}"></i></div><div><strong>${n}</strong><span style="display:block">${label}</span></div></button>`}
function agendaItem(time,name,person,group,status){const [l,t]=statusMeta(status);return `<div class="list-item"><div class="time-box single"><strong>${time||'—'}</strong></div><div class="item-main"><h3>${escapeHtml(name||'Atividade')}</h3><p>${escapeHtml(person||'Voluntário')} • ${escapeHtml(group||'A definir')}</p><div class="item-meta">${badge(l,t)}</div></div></div>`}
function miniMove(name,date,label){return `<div style="padding:8px 0;border-bottom:1px solid var(--border)"><strong style="font-size:.7rem">${escapeHtml(name||'Voluntário')}</strong><div style="font-size:.61rem;color:var(--muted)">${date} • ${label}</div></div>`}
