function groupUnits(){return state.units||[]}
function groupUnitSelector(){
  const units=groupUnits(),selected=String(state.groupUnitId||'rodeio');
  if(!units.length)return '<div class="notice"><i class="fa-solid fa-circle-info"></i><div>Nenhuma unidade cadastrada.</div></div>';
  return `<div class="field" style="margin-bottom:14px"><label for="managerGroupUnit">Unidade</label><select id="managerGroupUnit" class="select" onchange="changeManagerGroupUnit(this.value)">${units.map(unit=>`<option value="${escapeHtml(String(unit.id))}" ${String(unit.id)===selected?'selected':''}>${escapeHtml((unit.name||String(unit.id).replace(/^./,c=>c.toUpperCase()))+(unit.active===false?' • inativa':''))}</option>`).join('')}</select><small>Os grupos A/B/C/D e seus integrantes são independentes por unidade. Unidades inativas podem ser preparadas antes da abertura.</small></div>`;
}
function managerGroups(){
  const selector=groupUnitSelector(),selected=String(state.groupUnitId||'rodeio'),unit=groupUnits().find(row=>String(row.id)===selected),unitLabel=unit?.name||selected.replace(/^./,c=>c.toUpperCase());
  if(!state.groupsLoaded||String(state.groupsUnitId||'')!==selected)return `<section class="section compact-page-top">${selector}<div class="empty compact-loading"><i class="fa-solid fa-circle-notch fa-spin"></i>Carregando grupos de ${escapeHtml(unitLabel)}...</div></section>`;
  const rows=state.groups||[];
  return `<section class="section compact-page-top">${selector}<div class="section-title" style="margin-bottom:10px"><div><span class="eyebrow">${escapeHtml(unitLabel)}${unit?.active===false?' • inativa':''}</span><h2>Grupos da unidade</h2></div></div>${rows.length?rows.map(g=>`<details class="group-details"><summary><div class="avatar">${escapeHtml(g.code||g.id)}</div><div class="group-summary-copy"><strong>Grupo ${escapeHtml(g.code||g.id)}</strong><span>${(g.members||[]).length} integrantes • capacidade ${Number(g.capacity||5)}</span></div><i class="fa-solid fa-chevron-down" style="color:var(--muted)"></i></summary><div class="group-members">${(g.members||[]).map(m=>`<div class="member-row"><span class="member-name"><span class="member-dot"></span>${escapeHtml(m)}</span></div>`).join('')||'<div class="empty">Nenhum nome cadastrado.</div>'}<button class="btn btn-outline btn-block" type="button" style="margin-top:10px" onclick='editGroup(${JSON.stringify(String(g.id))})'><i class="fa-solid fa-pen"></i>Editar</button></div></details>`).join(''):'<div class="empty"><i class="fa-solid fa-people-group"></i>Nenhum grupo cadastrado.</div>'}</section>`;
}
function editGroup(id){
  const g=(state.groups||[]).find(x=>String(x.id)===String(id));if(!g)return showToast('Grupo não encontrado.');const members=[...(g.members||[])];
  const unit=(state.units||[]).find(row=>String(row.id)===String(g.unitId||state.groupUnitId||'')),unitLabel=unit?.name||String(g.unitId||state.groupUnitId||'').replace(/^./,c=>c.toUpperCase());
  openModal(`Grupo ${g.code||g.id} • ${unitLabel}`,'Edite capacidade, observação e integrantes desta unidade.',`<div class="form-grid group-edit-form"><div class="field"><label>Capacidade</label><input id="gCap" class="input" type="number" min="1" value="${Number(g.capacity||5)}"></div><div class="field"><label>Observação</label><input id="gNote" class="input" value="${escapeHtml(g.note||'')}" placeholder="Opcional"></div><div class="field"><label>Integrantes</label><div id="groupMemberList" class="group-member-list">${members.map((m,i)=>`<div class="member-row group-member-edit-row"><span class="member-name"><span class="member-dot"></span>${escapeHtml(m)}</span><button class="group-delete-button" type="button" onclick="removeGroupMemberDraft(${i})" aria-label="Excluir"><i class="fa-solid fa-trash"></i></button></div>`).join('')||'<div class="empty">Nenhum nome cadastrado.</div>'}</div></div><div class="field group-new-member"><label>Novo nome</label><div class="group-add-row"><input id="gMember" class="input" placeholder="Nome"><button class="btn btn-soft" type="button" onclick="addGroupMemberDraft()"><i class="fa-solid fa-plus"></i>Adicionar</button></div></div></div>`,`<button class="btn btn-primary btn-block" type="button" onclick="saveGroupConfig(${JSON.stringify(g.id)})">Salvar</button>`);
  modalRoot.dataset.groupId=String(g.id);modalRoot.dataset.groupMembers=JSON.stringify(members);modalRoot.querySelector('.modal')?.classList.add('group-edit-modal');
}
function groupDraftMembers(){try{return JSON.parse(modalRoot.dataset.groupMembers||'[]')}catch{return []}}
function renderGroupDraftMembers(){const list=document.getElementById('groupMemberList');if(!list)return;const members=groupDraftMembers();list.innerHTML=members.map((m,i)=>`<div class="member-row group-member-edit-row"><span class="member-name"><span class="member-dot"></span>${escapeHtml(m)}</span><button class="group-delete-button" type="button" onclick="removeGroupMemberDraft(${i})" aria-label="Excluir"><i class="fa-solid fa-trash"></i></button></div>`).join('')||'<div class="empty">Nenhum nome cadastrado.</div>'}
function removeGroupMemberDraft(index){const members=groupDraftMembers();members.splice(index,1);modalRoot.dataset.groupMembers=JSON.stringify(members);renderGroupDraftMembers()}
function addGroupMemberDraft(){const input=document.getElementById('gMember');const name=input?.value.trim();if(!name)return showToast('Informe um nome.');const members=groupDraftMembers();members.push(name);modalRoot.dataset.groupMembers=JSON.stringify(members);input.value='';renderGroupDraftMembers()}
async function saveGroupConfig(id){const g=(state.groups||[]).find(x=>String(x.id)===String(id));if(!g)return;const patch={capacity:Math.max(1,Number(document.getElementById('gCap')?.value)||5),note:document.getElementById('gNote')?.value.trim()||'',members:groupDraftMembers()};try{await window.OleiroServices.groups.update(g.id,patch);Object.assign(g,patch);closeModal();render();showToast('Grupo atualizado.')}catch(error){console.error(error);showToast('Não foi possível salvar o grupo.')}}
