function groupUnits(){return state.units||[]}
function groupUnitSelector(){const units=groupUnits(),selected=String(state.groupUnitId||'rodeio');if(!units.length)return '<div class="notice"><i class="fa-solid fa-circle-info"></i><div>Nenhuma unidade cadastrada.</div></div>';return `<div class="field" style="margin-bottom:14px"><label for="managerGroupUnit">Unidade</label><select id="managerGroupUnit" class="select" onchange="changeManagerGroupUnit(this.value)">${units.map(unit=>`<option value="${escapeHtml(String(unit.id))}" ${String(unit.id)===selected?'selected':''}>${escapeHtml((unit.name||String(unit.id).replace(/^./,c=>c.toUpperCase()))+(unit.active===false?' • inativa':''))}</option>`).join('')}</select><small>Os grupos e seus integrantes são independentes por unidade.</small></div>`}
function managerGroups(){
  const selector=groupUnitSelector(),selected=String(state.groupUnitId||'rodeio'),unit=groupUnits().find(row=>String(row.id)===selected),unitLabel=unit?.name||selected.replace(/^./,c=>c.toUpperCase());
  if(!state.groupsLoaded||String(state.groupsUnitId||'')!==selected)return `<div class="r61-page"><div class="r61-page-heading"><div><span class="r61-kicker">Organização da Casa</span><h1>Grupos</h1><p>Estruture capacidade e integrantes por unidade.</p></div></div><div class="r61-panel">${selector}<div class="empty compact-loading"><i class="fa-solid fa-circle-notch fa-spin"></i>Carregando grupos de ${escapeHtml(unitLabel)}...</div></div></div>`;
  const rows=state.groups||[];const cards=rows.map(g=>{const members=g.members||[],code=g.code||g.id;return `<article class="r61-group-card"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><span class="r61-group-code">${escapeHtml(code)}</span><span style="font-size:.58rem;color:var(--r61-muted);text-align:right">${members.length}/${Number(g.capacity||5)}<br>integrantes</span></div><h3>Grupo ${escapeHtml(code)}</h3><p>${escapeHtml(g.note||'Sem observações adicionais.')}</p><div class="r61-members">${members.length?members.map(m=>`<span class="r61-member">${escapeHtml(m)}</span>`).join(''):'<span class="r61-member">Nenhum integrante</span>'}</div><button class="btn btn-outline btn-block" type="button" onclick='editGroup(${JSON.stringify(String(g.id))})'><i class="fa-solid fa-pen"></i>Editar grupo</button></article>`}).join('');
  return `<div class="r61-page"><div class="r61-page-heading"><div><span class="r61-kicker">Organização da Casa</span><h1>Grupos</h1><p>Capacidade, integrantes e composição operacional por unidade.</p></div></div><div class="r61-panel" style="margin-bottom:16px">${selector}</div>${rows.length?`<div class="r61-group-grid">${cards}</div>`:'<div class="empty"><i class="fa-solid fa-people-group"></i>Nenhum grupo cadastrado.</div>'}</div>`;
}
function editGroup(id){const g=(state.groups||[]).find(x=>String(x.id)===String(id));if(!g)return showToast('Grupo não encontrado.');const members=[...(g.members||[])];const unit=(state.units||[]).find(row=>String(row.id)===String(g.unitId||state.groupUnitId||'')),unitLabel=unit?.name||String(g.unitId||state.groupUnitId||'').replace(/^./,c=>c.toUpperCase());openModal(`Grupo ${g.code||g.id} • ${unitLabel}`,'Edite capacidade, observação e integrantes desta unidade.',`<div class="form-grid group-edit-form"><div class="field"><label>Capacidade</label><input id="gCap" class="input" type="number" min="1" value="${Number(g.capacity||5)}"></div><div class="field"><label>Observação</label><input id="gNote" class="input" value="${escapeHtml(g.note||'')}" placeholder="Opcional"></div><div class="field"><label>Integrantes</label><div id="groupMemberList" class="group-member-list">${members.map((m,i)=>`<div class="member-row group-member-edit-row"><span class="member-name"><span class="member-dot"></span>${escapeHtml(m)}</span><button class="group-delete-button" type="button" onclick="removeGroupMemberDraft(${i})" aria-label="Excluir"><i class="fa-solid fa-trash"></i></button></div>`).join('')||'<div class="empty">Nenhum nome cadastrado.</div>'}</div></div><div class="field group-new-member"><label>Novo nome</label><div class="group-add-row"><input id="gMember" class="input" placeholder="Nome"><button class="btn btn-soft" type="button" onclick="addGroupMemberDraft()"><i class="fa-solid fa-plus"></i>Adicionar</button></div></div></div>`,`<button class="btn btn-primary btn-block" type="button" onclick="saveGroupConfig(${JSON.stringify(g.id)})">Salvar</button>`);modalRoot.dataset.groupId=String(g.id);modalRoot.dataset.groupMembers=JSON.stringify(members);modalRoot.querySelector('.modal')?.classList.add('group-edit-modal')}
function groupDraftMembers(){try{return JSON.parse(modalRoot.dataset.groupMembers||'[]')}catch{return []}}
function renderGroupDraftMembers(){const list=document.getElementById('groupMemberList');if(!list)return;const members=groupDraftMembers();list.innerHTML=members.map((m,i)=>`<div class="member-row group-member-edit-row"><span class="member-name"><span class="member-dot"></span>${escapeHtml(m)}</span><button class="group-delete-button" type="button" onclick="removeGroupMemberDraft(${i})" aria-label="Excluir"><i class="fa-solid fa-trash"></i></button></div>`).join('')||'<div class="empty">Nenhum nome cadastrado.</div>'}
function removeGroupMemberDraft(index){const members=groupDraftMembers();members.splice(index,1);modalRoot.dataset.groupMembers=JSON.stringify(members);renderGroupDraftMembers()}
function addGroupMemberDraft(){const input=document.getElementById('gMember');const name=input?.value.trim();if(!name)return showToast('Informe um nome.');const members=groupDraftMembers();members.push(name);modalRoot.dataset.groupMembers=JSON.stringify(members);input.value='';renderGroupDraftMembers()}
async function saveGroupConfig(id){const g=(state.groups||[]).find(x=>String(x.id)===String(id));if(!g)return;const patch={capacity:Math.max(1,Number(document.getElementById('gCap')?.value)||5),note:document.getElementById('gNote')?.value.trim()||'',members:groupDraftMembers()};try{await window.OleiroServices.groups.update(g.id,patch);Object.assign(g,patch);closeModal();render();showToast('Grupo atualizado.')}catch(error){console.error(error);showToast('Não foi possível salvar o grupo.')}}
