/* Estado atual do produto Admin: UX estável e orçamento de leituras do Firestore. */
(function productCurrentAdmin(){
  const SCHEDULE_READ_TTL=5*60*1000;
  const APPLICATION_READ_TTL=2*60*1000;
  const PLAN_REVIEW_TTL=60*1000;
  const PLAN_APPROVED_TTL=30*1000;
  const scheduleBudget=new Map();
  let applicationsBudgetAt=Date.now();
  const candidateReadAt=new Map();

  function safe(value){return encodeURIComponent(String(value??''))}
  function planHours(p){const cache=typeof candidatePlanningCache==='function'?candidatePlanningCache(p.id):null;const minutes=(cache?.sessions||[]).reduce((sum,row)=>sum+(Number(row.duration)||Number(row.activity?.duration)||60),0);if(!cache)return null;const h=Math.floor(minutes/60),m=minutes%60;return m?`${h}h${String(m).padStart(2,'0')}`:`${h}h`}
  function stayMonths(start,end){if(!start||!end)return [];const from=new Date(`${start}T12:00:00`),to=new Date(`${end}T12:00:00`),out=[];let y=from.getFullYear(),m=from.getMonth(),ey=to.getFullYear(),em=to.getMonth();while(y<ey||(y===ey&&m<=em)){out.push(`${y}-${String(m+1).padStart(2,'0')}`);m++;if(m===12){m=0;y++}}return out}
  function nextDateLimit(){return addDays(_oleiroToday,30)}

  /* Evita reler a mesma agenda a cada Home/Agenda/foco do navegador. Uma mutação local
     continua invalidando o cache explicitamente. */
  const baseHydrateManagerSchedule=hydrateManagerSchedule;
  hydrateManagerSchedule=async function(from=_oleiroToday,to=_oleiroToday,options={}){
    const unitId=options.unitId||'all',key=`${from}|${to}|${unitId}`,cached=scheduleBudget.get(key);
    if(!options.hard&&cached&&Date.now()-cached.at<SCHEDULE_READ_TTL){state.sessions=cached.rows;state.activities=[];state.scheduleFrom=from;state.scheduleTo=to;return cached.rows}
    const rows=await baseHydrateManagerSchedule(from,to,{...options,force:false});scheduleBudget.set(key,{at:Date.now(),rows:rows||[]});return rows||[];
  };
  const baseInvalidateManagerScheduleCache=invalidateManagerScheduleCache;
  invalidateManagerScheduleCache=function(){scheduleBudget.clear();return baseInvalidateManagerScheduleCache()};

  const baseRefreshManagerApplications=refreshManagerApplications;
  refreshManagerApplications=async function(options={}){
    if(!options.hard&&Date.now()-applicationsBudgetAt<APPLICATION_READ_TTL)return state.candidates||[];
    const rows=await baseRefreshManagerApplications({force:true});applicationsBudgetAt=Date.now();return rows;
  };

  /* Próximas movimentações: somente os próximos 30 dias. */
  nextMovements=function(field,limit=3){const end=nextDateLimit();return (state.candidates||[]).filter(p=>p.status==='approved'&&!p.inactive&&p[field]&&p[field]>=_oleiroToday&&p[field]<=end).sort((a,b)=>a[field].localeCompare(b[field])).slice(0,limit)};

  /* Navegação Admin: Grupos vai para Menu; Ocupação mensal fica fixa. */
  managerNav=function(){
    const item=(id,icon,label,action,active=false)=>`<button class="nav-btn ${active?'active':''}" onclick="${action}"><i class="fa-solid ${icon}"></i><span>${label}</span></button>`;
    return `<nav class="bottom-nav">${item('home','fa-house','Início',"navigateManager('home')",state.managerPage==='home')}${item('volunteer','fa-users','Voluntariado',"navigateManager('volunteer')",state.managerPage==='volunteer')}${item('agenda','fa-calendar-days','Agenda',"navigateManager('agenda')",state.managerPage==='agenda')}${item('occupancy','fa-bed','Ocupação','openOccupancyCalendar()',false)}${item('menu','fa-bars','Menu',"navigateManager('menu')",state.managerPage==='menu')}</nav>`;
  };

  managerMenu=function(){return `<section class="section menu-page-clean"><div class="menu-list">${menuLink('fa-people-group','Grupos','Grupos A, B, C, D e participação livre',"navigateManager('groups')")}${menuLink('fa-circle-info','Informações do portal','Conteúdo consultado pelos voluntários',"openPortalInfo()")}${menuLink('fa-building','Unidades','Configuração das unidades',"openUnits()")}${menuLink('fa-clock','Rotina-base','Horários de referência da comunidade',"openRoutine()")}${menuLink('fa-user','Minha conta','Dados da sessão autenticada',"openMyAccount()")}${menuLink('fa-right-from-bracket','Sair','Encerrar sessão neste dispositivo','logout()')}</div></section>`};

  openMyAccount=function(){const session=state.currentSession||{};openModal('Minha conta','',`<div class="admin-account-card"><div class="admin-account-row"><span class="admin-account-icon"><i class="fa-regular fa-envelope"></i></span><div><small>Email</small><strong>${escapeHtml(session.email||'—')}</strong></div></div><div class="admin-account-row"><span class="admin-account-icon"><i class="fa-solid fa-user-shield"></i></span><div><small>Perfil</small><strong>Administrador</strong></div></div></div>`)};

  /* País como lista padronizada. O texto selecionado continua sendo persistido nos mesmos
     campos participantCountries/country já utilizados pelo restante do app. */
  function countryOptions(){
    let display=null;try{display=new Intl.DisplayNames(['pt-BR'],{type:'region'})}catch{}
    const rows=[];for(let a=65;a<=90;a++)for(let b=65;b<=90;b++){const code=String.fromCharCode(a,b);if(['ZZ','EU','UN','XA','XB'].includes(code))continue;let name='';try{name=display?.of(code)||''}catch{}if(name&&name!==code)rows.push(name)}
    return [...new Set(rows)].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join('');
  }
  const countrySelectOptions=countryOptions();
  candidateParticipantFields=function(index,{optional=false}={}){const n=Number(index);return `<div class="card candidate-participant-card" id="ncParticipant${n}" ${optional?'hidden':''}><div class="candidate-participant-title"><strong>Participante ${n}</strong></div><div class="form-grid" style="margin-top:10px"><div class="field"><label for="ncName${n}">Nome completo</label><input id="ncName${n}" class="input" autocomplete="name" placeholder="Nome completo" oninput="syncNewCandidateSubmit()"></div><div class="field"><label for="ncEmail${n}">Email</label><input id="ncEmail${n}" class="input" type="email" autocomplete="email" placeholder="email@exemplo.com" oninput="syncNewCandidateSubmit()"></div><div class="field-row"><div class="field"><label for="ncPhone${n}">WhatsApp</label><input id="ncPhone${n}" class="input" type="tel" autocomplete="tel" placeholder="+55 ..."></div><div class="field"><label for="ncCountry${n}">País</label><select id="ncCountry${n}" class="select" autocomplete="country-name"><option value="">Selecione o país</option>${countrySelectOptions}</select></div></div><div class="field"><label for="ncLanguage${n}">Idioma do email</label><select id="ncLanguage${n}" class="select"><option value="en">English</option><option value="pt">Português</option><option value="es">Español</option></select></div></div></div>`};

  /* Recusado já implica acesso inativo; não repetir duas tags. */
  personCompact=function(p){const [label,type]=statusMeta(p.status),meta=p.status==='pending'?candidateDeadlineMeta(p):null,extra=meta?`<div class="candidate-deadline-mini"><i class="fa-regular fa-clock"></i>${meta.label}</div>`:'',inactive=p.inactive&&p.status!=='rejected'?badge('Inativo','danger'):'',period=p.from&&p.to?`${fmtDate(p.from,true)}–${fmtDate(p.to,true)}`:'Período não informado',id=candidateActionArg(p.id);return `<div class="list-item clickable" onclick="openPerson(decodeURIComponent('${id}'))"><div class="avatar">${String(p.name||'V').split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div class="item-main"><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.country||'—')} • ${escapeHtml(p.unit||'—')} • ${period}</p><div class="item-meta">${badge(label,type)}${inactive}</div>${extra}</div><i class="fa-solid fa-chevron-right" style="color:var(--muted);margin-top:11px"></i></div>`};

  /* Visão geral: atividades + horas são mais úteis que contar sessões. */
  const basePersonTabContent=personTabContent;
  personTabContent=function(p,tab){let html=basePersonTabContent(p,tab);if(tab==='overview'){const hours=planHours(p);html=html.replace(/<span class="stat-pill">\d+ sessões<\/span>/,`<span class="stat-pill">${hours??'—'} planejadas</span>`)}return html};

  /* Abrir candidato usa dados em memória imediatamente. Planejamento só relê sessões quando
     o cache realmente envelheceu; contato só relê quando ainda não foi hidratado. */
  openPerson=async function(id,tab='overview'){
    let p=candidateById(id);if(!p)return;renderPersonModal(p,tab);
    const key=String(p.id),now=Date.now();
    if(!p.profileHydrated&&window.OleiroServices?.applications?.getById&&now-(candidateReadAt.get(key)||0)>APPLICATION_READ_TTL){candidateReadAt.set(key,now);window.OleiroServices.applications.getById(p.id).then(fresh=>{if(!fresh)return;const cache=candidatePlanningCache(p.id);if(cache){fresh.activities=cache.activities.length;fresh.sessions=cache.sessions.length}const index=state.candidates.findIndex(row=>String(row.id)===key);if(index>=0)state.candidates[index]=fresh;p=fresh;if(modalRoot.dataset.personId===key)renderPersonModal(fresh,modalRoot.dataset.personTab||tab)}).catch(console.error)}
    const cache=candidatePlanningCache(p.id),ttl=p.status==='approved'?PLAN_APPROVED_TTL:PLAN_REVIEW_TTL,needsPlan=tab==='plan'||(['analysis','adjustments'].includes(p.status)&&!cache);
    if(needsPlan){if(cache){applyCandidatePlanningCache(p.id,cache);renderPersonModal(p,tab)}if(!cache||Date.now()-(cache.at||0)>ttl){hydrateCandidatePlanning(p.id,{force:true}).then(freshCache=>{const current=candidateById(p.id);if(current&&freshCache){current.activities=freshCache.activities.length;current.sessions=freshCache.sessions.length}if(modalRoot.dataset.personId===key)renderPersonModal(current||p,modalRoot.dataset.personTab||tab)}).catch(error=>{console.error(error);if(tab==='plan')showToast('Não foi possível carregar o planejamento.')})}}
  };

  /* Detalhe da atividade volta exatamente ao dia que estava aberto. */
  function restorePlanningDay(personId,date){const p=candidateById(personId);if(!p)return closeModal();renderPersonModal(p,'plan');requestAnimationFrame(()=>{const target=modalRoot.querySelector(`details[data-plan-date="${CSS.escape(String(date||''))}"]`);if(target){target.open=true;target.scrollIntoView({block:'center'})}})}
  openAdminActivityInfo=function(name,description,notes,date){const personId=String(modalRoot.dataset.personId||state.currentPlanningApplicationId||''),n=decodeURIComponent(name||''),d=decodeURIComponent(description||''),o=decodeURIComponent(notes||''),day=decodeURIComponent(date||'');const sections=[];if(d)sections.push(`<div class="activity-info-block"><strong>Descrição</strong><p>${escapeHtml(d)}</p></div>`);if(o)sections.push(`<div class="activity-info-block"><strong>Observações</strong><p>${escapeHtml(o)}</p></div>`);openModal(n||'Informações da atividade','',`<div class="activity-info-compact">${sections.join('')||'<div class="empty">Sem informações adicionais.</div>'}</div>`);const close=modalRoot.querySelector('.modal-close');if(close)close.onclick=()=>restorePlanningDay(personId,day);const head=modalRoot.querySelector('.modal-head');if(head&&close){const back=document.createElement('button');back.className='modal-back-button';back.type='button';back.innerHTML='<i class="fa-solid fa-arrow-left"></i><span>Voltar</span>';back.onclick=()=>restorePlanningDay(personId,day);head.insertBefore(back,head.firstChild)}const backdrop=modalRoot.querySelector('.modal-backdrop');if(backdrop)backdrop.onclick=e=>{if(e.target===backdrop)restorePlanningDay(personId,day)}};

  function compactDay(date){try{return new Intl.DateTimeFormat(typeof currentLocale==='function'?currentLocale():'pt-BR',{day:'2-digit',month:'2-digit'}).format(new Date(`${date}T12:00:00`))}catch{return fmtDate(date,true)}}
  function weekday(date){try{return new Intl.DateTimeFormat(typeof currentLocale==='function'?currentLocale():'pt-BR',{weekday:'short'}).format(new Date(`${date}T12:00:00`)).replace('.','').toLowerCase()}catch{return dayName(date).slice(0,3).toLowerCase()}}
  function dayHours(day){const m=(day.sessions||[]).reduce((s,row)=>s+(Number(row.duration||row.activity?.duration)||0),0),h=Math.floor(m/60),r=m%60;return h?(r?`${h}h${String(r).padStart(2,'0')}`:`${h}h`):`${r}min`}
  adminPlanningDayCard=function(p,day){const adjustment=candidateDayAdjustment(p,day.date),canAdjust=['analysis','adjustments'].includes(p.status),id=safe(p.id),dateArg=safe(day.date);return `<details class="card planning-day-card" data-plan-date="${escapeHtml(day.date)}"><summary class="planning-day-head"><div class="planning-day-date"><strong>${compactDay(day.date)} ${weekday(day.date)}</strong>${adjustment?'<span class="badge warning">Reajustar</span>':''}</div><div class="planning-day-total"><strong>${dayHours(day)}</strong><i class="fa-solid fa-chevron-down"></i></div></summary><div class="planning-day-content">${adjustment?`<div class="day-adjustment-note"><i class="fa-solid fa-circle-info"></i><span>${escapeHtml(adjustment.note||'Ajuste solicitado pela equipe.')}</span></div>`:''}<div class="planning-day-sessions">${day.sessions.map(session=>{const a=session.activity||{},description=session.activityDescription||a.description||'',notes=session.notes||a.notes||'',hasInfo=!!(description||notes),group=session.groupId&&session.groupId!=='A definir'?` • Grupo ${escapeHtml(session.groupId)}`:'',change=session.status==='change_requested';return `<div class="planning-session-row ${change?'has-change-request':''}"><div><div class="planning-session-title"><strong>${escapeHtml(a.name||session.activityName||'Atividade')}</strong>${hasInfo?`<button class="planning-note-button" type="button" aria-label="Ver informações" onclick="openAdminActivityInfo('${safe(a.name||session.activityName||'Atividade')}','${safe(description)}','${safe(notes)}','${dateArg}')"><i class="fa-solid fa-circle-info"></i></button>`:''}${change?'<span class="badge warning">Mudança solicitada</span>':''}</div><span>${Number(session.duration||a.duration)||0} min • ${escapeHtml(activityPeriodValue(session,a))}${group}</span>${change?`<button class="btn btn-soft approve-change-button" type="button" onclick="approveVolunteerChange('${safe(session.id)}','${safe(p.id)}')"><i class="fa-solid fa-check"></i>Aprovar mudança</button>`:''}</div></div>`}).join('')}</div>${canAdjust?`<div class="planning-day-adjust-action"><button class="btn btn-soft" type="button" onclick="requestDayAdjust(decodeURIComponent('${id}'),decodeURIComponent('${dateArg}'))"><i class="fa-solid fa-pen"></i>Solicitar ajuste neste dia</button></div>`:''}</div></details>`};

  /* Uma nova rodada de ajuste confirma o status atual da candidatura com uma única leitura,
     somente no momento em que o gestor realmente solicita o ajuste. */
  saveDayAdjustment=async function(id,date){let p=candidateById(id),note=document.getElementById('dayAdjustNote')?.value.trim()||'',button=document.getElementById('r4DayAdjustSave');if(!p||!note)return showToast('Informe o ajuste solicitado.');if(button){button.disabled=true;button.innerHTML='<i class="fa-solid fa-circle-notch fa-spin"></i> Salvando...'}try{if(p.status==='adjustments'&&window.OleiroServices?.applications?.getById){const fresh=await window.OleiroServices.applications.getById(p.id,{enrichProfiles:false});if(fresh){const index=state.candidates.findIndex(row=>String(row.id)===String(p.id));if(index>=0)state.candidates[index]={...p,...fresh};p=state.candidates[index]||{...p,...fresh}}}const next=p.status==='analysis'?{}:{...(p.dayAdjustments||{})};next[date]={note,status:'requested',requestedAt:new Date()};const deadline=new Date();deadline.setDate(deadline.getDate()+7);await window.OleiroServices.applications.update(p.id,{dayAdjustments:next,status:'adjustments',active:true,planningDeadlineAt:deadline});p.status='adjustments';p.dayAdjustments=next;p.pendingUntil=deadline.toISOString();renderPersonModal(p,'plan');showToast('Ajuste solicitado para este dia.')}catch(error){console.error(error);showToast(error?.message||'Não foi possível solicitar o ajuste.');if(button?.isConnected){button.disabled=false;button.textContent='Solicitar ajuste'}}};

  /* Alterar período usa o planejamento já carregado. Com cache: zero leituras extras;
     sem cache: uma consulta de sessões. Chegada e saída permanecem dias sem atividade. */
  async function currentPlanCache(p){let cache=candidatePlanningCache(p.id);if(!cache)cache=await hydrateCandidatePlanning(p.id,{force:true});return cache}
  async function commitStayDates(p,from,to,cache){const context=await window.OleiroServices.firebase(),{firestore}=context.modules,sessions=cache?.sessions||[],outside=sessions.filter(row=>!row.date||row.date<=from||row.date>=to),outsideIds=new Set(outside.map(row=>String(row.id))),remaining=sessions.filter(row=>!outsideIds.has(String(row.id))),allActivityIds=new Set(sessions.map(row=>String(row.activityId||'')).filter(Boolean)),remainingActivityIds=new Set(remaining.map(row=>String(row.activityId||'')).filter(Boolean)),batch=firestore.writeBatch(context.db),now=firestore.serverTimestamp();outside.forEach(row=>batch.delete(firestore.doc(context.db,'activity_sessions',String(row.id))));allActivityIds.forEach(id=>{if(!remainingActivityIds.has(id))batch.delete(firestore.doc(context.db,'activities',id))});batch.update(firestore.doc(context.db,'applications',String(p.id)),{stayStart:from,stayEnd:to,stayMonths:stayMonths(from,to),sessionCount:remaining.length,activityCount:remainingActivityIds.size,updatedAt:now});await batch.commit();cache.sessions=remaining;cache.activities=(cache.activities||[]).filter(a=>remainingActivityIds.has(String(a.id)));cache.activities.forEach(a=>a.dates=remaining.filter(s=>String(s.activityId)===String(a.id)).map(s=>s.date).filter(Boolean).sort());cache.at=Date.now();return {removedSessions:outside.length,sessionCount:remaining.length,activityCount:remainingActivityIds.size}}
  saveStayDates=async function(id){const p=candidateById(id),from=document.getElementById('editStayFrom')?.value||'',to=document.getElementById('editStayTo')?.value||'',button=document.getElementById('stayDateSaveButton');if(!p||!from||!to||to<from)return showToast('Confira as datas informadas.');if(button){button.disabled=true;button.innerHTML='<i class="fa-solid fa-circle-notch fa-spin"></i> Verificando...'}try{const cache=await currentPlanCache(p),outside=(cache?.sessions||[]).filter(row=>!row.date||row.date<=from||row.date>=to);if(outside.length){const dates=[...new Set(outside.map(row=>row.date).filter(Boolean))].sort(),idArg=safe(id),fromArg=safe(from),toArg=safe(to);state.pendingStayChange={id:String(id),from,to,cache};openModal('Confirmar alteração',`${outside.length} ${outside.length===1?'sessão será removida':'sessões serão removidas'}.`,`<div class="notice warning"><i class="fa-solid fa-triangle-exclamation"></i><div>Chegada e saída são dias sem atividade. As atividades em ${dates.map(d=>fmtDate(d,true)).join(', ')} serão removidas para manter o período consistente.</div></div>`,`<div class="confirm-delete-actions"><button class="btn btn-outline" type="button" onclick="openStayDateEditor(decodeURIComponent('${idArg}'))">Voltar</button><button id="confirmStayDateChange" class="btn btn-danger" type="button" onclick="confirmStayDatesFast(decodeURIComponent('${idArg}'),decodeURIComponent('${fromArg}'),decodeURIComponent('${toArg}'))">Alterar e remover</button></div>`);return}await window.confirmStayDatesFast(String(id),from,to,cache)}catch(error){console.error(error);showToast(error?.message||'Não foi possível alterar as datas.')}finally{if(button?.isConnected){button.disabled=false;button.textContent='Salvar período'}}};
  window.confirmStayDatesFast=async function(id,from,to,providedCache=null){const p=candidateById(id),button=document.getElementById('confirmStayDateChange');if(!p)return;if(button){button.disabled=true;button.innerHTML='<i class="fa-solid fa-circle-notch fa-spin"></i> Alterando...'}try{const cache=providedCache||state.pendingStayChange?.cache||await currentPlanCache(p),result=await commitStayDates(p,from,to,cache);p.from=from;p.to=to;p.stayStart=from;p.stayEnd=to;p.sessions=result.sessionCount;p.activities=result.activityCount;state.candidatePlanningCache[String(p.id)]=cache;applyCandidatePlanningCache(p.id,cache);invalidateManagerScheduleCache?.();renderPersonModal(p,'stay');showToast(result.removedSessions?`Datas alteradas. ${result.removedSessions} sessões removidas.`:'Datas da estadia alteradas.')}catch(error){console.error(error);showToast(error?.message||'Não foi possível alterar as datas.');if(button?.isConnected){button.disabled=false;button.textContent='Alterar e remover'}}finally{state.pendingStayChange=null}};

  /* Aprovação dá feedback imediatamente no próprio botão. */
  const baseApproveCandidate=approveCandidate;
  approveCandidate=async function(id){const buttons=[...modalRoot.querySelectorAll('button')].filter(button=>/^Aprovar(?: planejamento)?$/i.test((button.textContent||'').trim()));buttons.forEach(button=>{button.disabled=true;button.dataset.oldText=button.innerHTML;button.innerHTML='<i class="fa-solid fa-circle-notch fa-spin"></i> Aprovando...'});try{return await baseApproveCandidate(id)}finally{buttons.forEach(button=>{if(button.isConnected){button.disabled=false;button.innerHTML=button.dataset.oldText||'Aprovar'}})}};

  /* Seleção de múltiplos grupos usa o mesmo campo groupId como texto composto, sem migração. */
  openManagerGroupPicker=function(id){const s=managerSessionById(id);if(!s)return;const current=String(s.groupId||'').split('+').map(x=>x.trim()).filter(Boolean),groups=(state.groups||[]).map(g=>String(g.code||g.id)).filter(Boolean),options=[...new Set([...groups,'Livre'])];openModal('Definir grupos','Selecione um ou mais grupos para esta atividade.',`<div class="check-grid multi-group-grid">${options.map(g=>`<label class="check-card"><input type="checkbox" name="managerGroup" value="${escapeHtml(g)}" ${current.includes(g)?'checked':''}><span>${g==='Livre'?'Participação livre':'Grupo '+escapeHtml(g)}</span></label>`).join('')}</div>`,`<button class="btn btn-primary btn-block" type="button" onclick="saveManagerGroups('${safe(id)}')">Salvar grupos</button>`)};
  window.saveManagerGroups=async function(encodedId){const id=decodeURIComponent(encodedId),s=managerSessionById(id);if(!s)return showToast('Sessão não encontrada.');let values=[...document.querySelectorAll('input[name="managerGroup"]:checked')].map(input=>input.value);if(values.includes('Livre'))values=['Livre'];if(!values.length)return showToast('Selecione pelo menos um grupo ou Livre.');const value=values.join(' + ');try{await window.OleiroServices.planning.updateSession(id,{groupId:value});s.groupId=value;invalidateManagerScheduleCache?.();closeModal();render();showToast('Grupos atualizados.')}catch(error){console.error(error);showToast('Não foi possível atualizar os grupos.')}};
  assignGroup=function(activityId,date){const session=realSessionFor(activityId,date);if(!session)return showToast('Sessão não encontrada.');openManagerGroupPicker(session.id)};

  /* Casal é cinza; gênero individual só é usado quando foi realmente cadastrado. */
  occupancyGender=function(p){if(p?.type==='couple'||Number(p?.participantCount)===2)return 'couple';return p?.gender==='male'?'male':p?.gender==='female'?'female':'other'};
  openOccupancyCalendar=function(){const month=occupancyMonthAnchor(),year=month.getFullYear(),monthIndex=month.getMonth(),first=new Date(year,monthIndex,1,12),last=new Date(year,monthIndex+1,0,12),leading=first.getDay(),cells=[];for(let i=0;i<leading;i++)cells.push('<span class="occupancy-day occupancy-blank" aria-hidden="true"></span>');for(let day=1;day<=last.getDate();day++){const d=new Date(year,monthIndex,day,12),iso=occupancyIso(d),people=occupancyPeopleOnDate(iso);cells.push(`<button class="occupancy-day ${iso===_oleiroToday?'today':''} ${people.length?'has-people':''}" type="button" onclick="openOccupancyDay('${iso}')"><strong>${day}</strong><span class="occupancy-dots">${occupancyDots(people)}</span></button>`)}openModal('Ocupação mensal','Voluntários hospedados por dia.',`<div class="occupancy-section"><div class="occupancy-month-nav"><button class="icon-btn" type="button" onclick="shiftOccupancyMonth(-1)" aria-label="Mês anterior"><i class="fa-solid fa-chevron-left"></i></button><strong>${occupancyMonthTitle()}</strong><button class="icon-btn" type="button" onclick="shiftOccupancyMonth(1)" aria-label="Próximo mês"><i class="fa-solid fa-chevron-right"></i></button></div><div class="occupancy-legend"><span><i class="legend-dot male"></i>Homem</span><span><i class="legend-dot female"></i>Mulher</span><span><i class="legend-dot couple"></i>Casal / não informado</span></div><div class="occupancy-weekdays">${occupancyWeekdayLabels().map(x=>`<span>${x}</span>`).join('')}</div><div class="occupancy-calendar">${cells.join('')}</div></div>`);modalRoot.querySelector('.modal')?.classList.add('occupancy-modal')};

  if(state.role==='manager'&&typeof render==='function')render();
})();
