const CANDIDATE_STATUS_OPTIONS=[
  ['all','Todos os status'],['pending','Em preparação'],['analysis','Em análise'],['adjustments','Ajustes'],['meeting','Planejamento aprovado'],['approved','Aprovado'],['rejected','Recusado']
];
const CANDIDATE_PAGE_SIZE=10;
let _candidateSearchTimer=null;
function normalizeCandidateFilter(value){return CANDIDATE_STATUS_OPTIONS.some(([id])=>id===value)?value:'all';}
function managerVolunteers(){
  state.candidateFilter=normalizeCandidateFilter(state.candidateFilter);const search=state.candidateSearch||'';const activeFilters=state.candidateFilter!=='all'||(state.candidateUnit||'all')!=='all';
  return `<section class="section volunteer-list-page compact-page-top"><div class="candidate-tools candidate-tools-compact"><div class="filter-search candidate-search"><i class="fa-solid fa-magnifying-glass"></i><input id="candidateSearch" class="input" type="search" value="${escapeHtml(search)}" placeholder="Buscar voluntário por nome" oninput="updateCandidateSearch(this.value)"></div><button class="candidate-filter-button ${activeFilters?'active':''}" type="button" onclick="openCandidateFilters()" aria-label="Filtros"><i class="fa-solid fa-sliders"></i>${activeFilters?'<span class="filter-dot"></span>':''}</button><button class="candidate-add-button" style="background:linear-gradient(145deg,var(--primary),#234936);border-color:transparent" type="button" onclick="openNewCandidate()" aria-label="Novo candidato" title="Novo candidato"><i class="fa-solid fa-user-plus"></i></button></div><div id="candidateList" class="list">${candidateListHtml(state.candidates||[])}</div></section>`;
}
function escapeHtml(value){return String(value||'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt',"'":'&#39;','"':'&quot;'}[c]))}
function adjustmentCandidateIds(){return typeof pendingChangeApplicationIds==='function'?pendingChangeApplicationIds():new Set((state.pendingChangeRequests||[]).map(row=>String(row.applicationId||'')).filter(Boolean))}
function getFilteredCandidates(){return state.candidates||[]}
function candidateListHtml(list){
  if(state.candidateLoading&&!list.length)return `<div class="empty compact-loading"><i class="fa-solid fa-circle-notch fa-spin"></i>Carregando voluntários...</div>`;
  if(!list.length)return `<div class="empty"><i class="fa-regular fa-folder-open"></i>Nenhum perfil encontrado com esses filtros.</div>`;
  const more=state.candidateHasMore?`<button class="btn btn-soft btn-block candidate-load-more" type="button" onclick="loadMoreCandidates()" ${state.candidateLoading?'disabled':''}><i class="fa-solid ${state.candidateLoading?'fa-circle-notch fa-spin':'fa-chevron-down'}"></i>${state.candidateLoading?'Carregando...':'Ver mais 10'}</button>`:'';
  return list.map(personCompact).join('')+more;
}
async function loadMoreCandidates(){if(typeof loadMoreManagerCandidates==='function')await loadMoreManagerCandidates()}
function refreshCandidateList(){const list=document.getElementById('candidateList');if(list){list.innerHTML=candidateListHtml(state.candidates||[]);if(typeof applyI18n==='function')applyI18n(list)}}
function updateCandidateSearch(value){state.candidateSearch=value;clearTimeout(_candidateSearchTimer);_candidateSearchTimer=setTimeout(()=>{if(typeof loadManagerCandidates==='function')loadManagerCandidates({force:true}).catch(error=>{console.error(error);showToast('Não foi possível buscar os voluntários.')})},300)}
function openCandidateFilters(){const filter=normalizeCandidateFilter(state.candidateFilter);const unit=state.candidateUnit||'all';openModal('Filtros','Refine os perfis exibidos.',`<div class="filter-modal-content"><div class="field"><label>Status</label><select id="candidateStatusFilter" class="select">${CANDIDATE_STATUS_OPTIONS.map(([id,l])=>`<option value="${id}" ${filter===id?'selected':''}>${l}</option>`).join('')}</select></div><div class="field"><label>Unidade</label><select id="candidateUnitFilter" class="select">${[['all','Todas as unidades'],['Rodeio','Rodeio'],['Indaial','Indaial']].map(([id,l])=>`<option value="${id}" ${unit===id?'selected':''}>${l}</option>`).join('')}</select></div><div class="filter-modal-actions"><button class="btn btn-outline" type="button" onclick="clearCandidateFilters()">Limpar filtros</button><button class="btn btn-primary" type="button" onclick="applyCandidateFilters()">Aplicar</button></div></div>`);modalRoot.querySelector('.modal')?.classList.add('filter-modal');}
function applyCandidateFilters(){state.candidateFilter=normalizeCandidateFilter(document.getElementById('candidateStatusFilter')?.value);state.candidateUnit=document.getElementById('candidateUnitFilter')?.value||'all';closeModal();render();if(typeof loadManagerCandidates==='function')loadManagerCandidates({force:true}).catch(error=>{console.error(error);showToast('Não foi possível aplicar os filtros.')})}
function clearCandidateFilters(){state.candidateFilter='all';state.candidateUnit='all';closeModal();render();if(typeof loadManagerCandidates==='function')loadManagerCandidates({force:true}).catch(console.error)}
function countFilter(id){if(id==='all')return state.candidates.length;if(id==='adjustments')return dashboardCount('adjustments');return state.candidates.filter(p=>p.status===id).length;}
function countTab(id){if(id==='candidates')return state.candidates.filter(p=>['pending','analysis','adjustments','meeting'].includes(p.status)).length;return state.candidates.filter(p=>p.status===id).length}
