const CANDIDATE_STATUS_OPTIONS=[['all','Todos os status'],['pending','Em preparação'],['analysis','Em análise'],['adjustments','Ajustes'],['meeting','Planejamento aprovado'],['approved','Aprovado'],['rejected','Recusado']];
const CANDIDATE_PAGE_SIZE=10;let _candidateSearchTimer=null;
function normalizeCandidateFilter(value){return CANDIDATE_STATUS_OPTIONS.some(([id])=>id===value)?value:'approved'}
function managerVolunteers(){
  state.candidateFilter=normalizeCandidateFilter(state.candidateFilter);const search=state.candidateSearch||'';const activeFilters=state.candidateFilter!=='approved'||(state.candidateUnit||'all')!=='all';
  return `<div class="r61-page"><div class="r61-page-heading"><div><span class="r61-kicker">Pessoas e processos</span><h1>Voluntariado</h1><p>Acompanhe candidatos, planejamentos, reuniões, aprovações e voluntários em estadia.</p></div><div class="r61-heading-actions"><button class="btn btn-outline" type="button" onclick="openOccupancyCalendar()"><i class="fa-solid fa-bed"></i>Ocupação</button><button class="btn btn-primary" type="button" onclick="openNewCandidate()"><i class="fa-solid fa-user-plus"></i>Novo candidato</button></div></div><div class="r61-volunteer-toolbar"><div class="filter-search candidate-search"><i class="fa-solid fa-magnifying-glass"></i><input id="candidateSearch" class="input" type="search" value="${escapeHtml(search)}" placeholder="Buscar voluntário por nome" oninput="updateCandidateSearch(this.value)"></div><button class="candidate-filter-button ${activeFilters?'active':''}" type="button" onclick="openCandidateFilters()" aria-label="Filtros"><i class="fa-solid fa-sliders"></i>${activeFilters?'<span class="filter-dot"></span>':''}</button><button class="candidate-add-button" type="button" onclick="openNewCandidate()" aria-label="Novo candidato"><i class="fa-solid fa-plus"></i></button></div><div class="candidate-filter-summary">${candidateFilterSummary()}</div><div id="candidateList">${candidateListHtml(state.candidates||[])}</div></div>`;
}
function escapeHtml(value){return String(value||'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function adjustmentCandidateIds(){return typeof pendingChangeApplicationIds==='function'?pendingChangeApplicationIds():new Set((state.pendingChangeRequests||[]).map(row=>String(row.applicationId||'')).filter(Boolean))}
function getFilteredCandidates(){return state.candidates||[]}
function r61CandidateRow(p){
  const [label,tone]=statusMeta(p.status),meta=p.status==='pending'&&typeof candidateDeadlineMeta==='function'?candidateDeadlineMeta(p):null;const inactive=p.inactive&&p.status!=='rejected'?badge('Inativo','danger'):'';const period=p.from&&p.to?`${fmtDate(p.from,true)} – ${fmtDate(p.to,true)}`:'Período não informado';const id=typeof candidateActionArg==='function'?candidateActionArg(p.id):encodeURIComponent(String(p.id));const initials=String(p.name||'V').split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase();
  return `<article class="r61-candidate-row" role="button" tabindex="0" onclick="openPerson(decodeURIComponent('${id}'))" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();openPerson(decodeURIComponent('${id}'))}"><div class="r61-person"><div class="avatar">${escapeHtml(initials)}</div><div><strong>${escapeHtml(p.name||'Voluntário')}</strong><span>${escapeHtml(p.country||'—')}${p.type==='couple'?' • Dupla':''}</span></div></div><div class="r61-cell r61-unit"><strong>${escapeHtml(p.unit||p.unitName||p.unitId||'—')}</strong><small>Unidade</small></div><div class="r61-cell r61-stay"><strong>${escapeHtml(period)}</strong><small>${meta?escapeHtml(meta.label):'Estadia'}</small></div><div class="r61-status"><div class="item-meta">${badge(label,tone)}${inactive}</div></div><i class="fa-solid fa-chevron-right r61-chevron"></i></article>`;
}
function candidateListHtml(list){
  if(state.candidateLoading&&!list.length)return `<div class="empty compact-loading"><i class="fa-solid fa-circle-notch fa-spin"></i>Carregando voluntários...</div>`;
  if(!list.length)return `<div class="empty"><i class="fa-regular fa-folder-open"></i>Nenhum perfil encontrado com esses filtros.</div>`;
  const more=state.candidateHasMore?`<button class="btn btn-soft btn-block candidate-load-more" type="button" onclick="loadMoreCandidates()" ${state.candidateLoading?'disabled':''}><i class="fa-solid ${state.candidateLoading?'fa-circle-notch fa-spin':'fa-chevron-down'}"></i>${state.candidateLoading?'Carregando...':'Ver mais 10'}</button>`:'';
  return `<div class="r61-candidate-table"><div class="r61-candidate-head"><span>Voluntário</span><span>Unidade</span><span>Estadia</span><span>Status</span><span></span></div>${list.map(r61CandidateRow).join('')}</div>${more}`;
}
async function loadMoreCandidates(){if(typeof loadMoreManagerCandidates==='function')await loadMoreManagerCandidates()}
function refreshCandidateList(){const list=document.getElementById('candidateList');if(list){list.innerHTML=candidateListHtml(state.candidates||[]);if(typeof applyI18n==='function')applyI18n(list)}}
function updateCandidateSearch(value){state.candidateSearch=value;clearTimeout(_candidateSearchTimer);_candidateSearchTimer=setTimeout(()=>{if(typeof loadManagerCandidates==='function')loadManagerCandidates({force:true}).catch(error=>{console.error(error);showToast('Não foi possível buscar os voluntários.')})},300)}
function candidateFilterSummary(){const filter=normalizeCandidateFilter(state.candidateFilter);const unit=state.candidateUnit||'all';const label=(CANDIDATE_STATUS_OPTIONS.find(([id])=>id===filter)||['','Aprovado'])[1];const parts=[label];if(unit!=='all')parts.push(unit);return `<span><i class="fa-solid fa-filter"></i>${parts.join(' • ')}</span>`}
function openCandidateFilters(){const filter=normalizeCandidateFilter(state.candidateFilter);const unit=state.candidateUnit||'all';openModal('Filtros','Refine os perfis exibidos.',`<div class="filter-modal-content"><div class="field"><label>Status</label><select id="candidateStatusFilter" class="select">${CANDIDATE_STATUS_OPTIONS.map(([id,l])=>`<option value="${id}" ${filter===id?'selected':''}>${l}</option>`).join('')}</select></div><div class="field"><label>Unidade</label><select id="candidateUnitFilter" class="select">${[['all','Todas as unidades'],['Rodeio','Rodeio'],['Indaial','Indaial']].map(([id,l])=>`<option value="${id}" ${unit===id?'selected':''}>${l}</option>`).join('')}</select></div><div class="filter-modal-actions"><button class="btn btn-outline" type="button" onclick="clearCandidateFilters()">Limpar filtros</button><button class="btn btn-primary" type="button" onclick="applyCandidateFilters()">Aplicar</button></div></div>`);modalRoot.querySelector('.modal')?.classList.add('filter-modal')}
function applyCandidateFilters(){state.candidateFilter=normalizeCandidateFilter(document.getElementById('candidateStatusFilter')?.value);state.candidateUnit=document.getElementById('candidateUnitFilter')?.value||'all';closeModal();render();if(typeof loadManagerCandidates==='function')loadManagerCandidates({force:true}).catch(error=>{console.error(error);showToast('Não foi possível aplicar os filtros.')})}
function clearCandidateFilters(){state.candidateFilter='approved';state.candidateUnit='all';closeModal();render();if(typeof loadManagerCandidates==='function')loadManagerCandidates({force:true}).catch(console.error)}
function countFilter(id){if(id==='all')return state.candidates.length;if(id==='adjustments')return dashboardCount('adjustments');return state.candidates.filter(p=>p.status===id).length}
function countTab(id){if(id==='candidates')return state.candidates.filter(p=>['pending','analysis','adjustments','meeting'].includes(p.status)).length;return state.candidates.filter(p=>p.status===id).length}
