if(typeof OLEIRO_TRANSLATIONS!=='undefined'){
  Object.assign(OLEIRO_TRANSLATIONS.en,{
    'Filtros':'Filters','Refine os perfis exibidos.':'Refine the displayed profiles.','Status do perfil':'Profile status','Limpar filtros':'Clear filters','Aplicar filtros':'Apply filters','Aplicar':'Apply','Buscar voluntário por nome':'Search volunteer by name','Novo voluntário':'New volunteer','Todos os status':'All statuses',
    'Período da agenda':'Schedule period','Escolha as datas que deseja visualizar.':'Choose the dates you want to view.','De':'From','Até':'To','Aplicar período':'Apply period','Agenda do dia':'Day schedule','Período selecionado':'Selected period','Período anterior':'Previous period','Próximo período':'Next period','Escolher período':'Choose period','Informe as duas datas.':'Enter both dates.','A data final deve ser igual ou posterior à inicial.':'The end date must be the same as or later than the start date.','Selecione um período de até 31 dias.':'Select a period of up to 31 days.','Português, English ou Español':'Portuguese, English or Spanish','Idioma da interface':'Interface language',
    'Excluir integrante?':'Remove member?','Confirme a remoção deste integrante do grupo.':'Confirm removing this member from the group.','Cancelar':'Cancel','Excluir':'Remove','Integrante removido.':'Member removed.'
  });
  Object.assign(OLEIRO_TRANSLATIONS.es,{
    'Filtros':'Filtros','Refine os perfis exibidos.':'Refina los perfiles mostrados.','Status do perfil':'Estado del perfil','Limpar filtros':'Limpiar filtros','Aplicar filtros':'Aplicar filtros','Aplicar':'Aplicar','Buscar voluntário por nome':'Buscar voluntario por nombre','Novo voluntário':'Nuevo voluntario','Todos os status':'Todos los estados',
    'Período da agenda':'Período de la agenda','Escolha as datas que deseja visualizar.':'Elige las fechas que deseas visualizar.','De':'Desde','Até':'Hasta','Aplicar período':'Aplicar período','Agenda do dia':'Agenda del día','Período selecionado':'Período seleccionado','Período anterior':'Período anterior','Próximo período':'Próximo período','Escolher período':'Elegir período','Informe as duas datas.':'Ingresa ambas fechas.','A data final deve ser igual ou posterior à inicial.':'La fecha final debe ser igual o posterior a la inicial.','Selecione um período de até 31 dias.':'Selecciona un período de hasta 31 días.','Português, English ou Español':'Portugués, English o Español','Idioma da interface':'Idioma de la interfaz',
    'Excluir integrante?':'¿Eliminar integrante?','Confirme a remoção deste integrante do grupo.':'Confirma la eliminación de este integrante del grupo.','Cancelar':'Cancelar','Excluir':'Eliminar','Integrante removido.':'Integrante eliminado.'
  });
}
