const OLEIRO_LANGUAGES={
  pt:{code:'PT',label:'Português',locale:'pt-BR',html:'pt-BR'},
  en:{code:'EN',label:'English',locale:'en-US',html:'en'},
  es:{code:'ES',label:'Español',locale:'es-ES',html:'es'}
};

const OLEIRO_TRANSLATIONS={
  en:{
    'Idioma':'Language','Escolha o idioma da interface.':'Choose the interface language.','Português':'Portuguese',
    'Portal do voluntário • Rodeio':'Volunteer portal • Rodeio','Gestão de voluntariado • Rodeio':'Volunteer management • Rodeio',
    'Início':'Home','Voluntariado':'Volunteering','Planejamento':'Planning','Agenda':'Schedule','Estadia':'Stay','Informações':'Information','Grupos':'Groups','Menu':'Menu',
    'Gestão':'Management','Organização':'Organization','Portal':'Portal','Configurações e informações da Casa':'House settings and information','Conta e informações':'Account and information',
    'Prepare sua experiência':'Prepare your experience','Bem-vindo à sua experiência':'Welcome to your experience','Período proposto':'Proposed period','Estadia confirmada':'Confirmed stay',
    'Montar planejamento':'Build plan','Ajustar planejamento':'Adjust plan','Ver planejamento':'View plan','Minha agenda':'My schedule',
    'Seu cronograma foi atualizado':'Your schedule was updated','Confira sua agenda para acompanhar alterações recentes.':'Check your schedule to see recent changes.',
    'Próxima atividade':'Next activity','O que vem a seguir':'What comes next','Nenhuma próxima atividade confirmada.':'No upcoming confirmed activity.',
    'Seu planejamento':'Your plan','Status da proposta enviada':'Submitted proposal status','Enviado para análise':'Sent for review','Ajustes solicitados':'Changes requested',
    'Planejamento aprovado':'Plan approved','Planejamento pendente':'Plan pending','A equipe da Casa recebeu seu planejamento. Enquanto ele estiver em análise, a edição fica bloqueada.':'The House team received your plan. Editing is locked while it is under review.',
    'A equipe pediu alterações. Revise o planejamento e reenvie quando estiver pronto.':'The team requested changes. Review your plan and resend it when ready.',
    'Seu planejamento foi aprovado pela equipe da Casa.':'Your plan was approved by the House team.','Monte seu planejamento e envie para análise.':'Build your plan and send it for review.',
    'Minha estadia':'My stay','Informações principais':'Main information','Chegada':'Arrival','Saída':'Departure','Dia sem atividade':'Day without activities',
    'Informações importantes':'Important information','Tudo para sua chegada':'Everything for your arrival','Como chegar':'How to get here','Transporte, endereço e horários':'Transport, address and times',
    'Acomodação e refeições':'Accommodation and meals','O que está incluído na experiência':'What is included in the experience',
    'Meu planejamento':'My plan','Datas e horários são sugestões até a confirmação da Casa':'Dates and times are suggestions until confirmed by the House',
    'Atividades':'Activities','Atividade':'Activity','Resumo':'Summary','Enviar planejamento':'Send plan','Reenviar planejamento':'Resend plan','Enviado':'Sent',
    'Planejamento enviado. Enquanto a equipe estiver analisando, atividades e sessões ficam bloqueadas para edição.':'Plan sent. Activities and sessions are locked while the team reviews it.',
    'A equipe solicitou ajustes. Faça as alterações necessárias e reenvie o planejamento para uma nova análise.':'The team requested changes. Make the necessary updates and resend the plan for a new review.',
    'Monte o planejamento pelos dias da sua estadia. Você poderá editar tudo até realizar o primeiro envio.':'Build the plan across the days of your stay. You can edit everything until the first submission.',
    'Seu planejamento aprovado continua disponível para consulta. Alterações em sessões confirmadas voltam para análise da Casa.':'Your approved plan remains available for reference. Changes to confirmed sessions return to House review.',
    'Nenhuma atividade planejada.':'No activity planned.','Adicionar atividade':'Add activity','Editar':'Edit','Mover':'Move','Editar atividade':'Edit activity','+ Sessão':'+ Session',
    'Nova atividade':'New activity','Cadastre uma vez e selecione quantas datas precisar.':'Create it once and select as many dates as needed.',
    'A descrição é compartilhada entre todas as sessões.':'The description is shared across all sessions.','Nome da atividade':'Activity name','Descrição':'Description','Duração':'Duration',
    'Participação':'Participation','Materiais necessários':'Required materials','Observações':'Notes','Período preferido':'Preferred period','Horário sugerido':'Period',
    'Datas em que deseja realizar':'Dates you want to run it','Adicionar sessão':'Add session','Selecione uma nova data':'Select a new date','Salvar alterações':'Save changes',
    'Informe o nome da atividade.':'Enter the activity name.','Selecione pelo menos uma data.':'Select at least one date.','Atividade atualizada.':'Activity updated.',
    'Atividade adicionada ao planejamento.':'Activity added to the plan.','Nova sessão adicionada.':'New session added.','Planejamento enviado para análise.':'Plan sent for review.',
    'Planejamento reenviado para análise.':'Plan resent for review.','Adicione pelo menos uma atividade antes de enviar.':'Add at least one activity before sending.',
    'Cronograma operacional atualizado':'Updated operational schedule','Uma alteração feita por você pode precisar de nova confirmação da equipe.':'A change you make may require new confirmation from the team.',
    'Informações da Casa':'House information','Consulte antes e durante sua experiência':'Check before and during your experience','Perfil do voluntário':'Volunteer profile',
    'Dados pessoais e do acesso':'Personal and access details','Trocar modo do protótipo':'Switch prototype mode','Alternar em processo / aprovado':'Switch in process / approved',
    'Sair':'Sign out','Encerrar sessão':'End session','Seus dados de acesso e da experiência':'Your access and experience details','E-mail':'Email','WhatsApp':'WhatsApp','Período':'Period','Status':'Status',
    'Em preparação':'In preparation','Planejamento em análise':'Plan under review','Aprovado':'Approved','Rejeitado':'Rejected','Em análise':'Under review',
    'Informações do portal':'Portal information','Conteúdo que candidatos e voluntários consultam':'Content candidates and volunteers can view','Unidades':'Units',
    'Rodeio ativa • Indaial preparada':'Rodeio active • Indaial ready','Gestores e acessos':'Managers and access','Administradores e coordenadores':'Administrators and coordinators',
    'Rotina-base':'Base routine','Horários de referência da comunidade':'Community reference times','Minha conta':'My account','Preferências e sessão':'Preferences and session',
    'Encerrar sessão neste dispositivo':'End session on this device','Conteúdo visível para candidatos e voluntários.':'Content visible to candidates and volunteers.',
    'Editar conteúdo':'Edit content','Estrutura preparada para expansão.':'Structure prepared for expansion.','Unidade ativa':'Active unit','Preparada para ativação futura':'Ready for future activation',
    'Ativa':'Active','Inativa':'Inactive','MVP com mesmo nível de permissão.':'MVP with the same permission level.','Administrador principal':'Primary administrator',
    'Acesso completo no MVP':'Full access in the MVP','Gestor':'Manager','Referência geral da comunidade.':'General community reference.',
    'Despertar e higiene':'Wake up and hygiene','Devocional':'Devotional','Café da manhã':'Breakfast','Atividades práticas':'Practical activities',
    'Reunião de sentimentos':'Feelings meeting','Almoço e descanso':'Lunch and rest','Café da tarde':'Afternoon snack','Banho, lazer e jantar':'Shower, leisure and dinner',
    'Filme, palestra, documentário ou outras atividades':'Movie, talk, documentary or other activities','Alojamento':'Accommodation','Silêncio total':'Total silence',
    'Boa noite, Luan':'Good evening, Luan','Veja o que precisa da sua atenção e o que acontece hoje na Casa.':'See what needs your attention and what is happening at the House today.',
    'Novo candidato':'New candidate','Ver agenda':'View schedule','Pendências':'Pending items','Ações que merecem atenção':'Items that need attention','Ajustes':'Changes',
    'Chegadas':'Arrivals','Alteração':'Change','Hoje na Casa':'Today at the House','Nenhuma atividade prevista para hoje.':'No activity scheduled for today.',
    'Próximas movimentações':'Upcoming movements','Chegadas e saídas':'Arrivals and departures','Saídas':'Departures','2 pontos precisam de atenção':'2 items need attention',
    'Existe uma sessão em conflito e uma alteração feita por voluntário aguardando confirmação.':'There is one conflicting session and one volunteer change awaiting confirmation.',
    'Candidatos e experiências da Casa':'Candidates and House experiences','Novo':'New','Buscar por nome, país ou e-mail':'Search by name, country or email',
    'Filtrar por status':'Filter by status','Filtrar por unidade':'Filter by unit','Aprovados':'Approved','Em processo':'In process','Rejeitados':'Rejected','Todos':'All',
    'Todas as unidades':'All units','Por padrão, a lista abre em aprovados. Você pode combinar busca, status e unidade.':'By default, the list opens on approved profiles. You can combine search, status and unit.',
    'Nenhum perfil encontrado com esses filtros.':'No profile found with these filters.','Agenda da Casa':'House schedule','Atividades organizadas por data':'Activities organized by date',
    'A partir de hoje':'Starting today','7 dias a partir da data escolhida':'7 days from the selected date','Hoje':'Today','Escolher data':'Choose date',
    'Ver 7 dias anteriores':'View previous 7 days','Ver próximos 7 dias':'View next 7 days','Escolher uma data':'Choose a date','Nenhuma atividade neste dia.':'No activity on this day.',
    'Materiais:':'Materials:','Confirmar':'Confirm','Grupo':'Group','Composição operacional da unidade':'Operational group composition','Nenhum nome cadastrado.':'No name registered.',
    'Editar grupo':'Edit group','Nomes visíveis somente na área de gestão.':'Names visible only in the management area.','Capacidade de referência':'Reference capacity',
    'Observação':'Note','Integrantes':'Members','Novo nome':'New name','Nome':'Name','Adicionar':'Add','Salvar grupo':'Save group','Informe um nome.':'Enter a name.','Grupo atualizado.':'Group updated.',
    'Cadastre somente quem já está no processo real de avaliação.':'Register only people already in the real evaluation process.','Nome completo':'Full name','Nacionalidade':'Nationality','País':'Country','Unidade':'Unit','Chegada proposta':'Proposed arrival','Saída proposta':'Proposed departure',
    'Observação interna':'Internal note','Opcional':'Optional','Cadastrar e liberar acesso':'Register and grant access','Visão geral':'Overview','Histórico':'History','Contato':'Contact','Aprovar':'Approve','Pedir ajuste':'Request changes','Recusar':'Reject','Reativar perfil':'Reactivate profile',
    'Perfil criado':'Profile created','Acesso liberado para o processo de planejamento.':'Access granted for the planning process.','Planejamento enviado':'Plan sent','Status atual':'Current status','Nenhuma atividade cadastrada ainda.':'No activity registered yet.',
    'Acomodação':'Accommodation','Refeições':'Meals','Rotina da comunidade':'Community routine','Princípios e religião':'Principles and religion','Convivência e segurança':'Living together and safety',
    'A unidade fica em Rodeio/SC. Antes da chegada, confirme com a equipe o melhor transporte e o horário previsto. Dependendo do horário pode haver possibilidade de apoio na chegada.':'The unit is in Rodeio, Santa Catarina. Before arrival, confirm the best transport option and expected time with the team. Depending on the time, arrival support may be available.',
    'Homens utilizam quartos e banheiros compartilhados. Mulheres ficam em quarto e banheiro separados. Wi-Fi, cozinha e lavanderia estão disponíveis.':'Men use shared rooms and bathrooms. Women stay in a separate room with a separate bathroom. Wi-Fi, kitchen and laundry are available.',
    'Todas as refeições são oferecidas na unidade de Rodeio. Avise previamente caso possua alguma restrição alimentar importante.':'All meals are provided at the Rodeio unit. Please let the team know in advance about any important dietary restrictions.',
    'A rotina começa às 06:00 e possui momentos de atividades práticas, reuniões, refeições e atividades noturnas. Ela é flexível devido aos atendimentos terapêuticos e profissionais.':'The routine starts at 06:00 and includes practical activities, meetings, meals and evening activities. It is flexible due to therapeutic and professional appointments.',
    'A Casa possui princípios cristãos e momentos de oração. O voluntário não precisa ser cristão nem participar das atividades religiosas.':'The House follows Christian principles and has prayer moments. Volunteers do not need to be Christian or take part in religious activities.',
    'Álcool, drogas e cigarros são proibidos. Fotos e vídeos dos acolhidos exigem autorização prévia. Voluntários não exercem funções clínicas, medicamentosas ou terapêuticas.':'Alcohol, drugs and cigarettes are prohibited. Photos and videos of residents require prior authorization. Volunteers do not perform clinical, medication or therapeutic duties.',
    'Atualizações':'Updates','Mudanças e pendências recentes':'Recent changes and pending items','Fechar':'Close','Ir para a tela inicial':'Go to home',
    'Portal de gestão e planejamento do programa de voluntariado.':'Management and planning portal for the volunteer program.','Senha':'Password','Entrar':'Sign in',
    'Modo protótipo':'Prototype mode','Atalhos temporários para validar cada experiência antes do backend.':'Temporary shortcuts to validate each experience before the backend.',
    'Candidato':'Candidate','Voluntário':'Volunteer','Perfil inativo':'Inactive profile','Informe e-mail e senha.':'Enter email and password.','Autenticação real será conectada após a validação das telas.':'Real authentication will be connected after the screens are validated.',
    'Manhã':'Morning','Tarde':'Afternoon','Noite':'Evening','Sem preferência':'No preference','Livre':'Open','Até 5':'Up to 5','Até 10':'Up to 10','Outro':'Other','Proposta':'Proposal','Confirmada':'Confirmed','Alteração pendente':'Pending change','Conflito':'Conflict','A definir':'To be defined'
  },
  es:{
    'Idioma':'Idioma','Escolha o idioma da interface.':'Elige el idioma de la interfaz.','Português':'Portugués','Portal do voluntário • Rodeio':'Portal del voluntario • Rodeio','Gestão de voluntariado • Rodeio':'Gestión de voluntariado • Rodeio',
    'Início':'Inicio','Voluntariado':'Voluntariado','Planejamento':'Planificación','Agenda':'Agenda','Estadia':'Estadía','Informações':'Información','Grupos':'Grupos','Menu':'Menú','Gestão':'Gestión','Organização':'Organización','Portal':'Portal','Configurações e informações da Casa':'Configuración e información de la Casa','Conta e informações':'Cuenta e información',
    'Prepare sua experiência':'Prepara tu experiencia','Bem-vindo à sua experiência':'Bienvenido a tu experiencia','Período proposto':'Período propuesto','Estadia confirmada':'Estadía confirmada','Montar planejamento':'Crear planificación','Ajustar planejamento':'Ajustar planificación','Ver planejamento':'Ver planificación','Minha agenda':'Mi agenda',
    'Seu cronograma foi atualizado':'Tu cronograma fue actualizado','Confira sua agenda para acompanhar alterações recentes.':'Revisa tu agenda para ver los cambios recientes.','Próxima atividade':'Próxima actividad','O que vem a seguir':'Lo que sigue','Nenhuma próxima atividade confirmada.':'No hay próximas actividades confirmadas.',
    'Seu planejamento':'Tu planificación','Status da proposta enviada':'Estado de la propuesta enviada','Enviado para análise':'Enviado para revisión','Ajustes solicitados':'Ajustes solicitados','Planejamento aprovado':'Planificación aprobada','Planejamento pendente':'Planificación pendiente',
    'A equipe da Casa recebeu seu planejamento. Enquanto ele estiver em análise, a edição fica bloqueada.':'El equipo de la Casa recibió tu planificación. La edición queda bloqueada mientras está en revisión.','A equipe pediu alterações. Revise o planejamento e reenvie quando estiver pronto.':'El equipo solicitó cambios. Revisa la planificación y vuelve a enviarla cuando esté lista.','Seu planejamento foi aprovado pela equipe da Casa.':'Tu planificación fue aprobada por el equipo de la Casa.','Monte seu planejamento e envie para análise.':'Crea tu planificación y envíala para revisión.',
    'Minha estadia':'Mi estadía','Informações principais':'Información principal','Chegada':'Llegada','Saída':'Salida','Dia sem atividade':'Día sin actividad','Informações importantes':'Información importante','Tudo para sua chegada':'Todo para tu llegada','Como chegar':'Cómo llegar','Transporte, endereço e horários':'Transporte, dirección y horarios','Acomodação e refeições':'Alojamiento y comidas','O que está incluído na experiência':'Qué está incluido en la experiencia',
    'Meu planejamento':'Mi planificación','Datas e horários são sugestões até a confirmação da Casa':'Las fechas y horarios son sugerencias hasta la confirmación de la Casa','Atividades':'Actividades','Atividade':'Actividad','Resumo':'Resumen','Enviar planejamento':'Enviar planificación','Reenviar planejamento':'Reenviar planificación','Enviado':'Enviado',
    'Planejamento enviado. Enquanto a equipe estiver analisando, atividades e sessões ficam bloqueadas para edição.':'Planificación enviada. Las actividades y sesiones quedan bloqueadas mientras el equipo la revisa.','A equipe solicitou ajustes. Faça as alterações necessárias e reenvie o planejamento para uma nova análise.':'El equipo solicitó ajustes. Realiza los cambios necesarios y vuelve a enviar la planificación para una nueva revisión.','Monte o planejamento pelos dias da sua estadia. Você poderá editar tudo até realizar o primeiro envio.':'Crea la planificación para los días de tu estadía. Podrás editar todo hasta el primer envío.','Seu planejamento aprovado continua disponível para consulta. Alterações em sessões confirmadas voltam para análise da Casa.':'Tu planificación aprobada seguirá disponible para consulta. Los cambios en sesiones confirmadas vuelven a revisión de la Casa.',
    'Nenhuma atividade planejada.':'No hay actividades planificadas.','Adicionar atividade':'Agregar actividad','Editar':'Editar','Mover':'Mover','Editar atividade':'Editar actividad','+ Sessão':'+ Sesión','Nova atividade':'Nueva actividad','Cadastre uma vez e selecione quantas datas precisar.':'Créala una vez y selecciona todas las fechas que necesites.','A descrição é compartilhada entre todas as sessões.':'La descripción se comparte entre todas las sesiones.','Nome da atividade':'Nombre de la actividad','Descrição':'Descripción','Duração':'Duración','Participação':'Participación','Materiais necessários':'Materiales necesarios','Observações':'Observaciones','Período preferido':'Período preferido','Horário sugerido':'Período','Datas em que deseja realizar':'Fechas en las que deseas realizarla','Adicionar sessão':'Agregar sesión','Selecione uma nova data':'Selecciona una nueva fecha','Salvar alterações':'Guardar cambios',
    'Informe o nome da atividade.':'Ingresa el nombre de la actividad.','Selecione pelo menos uma data.':'Selecciona al menos una fecha.','Atividade atualizada.':'Actividad actualizada.','Atividade adicionada ao planejamento.':'Actividad agregada a la planificación.','Nova sessão adicionada.':'Nueva sesión agregada.','Planejamento enviado para análise.':'Planificación enviada para revisión.','Planejamento reenviado para análise.':'Planificación reenviada para revisión.','Adicione pelo menos uma atividade antes de enviar.':'Agrega al menos una actividad antes de enviar.',
    'Cronograma operacional atualizado':'Cronograma operativo actualizado','Uma alteração feita por você pode precisar de nova confirmação da equipe.':'Un cambio realizado por ti puede necesitar una nueva confirmación del equipo.','Informações da Casa':'Información de la Casa','Consulte antes e durante sua experiência':'Consulta antes y durante tu experiencia','Perfil do voluntário':'Perfil del voluntario','Dados pessoais e do acesso':'Datos personales y de acceso','Trocar modo do protótipo':'Cambiar modo del prototipo','Alternar em processo / aprovado':'Alternar en proceso / aprobado','Sair':'Salir','Encerrar sessão':'Cerrar sesión','Seus dados de acesso e da experiência':'Tus datos de acceso y de la experiencia','E-mail':'Correo electrónico','WhatsApp':'WhatsApp','Período':'Período','Status':'Estado','Em preparação':'En preparación','Planejamento em análise':'Planificación en revisión','Aprovado':'Aprobado','Rejeitado':'Rechazado','Em análise':'En revisión',
    'Informações do portal':'Información del portal','Conteúdo que candidatos e voluntários consultam':'Contenido que consultan candidatos y voluntarios','Unidades':'Unidades','Rodeio ativa • Indaial preparada':'Rodeio activa • Indaial preparada','Gestores e acessos':'Gestores y accesos','Administradores e coordenadores':'Administradores y coordinadores','Rotina-base':'Rutina base','Horários de referência da comunidade':'Horarios de referencia de la comunidad','Minha conta':'Mi cuenta','Preferências e sessão':'Preferencias y sesión','Encerrar sessão neste dispositivo':'Cerrar sesión en este dispositivo','Conteúdo visível para candidatos e voluntários.':'Contenido visible para candidatos y voluntarios.','Editar conteúdo':'Editar contenido','Estrutura preparada para expansão.':'Estructura preparada para expansión.','Unidade ativa':'Unidad activa','Preparada para ativação futura':'Preparada para activación futura','Ativa':'Activa','Inativa':'Inactiva','MVP com mesmo nível de permissão.':'MVP con el mismo nivel de permisos.','Administrador principal':'Administrador principal','Acesso completo no MVP':'Acceso completo en el MVP','Gestor':'Gestor','Referência geral da comunidade.':'Referencia general de la comunidad.',
    'Despertar e higiene':'Despertar e higiene','Devocional':'Devocional','Café da manhã':'Desayuno','Atividades práticas':'Actividades prácticas','Reunião de sentimentos':'Reunión de sentimientos','Almoço e descanso':'Almuerzo y descanso','Café da tarde':'Merienda','Banho, lazer e jantar':'Ducha, ocio y cena','Filme, palestra, documentário ou outras atividades':'Película, charla, documental u otras actividades','Alojamento':'Alojamiento','Silêncio total':'Silencio total',
    'Boa noite, Luan':'Buenas noches, Luan','Veja o que precisa da sua atenção e o que acontece hoje na Casa.':'Mira qué necesita tu atención y qué ocurre hoy en la Casa.','Novo candidato':'Nuevo candidato','Ver agenda':'Ver agenda','Pendências':'Pendientes','Ações que merecem atenção':'Acciones que requieren atención','Ajustes':'Ajustes','Chegadas':'Llegadas','Alteração':'Cambio','Hoje na Casa':'Hoy en la Casa','Nenhuma atividade prevista para hoje.':'No hay actividades previstas para hoy.','Próximas movimentações':'Próximos movimientos','Chegadas e saídas':'Llegadas y salidas','Saídas':'Salidas','2 pontos precisam de atenção':'2 puntos requieren atención','Existe uma sessão em conflito e uma alteração feita por voluntário aguardando confirmação.':'Hay una sesión en conflicto y un cambio realizado por un voluntario esperando confirmación.',
    'Candidatos e experiências da Casa':'Candidatos y experiencias de la Casa','Novo':'Nuevo','Buscar por nome, país ou e-mail':'Buscar por nombre, país o correo','Filtrar por status':'Filtrar por estado','Filtrar por unidade':'Filtrar por unidad','Aprovados':'Aprobados','Em processo':'En proceso','Rejeitados':'Rechazados','Todos':'Todos','Todas as unidades':'Todas las unidades','Por padrão, a lista abre em aprovados. Você pode combinar busca, status e unidade.':'Por defecto, la lista abre en aprobados. Puedes combinar búsqueda, estado y unidad.','Nenhum perfil encontrado com esses filtros.':'No se encontró ningún perfil con esos filtros.','Agenda da Casa':'Agenda de la Casa','Atividades organizadas por data':'Actividades organizadas por fecha','A partir de hoje':'A partir de hoy','7 dias a partir da data escolhida':'7 días desde la fecha elegida','Hoje':'Hoy','Escolher data':'Elegir fecha','Ver 7 dias anteriores':'Ver 7 días anteriores','Ver próximos 7 dias':'Ver próximos 7 días','Escolher uma data':'Elegir una fecha','Nenhuma atividade neste dia.':'No hay actividades este día.','Materiais:':'Materiales:','Confirmar':'Confirmar','Grupo':'Grupo','Composição operacional da unidade':'Composición operativa de la unidad','Nenhum nome cadastrado.':'No hay nombres registrados.','Editar grupo':'Editar grupo','Nomes visíveis somente na área de gestão.':'Nombres visibles solo en el área de gestión.','Capacidade de referência':'Capacidad de referencia','Observação':'Observación','Integrantes':'Integrantes','Novo nome':'Nuevo nombre','Nome':'Nombre','Adicionar':'Agregar','Salvar grupo':'Guardar grupo','Informe um nome.':'Ingresa un nombre.','Grupo atualizado.':'Grupo actualizado.',
    'Cadastre somente quem já está no processo real de avaliação.':'Registra solo a quien ya está en el proceso real de evaluación.','Nome completo':'Nombre completo','Nacionalidade':'Nacionalidad','País':'País','Unidade':'Unidad','Chegada proposta':'Llegada propuesta','Saída proposta':'Salida propuesta','Observação interna':'Observación interna','Opcional':'Opcional','Cadastrar e liberar acesso':'Registrar y habilitar acceso','Visão geral':'Vista general','Histórico':'Historial','Contato':'Contacto','Aprovar':'Aprobar','Pedir ajuste':'Solicitar ajuste','Recusar':'Rechazar','Reativar perfil':'Reactivar perfil','Perfil criado':'Perfil creado','Acesso liberado para o processo de planejamento.':'Acceso habilitado para el proceso de planificación.','Planejamento enviado':'Planificación enviada','Status atual':'Estado actual','Nenhuma atividade cadastrada ainda.':'Todavía no hay actividades registradas.',
    'Acomodação':'Alojamiento','Refeições':'Comidas','Rotina da comunidade':'Rutina de la comunidad','Princípios e religião':'Principios y religión','Convivência e segurança':'Convivencia y seguridad','A unidade fica em Rodeio/SC. Antes da chegada, confirme com a equipe o melhor transporte e o horário previsto. Dependendo do horário pode haver possibilidade de apoio na chegada.':'La unidad está en Rodeio/SC. Antes de llegar, confirma con el equipo el mejor transporte y el horario previsto. Según la hora, puede haber apoyo para la llegada.','Homens utilizam quartos e banheiros compartilhados. Mulheres ficam em quarto e banheiro separados. Wi-Fi, cozinha e lavanderia estão disponíveis.':'Los hombres utilizan habitaciones y baños compartidos. Las mujeres tienen habitación y baño separados. Hay Wi-Fi, cocina y lavandería.','Todas as refeições são oferecidas na unidade de Rodeio. Avise previamente caso possua alguma restrição alimentar importante.':'Todas las comidas se ofrecen en la unidad de Rodeio. Avisa con anticipación si tienes alguna restricción alimentaria importante.','A rotina começa às 06:00 e possui momentos de atividades práticas, reuniões, refeições e atividades noturnas. Ela é flexível devido aos atendimentos terapêuticos e profissionais.':'La rutina comienza a las 06:00 e incluye actividades prácticas, reuniones, comidas y actividades nocturnas. Es flexible debido a las atenciones terapéuticas y profesionales.','A Casa possui princípios cristãos e momentos de oração. O voluntário não precisa ser cristão nem participar das atividades religiosas.':'La Casa tiene principios cristianos y momentos de oración. El voluntario no necesita ser cristiano ni participar en actividades religiosas.','Álcool, drogas e cigarros são proibidos. Fotos e vídeos dos acolhidos exigem autorização prévia. Voluntários não exercem funções clínicas, medicamentosas ou terapêuticas.':'El alcohol, las drogas y los cigarrillos están prohibidos. Las fotos y videos de los residentes requieren autorización previa. Los voluntarios no realizan funciones clínicas, de medicación ni terapéuticas.',
    'Atualizações':'Actualizaciones','Mudanças e pendências recentes':'Cambios y pendientes recientes','Fechar':'Cerrar','Ir para a tela inicial':'Ir al inicio','Portal de gestão e planejamento do programa de voluntariado.':'Portal de gestión y planificación del programa de voluntariado.','Senha':'Contraseña','Entrar':'Entrar','Modo protótipo':'Modo prototipo','Atalhos temporários para validar cada experiência antes do backend.':'Atajos temporales para validar cada experiencia antes del backend.','Candidato':'Candidato','Voluntário':'Voluntario','Perfil inativo':'Perfil inactivo','Informe e-mail e senha.':'Ingresa correo y contraseña.','Autenticação real será conectada após a validação das telas.':'La autenticación real se conectará después de validar las pantallas.','Manhã':'Mañana','Tarde':'Tarde','Noite':'Noche','Sem preferência':'Sin preferencia','Livre':'Libre','Até 5':'Hasta 5','Até 10':'Hasta 10','Outro':'Otro','Proposta':'Propuesta','Confirmada':'Confirmada','Alteração pendente':'Cambio pendiente','Conflito':'Conflicto','A definir':'Por definir'
  }
};

function normalizeOleiroLanguage(value){const v=String(value||'').toLowerCase();if(v.startsWith('pt'))return 'pt';if(v.startsWith('es'))return 'es';if(v.startsWith('en'))return 'en';return null}
function detectOleiroLanguage(){const saved=normalizeOleiroLanguage(localStorage.getItem('oleiro-language'));if(saved)return saved;const langs=(navigator.languages&&navigator.languages.length?navigator.languages:[navigator.language]).map(normalizeOleiroLanguage).filter(Boolean);return langs[0]||'en'}
let oleiroLanguage=detectOleiroLanguage();
function currentLanguage(){return oleiroLanguage}
function currentLanguageCode(){return OLEIRO_LANGUAGES[currentLanguage()].code}
function currentLocale(){return OLEIRO_LANGUAGES[currentLanguage()].locale}
function translateText(value,lang=currentLanguage()){
  if(lang==='pt'||value==null)return String(value??'');const raw=String(value);const leading=(raw.match(/^\s*/)||[''])[0],trailing=(raw.match(/\s*$/)||[''])[0];const text=raw.trim();if(!text)return raw;const dict=OLEIRO_TRANSLATIONS[lang]||{};if(dict[text])return leading+dict[text]+trailing;const counted=text.match(/^(.+?)\s+\((\d+)\)$/);if(counted&&dict[counted[1]])return leading+dict[counted[1]]+` (${counted[2]})`+trailing;const group=text.match(/^Grupo\s+(.+)$/);if(group)return leading+(lang==='en'?'Group ':'Grupo ')+group[1]+trailing;const acts=text.match(/^(\d+)\s+atividades$/);if(acts)return leading+acts[1]+' '+(lang==='en'?'activities':'actividades')+trailing;const sessions=text.match(/^(\d+)\s+sessões$/);if(sessions)return leading+sessions[1]+' '+(lang==='en'?'sessions':'sesiones')+trailing;const members=text.match(/^(\d+)\s+integrantes\s+•\s+capacidade de referência\s+(\d+)$/);if(members)return leading+(lang==='en'?`${members[1]} members • reference capacity ${members[2]}`:`${members[1]} integrantes • capacidad de referencia ${members[2]}`)+trailing;const inDays=text.match(/^em\s+(\d+)\s+dias$/);if(inDays)return leading+(lang==='en'?`in ${inDays[1]} days`:`en ${inDays[1]} días`)+trailing;const hours=text.match(/^([\d,.]+)h\s+planejadas$/);if(hours)return leading+(lang==='en'?`${hours[1]}h planned`:`${hours[1]}h planificadas`)+trailing;let out=text;const fragments=[['Planejamento pendente',dict['Planejamento pendente']],['Ajustes solicitados',dict['Ajustes solicitados']],['Em análise',dict['Em análise']],['Confirmada',dict['Confirmada']],['Proposta',dict['Proposta']],['Alteração pendente',dict['Alteração pendente']],['Conflito',dict['Conflito']],['Manhã',dict['Manhã']],['Tarde',dict['Tarde']],['Noite',dict['Noite']],['Sem preferência',dict['Sem preferência']],['Livre',dict['Livre']],['A definir',dict['A definir']],[' atividades',lang==='en'?' activities':' actividades'],[' sessões',lang==='en'?' sessions':' sesiones']].filter(x=>x[1]);for(const [pt,tr] of fragments)out=out.split(pt).join(tr);if(lang!=='pt')out=out.replace(/\bSET\b/g,'SEP');return leading+out+trailing
}
function shouldSkipI18nNode(node){const parent=node.parentElement;return !parent||['SCRIPT','STYLE','NOSCRIPT','TEXTAREA'].includes(parent.tagName)||parent.closest('[data-no-i18n]')}
function applyI18n(root=document.body){if(!root)return;const lang=currentLanguage();document.documentElement.lang=OLEIRO_LANGUAGES[lang].html;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{if(!shouldSkipI18nNode(node))node.nodeValue=translateText(node.nodeValue,lang)});root.querySelectorAll?.('[placeholder],[aria-label],[title]').forEach(el=>{['placeholder','aria-label','title'].forEach(attr=>{if(el.hasAttribute(attr))el.setAttribute(attr,translateText(el.getAttribute(attr),lang))})});document.querySelectorAll('.current-language-code').forEach(el=>el.textContent=currentLanguageCode());const path=location.pathname;if(path.includes('/admin'))document.title=lang==='pt'?'Gestão • Casa do Oleiro':lang==='en'?'Management • Casa do Oleiro':'Gestión • Casa do Oleiro';else if(path.includes('/portal'))document.title=lang==='pt'?'Voluntariado • Casa do Oleiro':lang==='en'?'Volunteering • Casa do Oleiro':'Voluntariado • Casa do Oleiro'}
function setLanguage(lang){const next=normalizeOleiroLanguage(lang)||'pt';oleiroLanguage=next;localStorage.setItem('oleiro-language',next);if(typeof state!=='undefined')state.language=next;closeLanguageModal();if(typeof render==='function')render();else applyI18n(document.body)}
function openLanguageModal(){closeLanguageModal();const lang=currentLanguage();const title=translateText('Idioma',lang);const subtitle=translateText('Escolha o idioma da interface.',lang);const layer=document.createElement('div');layer.id='oleiroLanguageLayer';layer.className='language-overlay';layer.innerHTML=`<div class="language-sheet" role="dialog" aria-modal="true" aria-label="${title}"><div class="language-head"><div><strong>${title}</strong><span>${subtitle}</span></div><button class="language-close" type="button" onclick="closeLanguageModal()" aria-label="${translateText('Fechar',lang)}"><i class="fa-solid fa-xmark"></i></button></div><div class="language-options">${Object.entries(OLEIRO_LANGUAGES).map(([id,meta])=>`<button type="button" class="language-option ${id===lang?'active':''}" onclick="setLanguage('${id}')"><span class="language-code">${meta.code}</span><span>${meta.label}</span>${id===lang?'<i class="fa-solid fa-check"></i>':''}</button>`).join('')}</div></div>`;layer.addEventListener('click',e=>{if(e.target===layer)closeLanguageModal()});document.body.appendChild(layer)}
function closeLanguageModal(){document.getElementById('oleiroLanguageLayer')?.remove()}
document.addEventListener('DOMContentLoaded',()=>applyI18n(document.body));
