function showToast(msg){toastEl.textContent=typeof translateText==='function'?translateText(msg):msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('oleiro-theme',state.theme);document.documentElement.classList.toggle('dark',state.theme==='dark');render()}
function menuLink(icon,title,desc,action){const visibleTitle=title==='Rotina-base'?'Rotina':title;return `<button class="menu-link" onclick="${action}"><i class="fa-solid ${icon}"></i><span>${visibleTitle}<small>${desc}</small></span><i class="fa-solid fa-chevron-right" style="color:var(--muted)"></i></button>`}
function openModal(title,subtitle,body,footer=''){const closeLabel=typeof t==='function'?t('common.close'):'Fechar';document.body.classList.add('modal-open');modalRoot.innerHTML=`<div class="modal-backdrop" role="presentation" onclick="if(event.target===this)closeModal()"><div class="modal" role="dialog" aria-modal="true" aria-label="${escapeHtml(title)}"><div class="modal-head"><div><h2>${title}</h2>${subtitle?`<p>${subtitle}</p>`:''}</div><button class="modal-close" onclick="closeModal()" aria-label="${escapeHtml(closeLabel)}"><i class="fa-solid fa-xmark"></i></button></div>${body}${footer}</div></div>`;if(typeof applyI18n==='function')applyI18n(modalRoot);requestAnimationFrame(()=>{const modal=modalRoot.querySelector('.modal');if(modal)modal.scrollTop=0})}
function closeModal(){document.body.classList.remove('modal-open');modalRoot.innerHTML=''}
const OLEIRO_LOADING_DELAY_MS=600;let _oleiroLoadingDepth=0;let _oleiroLoadingTimer=null;
function ensureGlobalLoadingStyles(){if(document.getElementById('globalLoadingStyles'))return;const style=document.createElement('style');style.id='globalLoadingStyles';style.textContent=`.global-loading[hidden]{display:none!important}.global-loading{position:fixed;z-index:260;inset:0;display:grid;place-items:center;background:rgba(245,244,239,.78);backdrop-filter:blur(8px)}.dark .global-loading{background:rgba(20,28,23,.78)}.global-loading-card{min-width:150px;padding:18px 20px;border:1px solid var(--border);border-radius:18px;background:var(--surface);box-shadow:var(--shadow);display:flex;flex-direction:column;align-items:center;text-align:center;gap:4px}.global-loading-card strong{font-size:13px}.global-loading-card small{font-size:10px;color:var(--muted)}.global-loading-spinner{width:28px;height:28px;border:3px solid var(--primary-soft);border-top-color:var(--primary);border-radius:50%;margin-bottom:6px;animation:oleiroGlobalSpin .8s linear infinite}@keyframes oleiroGlobalSpin{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.global-loading-spinner{animation:none}}`;document.head.appendChild(style)}
function ensureGlobalLoading(){ensureGlobalLoadingStyles();let el=document.getElementById('globalLoading');if(el)return el;el=document.createElement('div');el.id='globalLoading';el.className='global-loading';el.hidden=true;const loading=typeof t==='function'?t('common.loading'):'Carregando...';el.innerHTML=`<div class="global-loading-card"><span class="global-loading-spinner" aria-hidden="true"></span><strong>${escapeHtml(loading)}</strong></div>`;document.body.appendChild(el);return el}
function beginGlobalLoading(delay=OLEIRO_LOADING_DELAY_MS){_oleiroLoadingDepth+=1;if(_oleiroLoadingDepth!==1)return;clearTimeout(_oleiroLoadingTimer);_oleiroLoadingTimer=setTimeout(()=>{const el=ensureGlobalLoading();el.hidden=false},delay)}
function endGlobalLoading(){_oleiroLoadingDepth=Math.max(0,_oleiroLoadingDepth-1);if(_oleiroLoadingDepth)return;clearTimeout(_oleiroLoadingTimer);_oleiroLoadingTimer=null;const el=document.getElementById('globalLoading');if(el)el.hidden=true}
async function withGlobalLoading(task,delay=OLEIRO_LOADING_DELAY_MS){beginGlobalLoading(delay);try{return await (typeof task==='function'?task():task)}finally{endGlobalLoading()}}
window.OleiroLoading={begin:beginGlobalLoading,end:endGlobalLoading,run:withGlobalLoading,delay:OLEIRO_LOADING_DELAY_MS};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureGlobalLoading,{once:true});else ensureGlobalLoading();

const OLEIRO_ADDRESS='R. São Pedro Novo, 1999, Rodeio - SC, 89136-000';
const OLEIRO_MAPS_URL='https://www.google.com/maps/search/?api=1&query=R.%20S%C3%A3o%20Pedro%20Novo%2C%201999%2C%20Rodeio%20-%20SC%2C%2089136-000';
const OLEIRO_ROUTINE=[['06:00','portal.info.routine.wake'],['06:15–07:30','portal.info.routine.devotional'],['07:30–08:15','portal.info.routine.breakfast'],['08:15–11:15','portal.info.routine.practice'],['11:15–12:00','portal.info.routine.feelings'],['12:00–13:30','portal.info.routine.lunch'],['13:45–15:00','portal.info.routine.activities'],['15:00–15:15','portal.info.routine.snack'],['15:15–16:30','portal.info.routine.activities'],['16:30 em diante','portal.info.routine.evening'],['19:30–21:00','portal.info.routine.nightActivity'],['21:00','portal.info.routine.lodging'],['21:30','portal.info.routine.silence']];
function routineInformationHtml(){return `<div class="info-routine">${OLEIRO_ROUTINE.map(([time,key])=>`<p><strong>${escapeHtml(time)}</strong> — ${escapeHtml(t(key))}</p>`).join('')}<p><small>${escapeHtml(t('portal.info.routineNote'))}</small></p></div>`}
function infoAccordion(){return `<div class="info-accordion"><details id="info-arrival"><summary>${escapeHtml(t('portal.info.arrivalTitle'))} <i class="fa-solid fa-chevron-down"></i></summary><p><strong>${escapeHtml(t('portal.info.address'))}</strong> ${escapeHtml(OLEIRO_ADDRESS)}</p><p>${escapeHtml(t('portal.info.arrivalBody'))}</p><a class="info-action-link" href="${OLEIRO_MAPS_URL}" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-map-location-dot"></i>${escapeHtml(t('portal.info.openMaps'))}</a></details><details id="info-accommodation"><summary>${escapeHtml(t('portal.info.accommodationTitle'))} <i class="fa-solid fa-chevron-down"></i></summary><p>${escapeHtml(t('portal.info.accommodationBody'))}</p></details><details id="info-meals"><summary>${escapeHtml(t('portal.info.mealsTitle'))} <i class="fa-solid fa-chevron-down"></i></summary><p>${escapeHtml(t('portal.info.mealsBody'))}</p></details><details id="info-routine"><summary>${escapeHtml(t('portal.info.routineTitle'))} <i class="fa-solid fa-chevron-down"></i></summary>${routineInformationHtml()}</details><details><summary>${escapeHtml(t('portal.info.principlesTitle'))} <i class="fa-solid fa-chevron-down"></i></summary><p>${escapeHtml(t('portal.info.principlesBody'))}</p></details><details><summary>${escapeHtml(t('portal.info.safetyTitle'))} <i class="fa-solid fa-chevron-down"></i></summary><p>${escapeHtml(t('portal.info.safetyBody'))}</p></details></div>`}
async function logout(){try{if(window.OleiroAuth?.signOut)await withGlobalLoading(()=>window.OleiroAuth.signOut())}catch(error){console.error('Falha ao encerrar sessão:',error)}finally{location.replace(document.body.dataset.root||'../index.html')}}
