function showToast(msg){toastEl.textContent=typeof translateText==='function'?translateText(msg):msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('oleiro-theme',state.theme);document.documentElement.classList.toggle('dark',state.theme==='dark');render()}
function menuLink(icon,title,desc,action){const visibleTitle=title==='Rotina-base'?'Rotina':title;return `<button class="menu-link" onclick="${action}"><i class="fa-solid ${icon}"></i><span>${visibleTitle}<small>${desc}</small></span><i class="fa-solid fa-chevron-right" style="color:var(--muted)"></i></button>`}
function openModal(title,subtitle,body,footer=''){const closeLabel=typeof t==='function'?t('common.close'):'Fechar';document.body.classList.add('modal-open');modalRoot.innerHTML=`<div class="modal-backdrop" role="presentation" onclick="if(event.target===this)closeModal()"><div class="modal" role="dialog" aria-modal="true" aria-label="${escapeHtml(title)}"><div class="modal-head"><div><h2>${title}</h2>${subtitle?`<p>${subtitle}</p>`:''}</div><button class="modal-close" onclick="closeModal()" aria-label="${escapeHtml(closeLabel)}"><i class="fa-solid fa-xmark"></i></button></div>${body}${footer}</div></div>`;if(typeof applyI18n==='function')applyI18n(modalRoot);requestAnimationFrame(()=>{const modal=modalRoot.querySelector('.modal');if(modal)modal.scrollTop=0})}
function closeModal(){document.body.classList.remove('modal-open');modalRoot.innerHTML=''}
const OLEIRO_LOADING_DELAY_MS=600;let _oleiroLoadingDepth=0;let _oleiroLoadingTimer=null;
function ensureGlobalLoadingStyles(){if(document.getElementById('globalLoadingStyles'))return;const style=document.createElement('style');style.id='globalLoadingStyles';style.textContent=`.global-loading[hidden]{display:none!important}.global-loading{position:fixed;z-index:260;inset:0;display:grid;place-items:center;background:rgba(245,244,239,.78);backdrop-filter:blur(8px)}.dark .global-loading{background:rgba(20,28,23,.78)}.global-loading-card{min-width:150px;padding:18px 20px;border:1px solid var(--border);border-radius:18px;background:var(--surface);box-shadow:var(--shadow);display:flex;flex-direction:column;align-items:center;text-align:center;gap:4px}.global-loading-card strong{font-size:13px}.global-loading-card small{font-size:10px;color:var(--muted)}.global-loading-spinner{width:28px;height:28px;border:3px solid var(--primary-soft);border-top-color:var(--primary);border-radius:50%;margin-bottom:6px;animation:oleiroGlobalSpin .8s linear infinite}@keyframes oleiroGlobalSpin{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.global-loading-spinner{animation:none}}`;document.head.appendChild(style)}
function ensureGlobalLoading(){ensureGlobalLoadingStyles();let el=document.getElementById('globalLoading');if(el)return el;el=document.createElement('div');el.id='globalLoading';el.className='global-loading';el.hidden=true;const loading=typeof t==='function'?t('common.loading'):'Carregando...';el.innerHTML=`<div class="global-loading-card"><span class="global-loading-spinner" aria-hidden="true"></span><strong>${escapeHtml(loading)}</strong></div>`;document.body.appendChild(el);return el}
function beginGlobalLoading(delay=OLEIRO_LOADING_DELAY_MS){_oleiroLoadingDepth+=1;if(_oleiroLoadingDepth!==1)return;clearTimeout(_oleiroLoadingTimer);_oleiroLoadingTimer=setTimeout(()=>{const el=ensureGlobalLoading();el.hidden=false},delay)}
function endGlobalLoading(){_oleiroLoadingDepth=Math.max(0,_oleiroLoadingDepth-1);if(_oleiroLoadingDepth)return;clearTimeout(_oleiroLoadingTimer);_oleiroLoadingTimer=null;const el=document.getElementById('globalLoading');if(el)el.hidden=true}
async function withGlobalLoading(task,delay=OLEIRO_LOADING_DELAY_MS){beginGlobalLoading(delay);try{return await (typeof task==='function'?task():task)}finally{endGlobalLoading()}}
window.OleiroLoading={begin:beginGlobalLoading,end:endGlobalLoading,run:withGlobalLoading,delay:OLEIRO_LOADING_DELAY_MS};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureGlobalLoading,{once:true});else ensureGlobalLoading();

const OLEIRO_ADDRESS='R. São Pedro Novo, 1999, Rodeio - SC, 89136-000';
const OLEIRO_MAPS_URL='https://www.google.com/maps/search/?api=1&query=R.%20S%C3%A3o%20Pedro%20Novo%2C%201999%2C%20Rodeio%20-%20SC%2C%2089136-000';
const OLEIRO_ROUTINE=[['06:00','portal.info.routine.wake'],['06:15–07:30','portal.info.routine.devotional'],['07:30–08:15','portal.info.routine.breakfast'],['08:15–11:15','portal.info.routine.practice'],['11:15–12:00','portal.info.routine.feelings'],['12:00–13:30','portal.info.routine.lunch'],['13:45–15:00','portal.info.routine.activities'],['15:00–15:15','portal.info.routine.snack'],['15:15–16:30','portal.info.routine.activities'],['16:30+','portal.info.routine.evening'],['19:30–21:00','portal.info.routine.nightActivity'],['21:00','portal.info.routine.lodging'],['21:30','portal.info.routine.silence']];

/* Round 29 — release metadata and safe update notice. Static HTTP only; no Firestore reads. */
const OLEIRO_RELEASE_SCRIPT_URL=document.currentScript?.src||'';
const OLEIRO_RELEASE_POLL_MS=180000;
const OLEIRO_RELEASE_MIN_CHECK_MS=30000;
let _oleiroLoadedRelease=null;
let _oleiroLatestRelease=null;
let _oleiroReleaseLastCheck=0;
const OLEIRO_RELEASE_MESSAGES={
  pt:{'release.cardTitle':'Versão do software','release.version':'Versão','release.build':'Build','release.commit':'Commit','release.published':'Publicado em','release.notAvailable':'Informação de versão indisponível','release.updateTitle':'Nova versão disponível','release.updateBody':'Salve o que estiver preenchendo antes de atualizar. A página não será recarregada automaticamente.','release.updateNow':'Atualizar agora'},
  en:{'release.cardTitle':'Software version','release.version':'Version','release.build':'Build','release.commit':'Commit','release.published':'Published','release.notAvailable':'Version information unavailable','release.updateTitle':'New version available','release.updateBody':'Save anything you are filling in before updating. The page will not reload automatically.','release.updateNow':'Update now'},
  es:{'release.cardTitle':'Versión del software','release.version':'Versión','release.build':'Build','release.commit':'Commit','release.published':'Publicado el','release.notAvailable':'Información de versión no disponible','release.updateTitle':'Nueva versión disponible','release.updateBody':'Guarda lo que estés completando antes de actualizar. La página no se recargará automáticamente.','release.updateNow':'Actualizar ahora'}
};
for(const [lang,rows] of Object.entries(OLEIRO_RELEASE_MESSAGES)){if(window.OleiroI18nMessages?.[lang])Object.assign(window.OleiroI18nMessages[lang],rows)}
function releaseText(key){if(typeof t==='function')return t(key);const lang=(typeof currentLanguage==='function'?currentLanguage():'pt')||'pt';return OLEIRO_RELEASE_MESSAGES[lang]?.[key]||OLEIRO_RELEASE_MESSAGES.pt[key]||key}
function releaseManifestUrl(){try{return new URL('../../release.json',OLEIRO_RELEASE_SCRIPT_URL||location.href)}catch{return new URL('../release.json',location.href)}}
function normalizedRelease(value){if(!value||typeof value!=='object')return null;const commit=String(value.commit||'').trim();if(!commit)return null;return {version:String(value.version||'').trim()||commit.slice(0,12),build:String(value.build??'').trim()||'—',commit,publishedAt:String(value.publishedAt||'').trim()}}
async function fetchReleaseManifest(){const url=releaseManifestUrl();url.searchParams.set('_',String(Date.now()));const response=await fetch(url.toString(),{cache:'no-store'});if(!response.ok)throw new Error(`release manifest ${response.status}`);return normalizedRelease(await response.json())}
function releaseDate(value){if(!value)return '—';const date=new Date(value);if(Number.isNaN(date.getTime()))return value;const lang=typeof currentLanguage==='function'?currentLanguage():'pt';return new Intl.DateTimeFormat(lang==='en'?'en-US':lang==='es'?'es-ES':'pt-BR',{dateStyle:'short',timeStyle:'short'}).format(date)}
function releaseInformationHtml(){const row=_oleiroLoadedRelease;return `<div class="release-info">${row?`<p><strong>${escapeHtml(releaseText('release.version'))}:</strong> <span data-release-version>${escapeHtml(row.version)}</span></p><p><strong>${escapeHtml(releaseText('release.build'))}:</strong> <span data-release-build>${escapeHtml(row.build)}</span></p><p><strong>${escapeHtml(releaseText('release.commit'))}:</strong> <code data-release-commit>${escapeHtml(row.commit.slice(0,12))}</code></p><p><strong>${escapeHtml(releaseText('release.published'))}:</strong> <span data-release-published>${escapeHtml(releaseDate(row.publishedAt))}</span></p>`:`<p data-release-unavailable>${escapeHtml(releaseText('release.notAvailable'))}</p>`}</div>`}
function refreshReleaseMetadata(){document.querySelectorAll('#info-software .release-info').forEach(el=>{el.outerHTML=releaseInformationHtml()})}
function ensureReleaseStyles(){if(document.getElementById('oleiroReleaseStyles'))return;const style=document.createElement('style');style.id='oleiroReleaseStyles';style.textContent=`.release-info p{margin:8px 0}.release-info code{font-size:12px;overflow-wrap:anywhere}.oleiro-update-banner{position:fixed;z-index:245;left:12px;right:12px;bottom:calc(76px + env(safe-area-inset-bottom));max-width:760px;margin:auto;padding:12px 14px;border:1px solid var(--border);border-radius:16px;background:var(--surface);box-shadow:var(--shadow);display:flex;align-items:center;gap:12px}.oleiro-update-banner>div{min-width:0;flex:1}.oleiro-update-banner strong{display:block;font-size:13px}.oleiro-update-banner p{margin:2px 0 0;font-size:11px;color:var(--muted);line-height:1.4}.oleiro-update-banner .btn{flex:0 0 auto;min-height:38px;padding:8px 12px}@media(max-width:560px){.oleiro-update-banner{align-items:stretch;flex-direction:column;bottom:calc(72px + env(safe-area-inset-bottom))}.oleiro-update-banner .btn{width:100%}}`;document.head.appendChild(style)}
function showReleaseUpdate(latest){_oleiroLatestRelease=latest;ensureReleaseStyles();let banner=document.getElementById('oleiroUpdateBanner');if(!banner){banner=document.createElement('aside');banner.id='oleiroUpdateBanner';banner.className='oleiro-update-banner';banner.setAttribute('role','status');document.body.appendChild(banner)}banner.innerHTML=`<div><strong>${escapeHtml(releaseText('release.updateTitle'))}</strong><p>${escapeHtml(releaseText('release.updateBody'))}</p></div><button class="btn btn-primary" type="button" id="oleiroUpdateNow">${escapeHtml(releaseText('release.updateNow'))}</button>`;banner.querySelector('#oleiroUpdateNow')?.addEventListener('click',()=>{const url=new URL(location.href);url.searchParams.set('_build',latest.commit.slice(0,12));location.assign(url.toString())})}
async function checkOleiroRelease(force=false){const now=Date.now();if(!force&&now-_oleiroReleaseLastCheck<OLEIRO_RELEASE_MIN_CHECK_MS)return _oleiroLatestRelease||_oleiroLoadedRelease;_oleiroReleaseLastCheck=now;try{const latest=await fetchReleaseManifest();if(!latest)return null;if(!_oleiroLoadedRelease){_oleiroLoadedRelease=latest;_oleiroLatestRelease=latest;refreshReleaseMetadata();return latest}_oleiroLatestRelease=latest;if(latest.commit!==_oleiroLoadedRelease.commit)showReleaseUpdate(latest);return latest}catch(error){console.debug('Release check indisponível:',error?.message||error);return null}}
function startOleiroRelease(){ensureReleaseStyles();checkOleiroRelease(true);setInterval(()=>checkOleiroRelease(false),OLEIRO_RELEASE_POLL_MS);window.addEventListener('focus',()=>checkOleiroRelease(false),{passive:true});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')checkOleiroRelease(false)})}
window.OleiroRelease={check:()=>checkOleiroRelease(true),current:()=>_oleiroLoadedRelease,latest:()=>_oleiroLatestRelease};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startOleiroRelease,{once:true});else startOleiroRelease();

function routineInformationHtml(){return `<div class="info-routine">${OLEIRO_ROUTINE.map(([time,key])=>`<p><strong>${escapeHtml(time)}</strong> — ${escapeHtml(t(key))}</p>`).join('')}<p><small>${escapeHtml(t('portal.info.routineNote'))}</small></p></div>`}
function infoAccordion(){return `<div class="info-accordion"><details id="info-arrival"><summary>${escapeHtml(t('portal.info.arrivalTitle'))} <i class="fa-solid fa-chevron-down"></i></summary><p><strong>${escapeHtml(t('portal.info.address'))}</strong> ${escapeHtml(OLEIRO_ADDRESS)}</p><p>${escapeHtml(t('portal.info.arrivalBody'))}</p><a class="info-action-link" href="${OLEIRO_MAPS_URL}" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-map-location-dot"></i>${escapeHtml(t('portal.info.openMaps'))}</a></details><details id="info-accommodation"><summary>${escapeHtml(t('portal.info.accommodationTitle'))} <i class="fa-solid fa-chevron-down"></i></summary><p>${escapeHtml(t('portal.info.accommodationBody'))}</p></details><details id="info-meals"><summary>${escapeHtml(t('portal.info.mealsTitle'))} <i class="fa-solid fa-chevron-down"></i></summary><p>${escapeHtml(t('portal.info.mealsBody'))}</p></details><details id="info-routine"><summary>${escapeHtml(t('portal.info.routineTitle'))} <i class="fa-solid fa-chevron-down"></i></summary>${routineInformationHtml()}</details><details><summary>${escapeHtml(t('portal.info.principlesTitle'))} <i class="fa-solid fa-chevron-down"></i></summary><p>${escapeHtml(t('portal.info.principlesBody'))}</p></details><details><summary>${escapeHtml(t('portal.info.safetyTitle'))} <i class="fa-solid fa-chevron-down"></i></summary><p>${escapeHtml(t('portal.info.safetyBody'))}</p></details><details id="info-software"><summary>${escapeHtml(releaseText('release.cardTitle'))} <i class="fa-solid fa-chevron-down"></i></summary>${releaseInformationHtml()}</details></div>`}
async function logout(){try{if(window.OleiroAuth?.signOut)await withGlobalLoading(()=>window.OleiroAuth.signOut())}catch(error){console.error('Falha ao encerrar sessão:',error)}finally{location.replace(document.body.dataset.root||'../index.html')}}
