function escapeHtml(value){return String(value??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(iso,short=false){if(!iso)return '—';const d=new Date(iso+'T12:00:00');const locale=typeof currentLocale==='function'?currentLocale():'pt-BR';return new Intl.DateTimeFormat(locale,short?{day:'2-digit',month:'2-digit'}:{day:'2-digit',month:'short'}).format(d).replace('.','')}
function dayName(iso){const locale=typeof currentLocale==='function'?currentLocale():'pt-BR';return new Intl.DateTimeFormat(locale,{weekday:'short'}).format(new Date(iso+'T12:00:00')).replace('.','').toUpperCase()}
function longDate(iso){const d=new Date(iso+'T12:00:00');const locale=typeof currentLocale==='function'?currentLocale():'pt-BR';const text=new Intl.DateTimeFormat(locale,{weekday:'long',day:'2-digit',month:'long'}).format(d);return text.charAt(0).toUpperCase()+text.slice(1)}
function statusMeta(s){return {pending:['Planejamento pendente','warning'],analysis:['Em análise','info'],adjustments:['Ajustes solicitados','warning'],approved:['Aprovado','success'],rejected:['Rejeitado','danger'],proposed:['Proposta','warning'],confirmed:['Confirmada','success'],change:['Mudança solicitada','warning'],change_requested:['Mudança solicitada','warning']}[s]||[s,'']}
function badge(label,type=''){return `<span class="badge ${type}">${label}</span>`}
function addDays(iso,days){const d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function dateRange(start,count){return Array.from({length:count},(_,i)=>addDays(start,i))}
function agendaRangeLabel(start){const end=addDays(start,6);return `${fmtDate(start)} – ${fmtDate(end)}`}
function getSessions(date,_volunteerOnly=false){
  const rows=(state.sessions||[]).filter(s=>String(s.date)===String(date)).map(session=>{const activity=session.activity||(state.activities||[]).find(a=>String(a.id)===String(session.activityId))||{id:session.activityId,name:session.activityName||'Atividade',description:session.activityDescription||'',duration:Number(session.duration||60),participation:session.participation||'Livre',materials:session.materials||'',notes:session.notes||'',period:session.period||'Sem preferência',time:session.time||'',owner:session.ownerName||'Voluntário'};return {sessionId:session.id,activity,date:session.date,status:session.status||'proposed',group:session.groupId||'A definir',raw:session}});
  if(rows.length)return rows.sort((a,b)=>String(a.activity.time||'').localeCompare(String(b.activity.time||''))||String(a.activity.name||'').localeCompare(String(b.activity.name||''),'pt-BR'));
  const fallback=[];(state.activities||[]).forEach(a=>(a.dates||[]).forEach(d=>{if(d===date)fallback.push({sessionId:null,activity:a,date:d,status:state.sessionStatus?.[`${a.id}-${d}`]||'proposed',group:state.sessionGroups?.[`${a.id}-${d}`]||'A definir'})}));return fallback.sort((a,b)=>String(a.activity.time||'').localeCompare(String(b.activity.time||'')));
}
