(function initAuthService(){
  async function firebaseContext(){if(!window.OleiroFirebase)throw new Error('Backend indisponível.');const context=await window.OleiroFirebase.ready;if(!context?.configured)throw new Error('Firebase ainda não foi configurado.');return context;}
  function normalizeRole(role){if(role==='admin'||role==='coordinator'||role==='activity_assistant')return 'manager';if(role==='volunteer')return 'volunteer';return 'inactive'}
  function appRootUrl(){const marker='/CasaDoOleiro/';const index=location.pathname.indexOf(marker);const path=index>=0?location.pathname.slice(0,index+marker.length):'/';return `${location.origin}${path}`}
  function inactiveAccessError(){const error=new Error('Seu cadastro está inativo. Entre em contato com a equipe da Casa do Oleiro para verificar o acesso.');error.code='oleiro/inactive';return error}
  function offlineAccessError(){const error=new Error('Sem conexão com a internet no momento. Verifique sua rede e tente novamente.');error.code='oleiro/offline';return error}
  function metric(name,started,count,meta={}){window.OleiroServices?.recordQuery?.(name,started,count,meta)}
  async function activeApplication(context,uid){const {firestore}=context.modules,started=Date.now();const q=firestore.query(firestore.collection(context.db,'applications'),firestore.where('participantUids','array-contains',uid),firestore.where('active','==',true),firestore.limit(1));const snapshot=await firestore.getDocs(q);metric('auth/active-application',started,snapshot.size,{uid:String(uid),limit:1});const doc=snapshot.docs[0];return doc?{id:doc.id,...doc.data()}:null}
  async function volunteerProfile(context,uid){const {firestore}=context.modules,started=Date.now();const snapshot=await firestore.getDoc(firestore.doc(context.db,'volunteer_profiles',uid));metric('auth/volunteer-profile',started,snapshot.exists()?1:0,{uid:String(uid)});return snapshot.exists()?{id:snapshot.id,...snapshot.data()}:null}
  async function ownAccessDocument(context,user){const {firestore,auth}=context.modules,started=Date.now();try{const snapshot=await firestore.getDoc(firestore.doc(context.db,'users',user.uid));metric('auth/access-document',started,snapshot.exists()?1:0,{uid:String(user.uid)});return snapshot}catch(error){const message=String(error?.message||'');if(error?.code==='unavailable'||/offline|failed to get/i.test(message))throw offlineAccessError();if(error?.code==='permission-denied'||/missing or insufficient permissions/i.test(message)){await auth.signOut(context.auth);throw inactiveAccessError()}throw error}}
  async function markFirstPortalAccess(context,user,access){if(access?.firstPortalAccessAt)return access;const {firestore}=context.modules;try{await firestore.updateDoc(firestore.doc(context.db,'users',user.uid),{firstPortalAccessAt:firestore.serverTimestamp(),updatedAt:firestore.serverTimestamp()});return {...access,firstPortalAccessAt:new Date().toISOString()}}catch(error){console.warn('Não foi possível registrar o primeiro acesso:',error);return access}}
  async function sessionFromUser(context,user){
    const {auth}=context.modules;const userSnapshot=await ownAccessDocument(context,user);
    if(!userSnapshot.exists()){await auth.signOut(context.auth);const error=new Error('Este acesso ainda não foi liberado pela Casa do Oleiro.');error.code='oleiro/not-released';throw error}
    let access=userSnapshot.data();if(access.active!==true){await auth.signOut(context.auth);throw inactiveAccessError()}
    const role=normalizeRole(access.role);if(role==='manager')return {role,mode:null,uid:user.uid,email:user.email||null,user:access};if(role!=='volunteer'){await auth.signOut(context.auth);throw inactiveAccessError()}
    access=await markFirstPortalAccess(context,user,access);
    const [application,profile]=await Promise.all([activeApplication(context,user.uid),volunteerProfile(context,user.uid)]);if(!application){await auth.signOut(context.auth);throw inactiveAccessError()}
    const mode=application.status==='approved'?'approved':'candidate';return {role:'volunteer',mode,uid:user.uid,email:user.email||null,user:access,profile,application};
  }
  window.OleiroAuth={
    async signIn({email,password}){if(!email||!password)throw new Error('Informe e-mail e senha.');const context=await firebaseContext();const {auth}=context.modules;try{const credential=await auth.signInWithEmailAndPassword(context.auth,email,password);return await sessionFromUser(context,credential.user)}catch(error){if(error?.code==='auth/invalid-credential'||error?.code==='auth/user-not-found'||error?.code==='auth/wrong-password'){const invalid=new Error('E-mail ou senha inválidos.');invalid.code='oleiro/invalid-credential';throw invalid}if(error?.code==='auth/too-many-requests')throw new Error('Muitas tentativas. Aguarde alguns minutos e tente novamente.');if(error?.code==='oleiro/offline')throw error;if(error?.message)throw error;throw new Error('Não foi possível entrar.')}},
    async sendPasswordReset(email,{language=null}={}){const normalized=String(email||'').trim().toLowerCase();if(!normalized||!normalized.includes('@'))throw new Error('Informe um e-mail válido.');const context=await firebaseContext();const {auth}=context.modules;try{context.auth.languageCode=language||((typeof currentLanguage==='function'&&currentLanguage())||'pt');await auth.sendPasswordResetEmail(context.auth,normalized,{url:appRootUrl(),handleCodeInApp:false});return true}catch(error){if(error?.code==='auth/user-not-found')return true;if(error?.code==='auth/invalid-email')throw new Error('Informe um e-mail válido.');if(error?.code==='auth/too-many-requests')throw new Error('Muitas solicitações. Aguarde alguns minutos e tente novamente.');throw new Error('Não foi possível enviar o e-mail de recuperação.')}},
    async currentSession(){const context=await firebaseContext();if(typeof context.auth.authStateReady==='function')await context.auth.authStateReady();const user=context.auth.currentUser;return user?sessionFromUser(context,user):null},
    async signOut(){const context=await firebaseContext();await context.modules.auth.signOut(context.auth)}
  };
})();
